### ISSUE TITLE
Visualize the connection between search results in list and in map

### ISSUE THREAD

**Issue by jacobwod** [hajkmap/Hajk#1002]
Currently the only connection between results list and map is when user selects an item. This makes the item highlighted and shows item's details. It's a good feature for viewing details of a specific result item, but does not help the user to get a better overview of "which result goes where in the map?". 

To fix this issue and aid users with a clearer connection between results list and the map, I propose the following solution: **as user's mouse hovers the results list, items get highlighted in the map**. (Thanks to @JakubPelka for this idea!)

https://user-images.githubusercontent.com/110222/153143813-4b52aaa8-fd26-42e5-a16c-e6ad5b87d73f.mov

![Skärmavbild 2022-02-10 kl  10 42 18](https://user-images.githubusercontent.com/110222/153380327-e216f3d0-a9ed-44df-ba74-991bf7400831.png)

**Comment by Hallbergs** [comment]
I love it!!
