### ISSUE TITLE
The Import KML Dialog is broken (Draw Plugin)

### ISSUE THREAD

**Issue by jesade-vbg** [hajkmap/Hajk#1006]
The import KML Dialog is broken in the draw plugin.

![image](https://user-images.githubusercontent.com/73874338/154010507-586dd8e9-ca99-4baa-a9f1-99fcf32f9505.png)

Console reports error from react-markdown:
![image](https://user-images.githubusercontent.com/73874338/154010740-b805615a-48db-4b57-a012-c207f0829ec0.png)

**Comment by Hallbergs** [comment]
Seems to work in 3.9, see image:
![image](https://user-images.githubusercontent.com/43059093/154012663-1f0e84cb-9ddf-47d5-8c93-c237d765d060.png)

Are you building from develop?

**Comment by jesade-vbg** [comment]
Yes, develop.

**Comment by jacobwod** [comment]
Hi @jesade-vbg! Can you see if adding one more option solves it?

After this:
https://github.com/hajkmap/Hajk/blob/611acdf04d07a0bc4aa19fced43ab2ebe4189213/new-client/src/plugins/Draw/DrawView.js#L183

Add this:
```javascript
useLegacyNonMarkdownRenderer: true
```

**Comment by perosoderstrom** [comment]
I have seen the same issue in develop. 
Just tested, and adding 
`useLegacyNonMarkdownRenderer: true `
solves the bug.

**Comment by jesade-vbg** [comment]
Ok, thanx. I'll push to dev.

**Comment by jesade-vbg** [comment]
Fixed using previous comments.
https://github.com/hajkmap/Hajk/commit/017c1480bd487bd9bc09a6e03ab5149904680a19
