### ISSUE TITLE
Overhaul of FeatureInfo (i.e. Infoclick)

### ISSUE THREAD

**Issue by jacobwod** [hajkmap/Hajk#1034]
*I'm adding this issue, as I couldn't find any covering this - in spite of an old ongoing discussion, and complete mock-ups.*

We need a way to group feature info responses by layer, similarly to how it's done in search results, where data sets are the first step displayed, before user sees the list of actual results.

There's a mockup that I've done one ugly edit to. The point of my edit is to visualise one more step between step 2-3. I think you get the idea.

**I imagine this will be an on-off switch per map where current functionality will remain untouched.**
![Skärmavbild 2022-03-15 kl  10 15 54](https://user-images.githubusercontent.com/110222/158345309-e8f72afb-b685-4ec3-8fd4-9526bc898d7e.png)

**Comment by jacobwod** [comment]
Some initial progress: the first screen that shows a list of returned feature collections:
![Skärmavbild 2022-03-17 kl  12 30 57](https://user-images.githubusercontent.com/110222/158799826-72baf342-bcbc-43e0-b36b-9320c6adb2cd.png)

**Comment by Hallbergs** [comment]
I'm really looking forward to testing this out! 🥳

**Comment by jacobwod** [comment]
Today's progress: implemented the features list view and a basic "show all attributes" table in the last step (feature details view).

https://user-images.githubusercontent.com/110222/159006775-c1e835a5-4ba6-4ce9-b624-0962dffb89bd.mov
