### ISSUE TITLE
FMEServer plugin: "STRING" is passed instead of "TEXT" when using FME Desktop 2021

### ISSUE THREAD

**Issue by eri-blan** [hajkmap/Hajk#1041]
**Describe the bug**
The plugin is rendering text fields based on an allowed parameter type "TEXT", however, if publishing a Text parameter using FME Desktop 2021, text parameters get passed as "STRING" and are therefore not rendered.

**To Reproduce**

1. Open a workspace in FME Desktop 2021
2. Add a user parameter that is Plain text (uniline)
3. Publish to FME Server and set it up in the plugin settings
4. See that the parameter is not rendered

**Expected behavior**
The plugin accepts "STRING" parameters as text fields as well.

**Comment by Hallbergs** [comment]
Will make sure this is fixed in 3.9
