### ISSUE TITLE
Map canvas stretches underneath the Drawer if map is loaded with drawer locked

### ISSUE THREAD

**Issue by jacobwod** [hajkmap/Hajk#1058]
See title for description.

Below is a demonstration of the problem.

I show it in a 1366 px wide viewport. The map canvas should be 1366 when drawer is hidden, while 1366 minus drawer's width when it's visible. This works as intended when we toggle drawer. 

However, if map starts with drawer visible and locked (i.e. "permanent"), **the map canvas stretches underneath the drawer**.

---

OK, no drawer, canvas as wide as the viewport:

![Skärmavbild 2022-04-22 kl  09 35 19](https://user-images.githubusercontent.com/110222/164631418-ac684d4c-affd-4215-88d9-a54bf5f1593b.png)

---

OK, drawer locked and canvas gets narrowed down on the lock event:

![Skärmavbild 2022-04-22 kl  09 35 31](https://user-images.githubusercontent.com/110222/164632279-f4092e42-a94a-4be2-b397-995147b1827d.png)

---

Not OK: map loads with drawer already visible and locked but the map canvas occupies the invisible space underneath the drawer too. It shouldn't. It should be exactly as in the second screenshot.

![Skärmavbild 2022-04-22 kl  09 35 43](https://user-images.githubusercontent.com/110222/164633081-d7127ac2-2c55-469d-8512-5eb4b7e5f446.png)

**Comment by Hallbergs** [comment]
Nice and simple fix, i like it! 👍
