### ISSUE TITLE
Provide admin-option to disable autocomplete in search

### ISSUE THREAD

**Issue by Hallbergs** [hajkmap/Hajk#1070]
In some Hajk-setups the autocomplete-functionality in Hajk seems to do more harm than good. For instance, some users seems to believe that the autocomplete-list is the actual search-results (making them a bit disappointed when they don't find what they are looking for).

Let's provide an admin-option that can be used to disable the autocomplete, and show the actual results right away instead.

With autocomplete active: (We show the autocomplete after around 300ms)
![autocomplete_search](https://user-images.githubusercontent.com/43059093/166411838-15e3cd0a-23e2-43b4-a71a-413e594fd158.png)

With autocomplete disabled: (We jump straight to the results after around 300ms)
![regular_search](https://user-images.githubusercontent.com/43059093/166411866-ad340832-dda5-4daa-ac31-2e0c1cac634c.png)

**Comment by Hallbergs** [comment]
Just linked a pr (#1071) to close this @jesade-vbg @maan002. Please check that it works as you want.

**Comment by jacobwod** [comment]
Really useful addition, great to have the option available! 👍
