### ISSUE TITLE
MapSwitcher: sort by label, not file name

### ISSUE THREAD

**Issue by jacobwod** [hajkmap/Hajk#1084]
Currently MapSwitcher sorts by the file name, which can lead to funny-looking results:
![Skärmavbild 2022-05-17 kl  15 08 11](https://user-images.githubusercontent.com/110222/168818164-9fc793cf-3639-46e1-97e1-7370c7236493.png)

It'd be better to sort alphabetically by the display name.

**Comment by Hallbergs** [comment]
I agree!
