### ISSUE TITLE
Admin: Give LayerInfoDialog artificial breathing

### ISSUE THREAD

**Issue by jesade-vbg** [hajkmap/Hajk#1085]
If nobody is against it I would like to make some fixes to the layerinfo dialog.
I think it's worth spending an hour or 2 to make it better.
Most fixes will be placed in index.css.

![image](https://user-images.githubusercontent.com/73874338/168846452-fe137127-b624-4b63-90b8-581847efa7d4.png)

**Comment by Hallbergs** [comment]
Go for it :)

**Comment by jesade-vbg** [comment]
The changes does not make it perfect, but it will help.

* Semitransparent background for dialog (All modal dialogs are affected)
* It is now possible to scroll the dialog content
* The info textarea is now bigger
* Some of the inputs are made wider
* Labels and inputs are better aligned

![image](https://user-images.githubusercontent.com/73874338/169023002-e442fd6c-2625-4426-b7a0-fcce332b6563.png)

![image](https://user-images.githubusercontent.com/73874338/169021382-5497b95a-11c0-4970-99ff-da7624d7fb76.png)

All modal dialogs will get semitransparent background.
![image](https://user-images.githubusercontent.com/73874338/169022411-b0195d0f-d455-43e2-980d-46b48bce06b0.png)

**Comment by jacobwod** [comment]
Way better now!

This got me thinking: perhaps we can throw away the ideas for Admin 4 and just keep fixing stuff with CSS in the current version? 🤣 💯 🥇 

(Seriously though: good fix @jesade-vbg, our admins are looking forward to it!)

**Comment by Hallbergs** [comment]
Looks 🔥🔥🔥 

Good job!

**Comment by jesade-vbg** [comment]
Thanx, It was a quick fix.
Oh no @jacobwod 🤣, I don't think it's allowed to joke about that 🤣
