### ISSUE TITLE
Allow users to change the z-index of visible layers

### ISSUE THREAD

**Issue by jacobwod** [hajkmap/Hajk#1086]
Currently the z-index of layers in a map is controlled once for each map by admins through a setting in Admin UI.

However, it is not always possible to predict the best z-index for layers and the number of combinations is huge. 

One possibility is to **add another tab in the LayerSwitcher, called "Drawing order"** or something similar. That tab would display all currently visible layers as a draggable list (or with up and down arrows – the exact UI implementation is to be discussed).

**Comment by jesade-vbg** [comment]
Good and interresting idea! It could also add the possibility to remove a specific visible layer.  I sometimes find it really hard to find a already visible layer to turn it off. I usually end up using "Hide all active layers". 

Maybe the tab could be called "Active Layers" or "Active layers",  with the ability to both change order and visibility/remove.

I'm just thinking out loud

**Comment by Hallbergs** [comment]
<img src="https://media4.giphy.com/media/fxZPrsux3vlFY6UQs6/giphy.gif"/>

**Comment by jacobwod** [comment]
First incarnation ready. I have some more ideas, such as toggling the visibility of active layers and controlling the opacity directly from the draw order view. Also, the zIndex value will be hidden (this is just a beta).

![Skärmavbild 2022-06-02 kl  09 21 14](https://user-images.githubusercontent.com/110222/171575746-6533bd1c-a704-4cec-95ae-3d8e6a0330d8.png)

**Comment by jacobwod** [comment]
Further improvements:
![Skärmavbild 2022-06-02 kl  14 50 21](https://user-images.githubusercontent.com/110222/171633122-59a99f30-4dc0-4bad-8c29-d041a7f565b0.png)

**Comment by jacobwod** [comment]
Ah, even better: let's make use of the recently added possibility to set custom icons for each layer!

![image](https://user-images.githubusercontent.com/110222/171634626-b6463f5f-9a83-4539-9668-12c4a5250cfd.png)
