### ISSUE TITLE
Search: WMS-layers and WFS-layers in search result list

### ISSUE THREAD

**Issue by jool-kba** [hajkmap/Hajk#1097]
I’ve talked with co-workers and we have found a bug regarding the search tool. The tool should be able to differentiate between wfs search layers and searchable wms-layers. When there are many wms-layers active as search services, the search hits could result in a long list where it could be hard to find the hits you are looking for. We suggest that wms-layers hits should only be visible when the search option ”search visible layers only” is activated and that wms-layers should not be included in the ”limit search services” option list.

**Comment by jacobwod** [comment]
Ping, @jool-kba?

**Comment by jool-kba** [comment]
We have reconsidered the issue and we think it should be closed.
