### ISSUE TITLE
Styling in documenthandler

### ISSUE THREAD

**Issue by lina-sbk-gbg** [hajkmap/Hajk#1105]
It seems that handling images in the documenthandler does not work in the same way as in 3.9. Could it be that mui4 and mui5 have different ways of handling the placement and / or size of images. See comparison below.

Version 3.9, the image is small and is centered right
![image](https://user-images.githubusercontent.com/23458086/173762147-acaa1495-b9e2-4d53-b6b5-009bf6cc56e1.png)

Version 3.10 RC1, the image is large and covers the entire width
![image](https://user-images.githubusercontent.com/23458086/173762509-c75d895d-22da-4be6-bbba-e81a1140b073.png)

**Comment by jacobwod** [comment]
I can confirm that in our environment as well. Will investigate.
