### ISSUE TITLE
Problem markup search result on surfaces with border only, no fill

### ISSUE THREAD

**Issue by mdellming** [hajkmap/Hajk#1127]
If we choose to display search results with only border and without fill, we get a problem with some parts of the selection being obscured by other search hit markings when using star marking or clicking on a hit and expanding info (for example, for real estate polygons).
Sometimes only 1 or 2 borders of a polygon appear in the map, and the others seem to fall below nearby items that are in the search hits list but not selected, as if the borders overlap.
When creating selections from the search hits list, for example with star marking, or when marking a post in the list and expanding info for it, we want the selection/expanded object to always end up as the top marking of the map image, both the border and any surface fill, and be displayed as whole polygons /objects in the map.

Requests prio for search result markings:
* general search result - Secondary (shown below, if any of the other options mentioned below are used)
* star selection - Primary (always show selection on top of general search results as whole objects)
* click on search result and expanding info – Primary (always show selection on top of general search results as whole object)

![github_sökträff](https://user-images.githubusercontent.com/107697679/175299843-cf71f92b-18c4-47d7-bf91-cd050b46bc4a.png)

**Comment by Hallbergs** [comment]
I think i've sorted this bug. Fix coming up. 

I understood the issue, and found a logic-error in the code, but i could not reproduce the error for some reason... If the fix doesn't work, we'll just re-open.
