### ISSUE TITLE
Infoclick: Don't display duplicate marker

### ISSUE THREAD

**Issue by jacobwod** [hajkmap/Hajk#1131]
As of #1034, there is a marker being shown when user clicks a spot in map. The purpose is to exactly indicate which point was clicked and it's especially relevant when it comes to polygons. See the example below: without the blue marker user wouldn't have any idea where the click occurred:
![Skärmavbild 2022-07-05 kl  09 08 51](https://user-images.githubusercontent.com/110222/177270121-e9952142-5797-4d1e-be1d-6fd8d200206e.png)

So this is extremely important for polygons.

But, if click occurs on a point (or line) layer, there will be a duplicate symbol. The reason for this is that we use the same marker image to both indicate where the click occurred and to mark the selected feature:

![Skärmavbild 2022-07-05 kl  09 05 47](https://user-images.githubusercontent.com/110222/177270319-99c8e3ed-56e5-4047-b2ff-5b7d22a9e7a9.png)

## Proposed solution
There are at least two possible ways of solving this:
a. use a different image marker 
b. only show the click marker if click resulted in polygon results

The second option, B, is somehow difficult to solve. There will be situations where we get responses from multiple type of layers. Shouldn't the marker be shown at all if at least one of the layers contains point features? How can we be sure that user isn't looking at the polygons and needs to see the click marker?

So, currently, the most feasible solution is A.

**Comment by jacobwod** [comment]
Here's one proposal.

A clear, blue ring indicates where click occurred on the polygon:
![Skärmavbild 2022-07-05 kl  09 59 03](https://user-images.githubusercontent.com/110222/177281765-810fa0bc-fa48-44e0-bdcd-f868639edee0.png)

When it comes to points, the same blue ring is there, but it is non-disturbing now and the icon marker clearly dominates and shows the selected point feature:
![Skärmavbild 2022-07-05 kl  10 13 05](https://user-images.githubusercontent.com/110222/177282000-e99e27af-9fec-4f70-b6af-4a75c678a36b.png)

**Comment by jacobwod** [comment]
I have an even better idea.

**Let's use the existing settings in Admin UI.**

Setting a marker URL, anchor, fill color etc will result in the specified icon to be printed in map. **We will also respect the color setting!** See example below (note that transparency is not used when tinting the icon color, though).

![Skärmavbild 2022-07-05 kl  10 41 37](https://user-images.githubusercontent.com/110222/177287937-51615bec-ec2a-49bb-acb8-3f6b48f99fec.png)
![Skärmavbild 2022-07-05 kl  10 41 32](https://user-images.githubusercontent.com/110222/177287943-ba57a806-9142-48a1-9d02-f93cf4a72f94.png)

Note that **for best result, a white icon should be used, otherwise the color tinting may lead to unexpected results**.

**Comment by Hallbergs** [comment]
Very nice
