### ISSUE TITLE
Side panel doesn't show the pre-selected chapter as marked

### ISSUE THREAD

**Issue by jacobwod** [hajkmap/Hajk#1132]
DocumentHandler's side panel should start with the selected chapter pre-marked in the side panel:
![image](https://user-images.githubusercontent.com/110222/177933682-3fa820a9-2ca4-4009-8332-a6847751f93c.png)
_Correct behaviour in bae432abe9b452646d3ca02907d2dc7570172194_

---

Somewhere along the way, it seems that we lost this functionality. The same configuration files lead to this result on recent codebase:
![Skärmavbild 2022-07-08 kl  08 50 25](https://user-images.githubusercontent.com/110222/177933752-bf113299-7efa-423d-ac41-25d1714360fd.png)
_Marker is lacking in newer releases, e.g. f172c2fedd611d23da56b9e008eab73c2702fb11_

---

Quite [a lot has happened in the code between these two points](https://github.com/hajkmap/Hajk/compare/bae432abe9b452646d3ca02907d2dc7570172194...f172c2fedd611d23da56b9e008eab73c2702fb11), including the upgraded MUI version. Probably we just missed some detail.

**Comment by jacobwod** [comment]
So this is worrying: two pretty important props (`document` and `model`) are `null`:

![image](https://user-images.githubusercontent.com/110222/177947996-1a96e9db-53dd-4871-b79c-423469d9be92.png)

**Comment by Hallbergs** [comment]
Ugh. Probably some timing issue related to the react 18 upgrade. Let's look into it.
