### ISSUE TITLE
Infoclick: Be able to use x,y and zoom as params.

### ISSUE THREAD

**Issue by jesade-vbg** [hajkmap/Hajk#1145]
We need the possibility to access and use  {x}, {y} and {zoom} in infoclick templates to create links etc containing these.

Similar to: https://github.com/hajkmap/Hajk/issues/1076#issue-1225284701

Maybe group these as {click:param}

```
{click:x}
{click:y}
{click:zoom}
```

Edit:
I've also added the possibility to convert the coordinates to another projection.
Example: 
`{click:x|toProjection('x', 'click:x', 'click:y','EPSG:4326', 4)}`
this converts x to EPSG:4326 (used by google etc)
`{click:y|toProjection('y', 'click:x', 'click:y','EPSG:4326', 4)}`
this converts y to EPSG:4326 (used by google etc)
So now you should be able to create links to a wide variety of map services.

**Comment by jacobwod** [comment]
@jesade-vbg  Can you tag and mark as done please?

**Comment by jesade-vbg** [comment]
Is this done? Have I missed something?

**Comment by jacobwod** [comment]
I thought it was completed in 3b565d885bf331d1990e1f38ba1159518040d1cb, but perhaps I mixed it up with something else? 😄

**Comment by jesade-vbg** [comment]
I have a suggestion, to make AppModel a singleton. The AppModel is passed around in alot of places in the code. As there is only one AppModel instance that coders want to access, why not make it a singleton?

Whats your opinion?

Check this commit:
https://github.com/hajkmap/Hajk/commit/e35b69d43008923d1b38cb942279eff857d55972

**Comment by jacobwod** [comment]
Interesting! Perhaps we can talk about this some day this week?

**Comment by jesade-vbg** [comment]
![image](https://user-images.githubusercontent.com/73874338/188834274-5f8c4e95-31ce-4d87-9cfe-13a89c6ea964.png)
AppModel and coordinate transforms seems trustworthy after refactoring. Transforms tested against GMaps and GStreetView.
