### ISSUE TITLE
Infoclick: new formatting method (MultiplyBy)

### ISSUE THREAD

**Issue by jesade-vbg** [hajkmap/Hajk#1150]
New formating method is needed.

**multiplyBy**

Use case: 
We have a value in meters. 0.08 meters.
But we want it in centimeters.

with value `0.08`
`{value|multiplyBy(100)}`
you would get `8`..............

Simple but useful.

**Comment by jacobwod** [comment]
Don't forget to a) tag this issue (#1150) with the closed keyword in your commit message and b) set the milestone to 3.11 (or whatever the current will be when you close).

Otherwise, good addition!
