### ISSUE TITLE
Print: add an option to append a margin

### ISSUE THREAD

**Issue by OlofSvahnVbg** [hajkmap/Hajk#1174]
User has asked to increase the marginals in the pdf-print function. Reason being; the icons and text now overlaps the map image, which renders them harder to discern. Marginals should be increased to fit the icons and text, so that they do not interfere with the map area:

This should be an option that can be turned on/off.

![PDF with upper and lower margins](https://user-images.githubusercontent.com/111860819/190161415-2a670cbe-0455-4126-9e15-ab31feaa158c.png)

**Comment by Hallbergs** [comment]
Sounds good!

**Comment by OlofSvahnVbg** [comment]
New print marginal styling:
![image](https://user-images.githubusercontent.com/111860819/191262152-7a621eca-c097-4c93-bb5d-7f52f7dcaa25.png)

**Comment by OlofSvahnVbg** [comment]
Preview box in map view scales accordingly.
![image](https://user-images.githubusercontent.com/111860819/191262381-4ad6eed4-caa5-40d0-8faf-9b9bc102682e.png)

**Comment by OlofSvahnVbg** [comment]
Added choice for text and icons in margins
![image](https://user-images.githubusercontent.com/111860819/191422865-a3ec20ae-49cc-4b60-883f-576d0ebf91ab.png)
![image](https://user-images.githubusercontent.com/111860819/191422940-36ba3f7c-5b6b-4bc8-bfc0-d6f03b931545.png)
