### ISSUE TITLE
QGIS Server: Single layer in group bug

### ISSUE THREAD

**Issue by WCarlsson** [hajkmap/Hajk#1182]
**Describe the bug**
When using a QGIS Server WMS-source served with a single layer in a group in the QGIS-project Hajk crashes when trying to set up a layer with the WMS-source.

**To Reproduce**

1. Create a QGIS project with a single layer in a group and serve with QGIS Server.
2. Try to add the WMS to Hajk
3. Notice how Hajk crashes

**Expected behavior**
Hajk should handle groups with a single layer from QGIS. Groups with 0 or 2+ layers work fine.

**Screenshots**
Set up in QGIS Desktop
![image](https://user-images.githubusercontent.com/38069156/191431053-61898a10-a7db-44fd-8062-95c9cffdd768.png)

Snippet of error when Hajk  crashes 
![image](https://user-images.githubusercontent.com/38069156/191431503-5fcafaf7-9e97-4099-b37a-6f31843ff867.png)

- Version Hajk 3.10

**Comment by jacobwod** [comment]
Can you please share if/where this layer is available publicly? You can PM me in case you don't want to publish your server details here.

**Comment by jacobwod** [comment]
Thanks for the info. I tried and got a crash already in Admin. **This is an Admin bug, right?**

**Comment by jacobwod** [comment]
Hmm…
![image](https://user-images.githubusercontent.com/110222/191914745-1d25656d-1251-4243-b035-b429d1113529.png)

**Comment by jacobwod** [comment]
OK, I can get pass the previous error by doing an `isArray` check. But there's another problem coming up, as QGIS Server tricks Admin to think that the last entry in the list below is a group (as it identifies itself as one), although it isn't. We'll need to investigate.

![Skärmavbild 2022-09-23 kl  10 30 22](https://user-images.githubusercontent.com/110222/191921335-5aeff9d7-941f-42ee-9d7a-2e1ee133ce83.png)

**Comment by jacobwod** [comment]
See fix/1182-single-layer-in-group-qgis-server.

**Comment by WCarlsson** [comment]
OneLayerGroup is a group that contains a layer called Original_layer so it is correct to call it a group although it is missing the content of the group in the list.
This is the setup in QGIS Desktop
![image](https://user-images.githubusercontent.com/38069156/191928773-85ff9d97-4a59-4acf-b7b1-033d9b570bd1.png)

**Comment by jacobwod** [comment]
That's correct. The problem is that QGIS Server's WMS sends different responses depending on the amount of layers in group (which is strange - a group should be a group). If there are more 2 or more items, the group is an Array of layers. If there's one item, the "group" is the layer item, directly. 

I'm not sure what the WMS specification says about it, but it's a clear case where the different WMS services handle things differently.

**Comment by jacobwod** [comment]
Hi @WCarlsson, I've just pushed some fixes to https://github.com/hajkmap/Hajk/tree/fix/1182-single-layer-in-group-qgis-server. If you can, please check out that branch and build Admin (just Admin is enough, as there are not changes in the other directories) and see if it solves the problem. I've verified that the crash is prevented and that you can save additional fieds (such as infobox definition), but it's best if you test for yourself. 

![Skärmavbild 2022-09-26 kl  10 13 19](https://user-images.githubusercontent.com/110222/192226633-ea94e873-a011-49cd-ac51-ab041035a9bb.png)

**Comment by WCarlsson** [comment]
@jacobwod it works fine for me aswell.
Awesome work as always!
