### ISSUE TITLE
Positioning bug using Coordinates plugin and Location Plugin

### ISSUE THREAD

**Issue by linusfj** [hajkmap/Hajk#1195]
**Describe the bug**
Using the positioning features of the Coordinates plugin and the Location plugin results in an issue that either delays or prevents the marker from appearing on the map.

**To Reproduce**

1. Toggle the Location plugin to activate it.
2. Open the Coordinates plugin.
3. Click on the button "Show my position".
4. While the Location plugin is active, the marker won't appear on the map.

**Expected behavior**
It should be possible to use the positioning feature simultaneously in both plugins.

**Comment by jacobwod** [comment]
Could not reproduce in a525f37570fbaa1e87dcd8d01cbcf76b953655fd. 
![Skärmavbild 2022-09-29 kl  13 22 42](https://user-images.githubusercontent.com/110222/193018841-e52d6b69-84bd-4413-ba45-395f6efc95fe.png)

**Comment by jacobwod** [comment]
And a video showing the exact steps as you describe.

https://user-images.githubusercontent.com/110222/193019240-ec71e2c6-78cc-4dfc-aa34-ac054ae38470.mov

**Comment by linusfj** [comment]
The error occurs when you click the "Show my position" button in the Coordinates plugin that navigates to and highlight your current position in the map.
