### ISSUE TITLE
Collector - Enabling WKT functionality fails

### ISSUE THREAD

**Issue by jool-kba** [hajkmap/Hajk#1212]
Enabling WKT functionality results in errors when map is loading. 

Version 3.10

**Comment by jacobwod** [comment]
Please add more details.

**Comment by jacobwod** [comment]
While we await more details: is this the plugin you are talking about?

![Skärmavbild 2022-10-19 kl  14 02 53](https://user-images.githubusercontent.com/110222/196685396-f2740cad-2c06-482f-a655-55c65b61cf16.png)

**Comment by jool-kba** [comment]
I see. I was just about to post some info about it.
