### ISSUE TITLE
Making the documenthandler drawerButtonIcon configurable

### ISSUE THREAD

**Issue by lina-sbk-gbg** [hajkmap/Hajk#1219]
We want to change the icon of the button used to open Dokumenthanterare 2.0.

We suggest making the documenthandler drawerButtonIcon configurable in admin. (in the same way that drawerTitle and drawerButtonTitle are already configurable)
The default icon is suggested to be MenuBook.

**Comment by jacobwod** [comment]
Related to #1220. Move to #650?

**Comment by Hallbergs** [comment]
> Related to #1220. Move to #650?

I agree. Both are good candidates to move to the admin-rebuild.

**Comment by linusfj** [comment]
Instead of importing all icons from the Material UI library to let the user choose any icon, I've added options with two icons to choose from. The options are configurable via a drop-down menu in _admin_.

**Comment by Hallbergs** [comment]
Hmm. But we're already providing support for any MUI icon in the DocumentHandler? (In the menu-items). Wouldn't that solution work here as well without importing all icons.

**Comment by linusfj** [comment]
Yes, that would work. I've added support to choose any Material UI icon by specifying the name of the icon in _admin_.
