### ISSUE TITLE
Anchor: generated link enables all sublayers even if only a subset was selected initially

### ISSUE THREAD

**Issue by jacobwod** [hajkmap/Hajk#1226]
**Describe the bug**
The Anchor plugin (which really should be renamed to _Share_ by the way) has trouble working with Hajk's group layers.

Even if a group layer is only partly selected, the Anchor plugin's will generate a URL that will lead to all sublayers being active:

https://user-images.githubusercontent.com/110222/197768172-2bef8735-6a8d-41f8-99d6-e0e64586f4a2.mov

**Comment by Hallbergs** [comment]
We're dealing with the same issue! Would be very nice if we got it sorted. Maybe we can have a look at it together?

**Comment by jesade-vbg** [comment]
Just mentioning this: https://github.com/hajkmap/Hajk/issues/677

**Comment by jacobwod** [comment]
Anybody started yet? 😉

**Comment by jacobwod** [comment]
I mean this is really interesting - I recall I did something that should've worked at some point in time, see:
https://github.com/hajkmap/Hajk/blob/280ae8dffc4229a2ae55b90c156f828e08e6a626/new-client/src/plugins/Anchor/AnchorModel.js#L30-L41

Somehow, it's broken now though…

**Comment by jacobwod** [comment]
Oh nevermind, CQL has nothing to do with this. What we need to take into account is this:

<img width="371" alt="Skärmavbild 2022-11-17 kl  11 19 29" src="https://user-images.githubusercontent.com/110222/202420505-f06da80a-1e92-4c50-8b6f-6fdbbf623277.png">

**Comment by Hallbergs** [comment]
> Anybody started yet? 😉

Nope! Let me know if you start looking at it. I'll gladly help!

**Comment by jacobwod** [comment]
Some major progress: Anchor's link will now respect the visibility of sublayers! 

(Still have to fix LayerSwitcher though, which thinks that everything's visible, though it's not…)

https://user-images.githubusercontent.com/110222/202717402-73a486ec-49b3-48e5-ae1f-7ece4202659a.mov
