### ISSUE TITLE
Backend: Add an endpoint that verifies Hajk layers against their respective service

### ISSUE THREAD

**Issue by jacobwod** [hajkmap/Hajk#1227]
As a Hajk setup grows, it can easily consist of thousands of Hajk layers (layers defined in `layers.json`). Over time, it because impossible to keep track of each layer individually. 

The respective service (WMS, WFS, etc) can move the layer to another workspace, rename it or just become unavailable. **All these situations will lead to Hajk Client having problem when loading maps with layers that do not exist where they are expected.**

To ensure a high quality of services provided by Hajk, Backend could be extended with an endpoint that checks each layer's existence. The exact implementation will vary, but the main idea is to:
1. loop each of the defined layers
2. group them together depending on source 
3. ask each source for a list of available layers (usually `GetCapabilities`)
4. compare the response from source with what we have in `layers.json`
5. mark diff layers as missing and return with the response

**Comment by jacobwod** [comment]
I've committed a first implementation. 

I've already found some cases where we run into trouble. In this screenshot there are two layers (id 0 and 1) that have different names. But inside those layers there are more layers where names are seemingly duplicates (e.g. 2019 and 2020). 

I'm writing this as a note to check it out further and see how we can distinguish between them. Simple recursive algorithm can't be enough as the two 2019/2020 sublayers are different, despite having the same name. 

![image](https://user-images.githubusercontent.com/110222/199037054-97272bb9-25e7-4d81-9790-3c9c02d2d7c6.png)

**Comment by jacobwod** [comment]
Initial progress, with some promising results already.

![image](https://user-images.githubusercontent.com/110222/199254952-1f9f00ee-7149-4747-a674-ca6972bbf601.png)

**Comment by Hallbergs** [comment]
Very nice! ;)

**Comment by jacobwod** [comment]
There's a slight misfortune here: this feature requires Node 18, but updating to it might not be feasible in some situations (see #1245). Nonetheless, this feature is complete and done.
