### ISSUE TITLE
Add close button to Snackbar in Coordinates Plugin

### ISSUE THREAD

**Issue by linusfj** [hajkmap/Hajk#1231]
**Is your feature request related to a problem? Please describe.**
When minimizing the Coordinates Plugin on mobile devices, the window is hidden behind the Snackbar and it is difficult to maximize it.

**Describe the solution you'd like.**
Adding a close button to the Snackbar solves this problem by giving the user access to the maximize button again and without changing the placement of the Snackbar.

**Describe alternatives you've considered.**
Following the described solution could result in this change.

Before:
![image](https://user-images.githubusercontent.com/8030104/199992606-08ee0a74-1d84-4a04-839c-ebee0ccbab6d.png)

After:
![image](https://user-images.githubusercontent.com/8030104/199992278-90fa4e29-b0e3-4681-a552-ebff551bdcdb.png)

**Comment by Hallbergs** [comment]
Nice! The mobile ui is really in need of a redo. (I don't really like how the plugins are handled when minimized etc.). This sorts the problem for now!
