### ISSUE TITLE
Search: sort search sources alphabetically in search settings

### ISSUE THREAD

**Issue by jacobwod** [hajkmap/Hajk#1234]
This is not an example of good UX… 😉 
![Skärmavbild 2022-11-07 kl  15 01 43](https://user-images.githubusercontent.com/110222/200329367-c622b12e-f0ec-4af0-af2e-7eb16c926d32.png)

Alphabetical sort should make it easier to grasp.

**Comment by jacobwod** [comment]
The result:

![Skärmavbild 2022-11-07 kl  15 12 28](https://user-images.githubusercontent.com/110222/200331390-f9617d22-6879-47e5-9fae-d7abeadd2b8a.png)

**Comment by Hallbergs** [comment]
Been on my mind for ages... Fantastic that you got it done! 👍
