### ISSUE TITLE
New Measure tool - step 1

### ISSUE THREAD

**Issue by jesade-vbg** [hajkmap/Hajk#1243]
I think we should rewrite the measure tool (or probably create a completely new measure tool).
We should also rethink the UI, probably use buttons instead.

There are many other ideas regarding the measure tool in other github issues, but my thoughts is to do this in steps.

**So for step 1 the suggestion is (initial thoughts):**

- Rewrite to functional component
- Use new DrawModel functionality etc
- Use buttons for the different measurement types
- Keep the base functionality simple.

**I think simplicity is key to keeping this tool a success.**

_(When I say success, I base it on the usage statistics of the measure tool)_

Any thoughts?

**Comment by jacobwod** [comment]
I agree with all of the above. We should keep it simple with an absolute minimum of most-used features (which should be determinate by consultation with our users). 

There'll still be _Sketch_ for the more advanced use cases.

**Comment by Hallbergs** [comment]
I completely agree with everything above!

**Comment by jesade-vbg** [comment]
1.  I'm sitting thinking about the ui for the Measure tool. It currently looks like in the screensjot below, but I'm wondering if the buttons should be vertical instead like in the Sketch tool. But in that case the plugin would take more room than needed..... Does anybody have any input on the matter? UI-wise.

![image](https://user-images.githubusercontent.com/73874338/214566721-20add634-94b4-460e-a0b9-7caee7003f26.png)

2. Naming the plugins is kind of a headache. Currently its called Measure2, but some of us does not like versioning in the name. Any other suggestions?

**Comment by jacobwod** [comment]
1. It looks good to me. If we want to keep it simple we should remove the red "Rensa" button and allow the trash can button to just clear everything off the map (first show an alter asking user "Are you sure you want to remove all measurements?" of course!) In this case I see a really minimalistic UI and it looks good both horizontally and vertically. We could actually have both, using the Grid or Flexbox or whatever. One row if there's room - one column if there's no room for the row.
2. I took a look at synonyms to the verb "measure". Of those proposed, "meter" looks like the best option to me.
![Skärmavbild 2023-01-25 kl  14 28 39](https://user-images.githubusercontent.com/110222/214575588-7b162de2-691b-4ad0-b9cd-b0b394a81bf3.png)

**Comment by Hallbergs** [comment]
Looks good! Maybey "Measurer" could be an option?

**Comment by jesade-vbg** [comment]
Thanx for input. Regarding Jacobs #1. I think the addition to be able to remove a single measurement is necessary. If you have made alot of measurement and something is wrong you get kind of annoyed that you'll have to do everything again. I also made the hovered object become red if you use the single object delete. So should we keep the added "single delete" feature or remove it? I vote for keep :)

**Comment by jacobwod** [comment]
Sound good, keep it! 👍
