### ISSUE TITLE
Ensure smooth upgrade path to NodeJS 18+

### ISSUE THREAD

**Issue by jacobwod** [hajkmap/Hajk#1245]
There have been some security fixes in Node 17 which renders some OpenSSL certificates insecure. So far I've identified two problems that we can run into:
- building Admin UI fails with this error: `Error: error:0308010C:digital envelope routines::unsupported`
- starting Backend with ActiveDirectory active _and_ providing an LDAPS server _puls_ the necessary certificates can require renewed certificates (as OpenSSL 3.0 has tightened the requirements)

This looks as two separate problems. The first one will probably be fixed by bumping some dependencies in Admin. The other one may require providing new, more secure certificates when using LDAPS.

**Comment by jacobwod** [comment]
The above issue were in fact two separate. 

# Building Admin UI fails
The reason for this is that we're still on a very old `react-scripts` version. We have two options here: upgrade to v5 or add a legacy flag. As this Admin is already a legacy product and we're working on its successor, I won't put any effort into upgrading it this late. So a fix with legacy flag is coming up. 

# Certificates too weak
This must be fixed server-side: you (or someone who provided you with the certs) must use a stronger encryption algorithm. That'll fix the issue.

**Comment by Hallbergs** [comment]
Legacy flags in the admin UI feels like the correct path.
