### ISSUE TITLE
Filter `roundToDecimals` fails parsing string values

### ISSUE THREAD

**Issue by jacobwod** [hajkmap/Hajk#1282]
**Describe the bug**
This: `{GRAY_INDEX|roundToDecimals(2)}` will fail if `GRAY_INDEX` is a string (which it is if it comes from a XML/GML response - only JSON responses have valid JS types).

**The reason**
I think that this https://github.com/hajkmap/Hajk/blob/01feb29fe67b5b65958292e4e15b884ed7bab4b8/new-client/src/components/FeatureInfo/FeaturePropsFilters.js#L133

should be this:
```javascript
return parseFloat(value).toFixed(parseInt(numDecimals)).toLocaleString();
```

I.e. first parse `value`, then invoke `toFixed()`. Currently, we invoke `toFixed()` on a value that _might_ be a string. I don't think this was intended.

**Comment by jesade-vbg** [comment]
Actually I think it must be parsed to float again before toLocaleString, if you want toLocaleString to work.

```javascript
let value = "8.2342"; // can be string or number
let numDecimals = "2"; // can be string or number

parseFloat(parseFloat(value).toFixed(parseInt(numDecimals))).toLocaleString();
```

**Comment by jacobwod** [comment]
Or just use the `Number` construct? It has both [toFixed](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed) and [toLocaleString](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString) I'll leave it up to you. 😄
