### ISSUE TITLE
DocumentHandler: Wrong font size for unordered lists

### ISSUE THREAD

**Issue by jacobwod** [hajkmap/Hajk#1287]
This does not look good, the font in list items is larger than the normal text. Shouldn't be like that.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/110222/218412180-d3d32722-04f4-4c30-9f33-8e21e017ffc0.png)

I'm curious if anyone else noticed that? @lina-sbk-gbg perhaps?

**Comment by lina-sbk-gbg** [comment]
I checked now and it looks like the size is the same in both lists and normal text in our application.

![image](https://user-images.githubusercontent.com/23458086/218758518-de477632-487f-4b5f-b8ab-5d3b8fe70b3d.png)

**Comment by jacobwod** [comment]
@FredrikEkstrom79 Can you check for similar lists on our older (deployed) setups? If it looks fine there too, we might have introduced a bug somewhere along the way.

**Comment by FredrikEkstrom79** [comment]
I have check several of our older installations and it looks good there, it must have been something hidden that made the text bigger. The text was copied from MS Word so it's possible that som formating from there was left. I think you can close this issue.

**Comment by jacobwod** [comment]
Interesting find, doesn't look as an issue we can fix on our side - we should keep the users informed on the implications on pasting formatted text though. Closing.
