### ISSUE TITLE
Min/max zoom level - Snackbar not displayed for layer groups when switched on outside of zoom level

### ISSUE THREAD

**Issue by elizabethgbg** [hajkmap/Hajk#1291]
**Bug deskription for group layers**
When you zoom outside of a layers specified zoom level and switch on a normal layer, a snack bar will appear.
When you zoom outside of a layers specified zoom level and switch on a group layer, no snack bar will appear.

**Expected behavior and wishes for group layers**
That the indicators for the layer being turned on outside the specified zoom level, work the same on group layers as for single layers. So that the selected setting for the snackbar is displayed for both group and single layers.

**NOTE**
There are settings in admin for the snackbar - the setting determines if the snackar only should be displayed when the layer is switched on outside the specified zoom lavel, or every time you zoom outside the zoom level when the layer is switched on. Group layers should work like single layers both when this function is activated and deactivated.

This is a clarification of the bugs described in #810 
Related issues: #1290, #1299, #1300.

**Comment by jacobwod** [comment]
Hi @linusfj, I know that #1304 is supposed to fix this, but I've found another small bug: the snackbar shows up as expected when toggling the affected layer directly. But if you toggle a group (just normal group), the layers inside do get the right color but don't show the snackbar notice. See video:

https://github.com/hajkmap/Hajk/assets/110222/160d8e79-e962-40fd-9f98-ea5216803e7c

Can you reproduce?
