### ISSUE TITLE
Overhaul of the OpenAPI specifications

### ISSUE THREAD

**Issue by jacobwod** [hajkmap/Hajk#1309]
# Documentation
- Two new keys have been added to `.env`. None of them is needed, you can safely use your current `.env` and let the Backend use its defaults.
- Keep in mind that enabling only V2 of the API requires fixes in Admin UI which are not there currently. One example is that the `GET /mapconfig/delete/{map}` is not implemented in V2 and replaced by `DELETE  /mapconfig/{map}`. 
- This means that you'll need both versions of the API running side-by-side for now. This is also the default configuration.

Check out the PR #1318 for a list of changes, including [the new keys in `.env`](https://github.com/hajkmap/Hajk/pull/1318/files#diff-f436188f94de2f059c281191e6ee6b0a50be320ab5c8eb11d2f22454dd8ee560). 

# Original issue
During development of #1210 we all agreed that the specifications that lay the foundation of our API implementations need an overhaul. 

This issue is ment to document the changes. Related commits (and possible PRs) should link this issue.

**Comment by jacobwod** [comment]
As I mentioned in my last commit, I had a feeling that this will need some more work. Now I see one place that needs re-thinking.

`server.js`, that is common for both API versions imports some controllers. Currently they come from V1 but we must find another way:
![Skärmavbild 2023-03-30 kl  12 37 55](https://user-images.githubusercontent.com/110222/228810844-d6b3e6e0-30e5-46b8-af1f-580529b72363.png)

**Comment by Hallbergs** [comment]
I agree that the exposed static dirs should be available directly on `/`, and not under versioned urls.

Maybe some functionality could be seen as some kind of "core-api"? These could be set to always use the last stable services (v2 in this case). Another solution could be to see the exposing of static folders as a "one-of" and have a separate setting for that middleware in `.env`, something like `STATIC_EXPOSER_VERSION = V1 | V2 | LATEST`

**Comment by jacobwod** [comment]
Good idea, that's what I ended up with as of 4066ce3c9b7e6b5b9941668411d355f26c786c2f. Pretty much done now I think.
