### ISSUE TITLE
Edit Plugin - Label is not used for attributes with boolean data type

### ISSUE THREAD

**Issue by maan002** [hajkmap/Hajk#1317]
**Describe the bug**
The label specified in Admin is not used for attributes with boolean data type in the Edit Plugin.

**Expected behavior**
I would like the label specified in Admin to be used in the client.
Also, it would be nice if the attributes were left justified instead of centered in the dialog.

**Screenshots**
Config page in Admin:

![Admin](https://user-images.githubusercontent.com/22821937/231104478-41bc8089-973b-48b5-9f49-4699b2680bbc.PNG)

Result in the Edit Plugin on the Client (the attribute name is used, not the label "Livsmedel")

![Client](https://user-images.githubusercontent.com/22821937/231104717-952c03af-a01c-4921-b413-222b4da55f1c.PNG)

**Comment by jesade-vbg** [comment]
Tested and working in #1384. Alias is showing as expected.
![image](https://github.com/hajkmap/Hajk/assets/73874338/c23110f2-0b2e-4c54-a7b5-d0d835383fb7)
