### ISSUE TITLE
Zoom Control: Not possible to disable zoom animation due to ignored zoomDuration

### ISSUE THREAD

**Issue by sweco-semara** [hajkmap/Hajk#1334]
**Describe the bug**
The zoomDuration value set in admin is ignored by the Zoom Control, currently making it impossible to disable zoom animation in Hajk. Zoom animation on slow loading background layer gives the Hajk map instance a very "rubberband"-like experience when using the zoom control, better to turn the animation off in those cases and make the map load more snappy (but slow).

Everything seems prepared in Hajk with respect to admin setting, persisted value in backend and [loading of the zoomDuration value in AppModel](https://github.com/hajkmap/Hajk/blob/master/new-client/src/models/AppModel.js#L319).

Culprit seems to be [a hard-coded 200ms duration in ZoomControl](https://github.com/hajkmap/Hajk/blob/master/new-client/src/controls/Zoom.js#L29).

**To Reproduce**

1. Go to admin, map settings
2. Enter 0 as zoom duration value
3. Load map instance
4. Use zoom control to zoom in or out
5. Actual: 200ms zoom animation always

**Expected behavior**
Expect a zoomDuration value of <=0 to disable the OpenLayers zoom animation.

**Screenshots**

**Desktop**

- OS: Windows 10
- Browser Chrome
- Version 112.0.5615.138

**Smartphone (please complete the following information):**

(Not tested on mobile, due to hardcoded zoom control 200ms behaviour is expected to be the same.)

**Comment by jacobwod** [comment]
Thank you for this bug description, good find!

As you already found out, it looks as I missed to activate the last step. (The `TODO` comment is not enough… 😉 )

This should be an easy to fix and I'll see if I can get it done next week, unless someone else beats me. 

One minor addition is that we must pass the settings value to the Zoom control (looks as it only gets the `Map` currently).

https://github.com/hajkmap/Hajk/blob/a745e12be217a39bdc2a39c6fe00c26081058a89/new-client/src/components/App.js#L963
