### ISSUE TITLE
Measurer: Perpendicular Measurements

### ISSUE THREAD

**Issue by jesade-vbg** [hajkmap/Hajk#1361]
It would be great to be able to easily make perpendicular measurements using 90 degree snapping.
Many people have asked for it.
It is probably especially useful for the "building permit people".

I've made a working prototype (a little bit buggy though), but it works. (Edit: Not that buggy after last push)

See video

https://github.com/hajkmap/Hajk/assets/73874338/af56229f-27c4-4fc6-a778-3f725d012686

**Comment by jesade-vbg** [comment]
WIP.
If you're testing, make sure you have some buildings or something to snap to :) 
https://github.com/hajkmap/Hajk/tree/feature/1361-perpendicular-measurements

**Comment by jacobwod** [comment]
Very cool! 👍

**Comment by Hallbergs** [comment]
Oh wow! Very nice!
