### ISSUE TITLE
Proposal: remove unused keys from `appConfig.json`

### ISSUE THREAD

**Issue by jacobwod** [hajkmap/Hajk#1369]
I think we have at least two candidates.

### `appName`
I can't see where it's used.

### `version`
Might seem like a good idea, but when you think about it, the version in `package.json`  (of `new-client`, in this case, because that's where `appConfig.json` belongs) is enough. 

This `version` from `appConfig.json` isn't read anywhere in the code (AFAICS). 

Furthermore, the version specified in `package.json` is the one that becomes visible to the user (part of `index.html` where it's read from `%REACT_APP_VERSION%`, which in its turn is set in `.env`:
```sh
# .env
REACT_APP_VERSION=$npm_package_version
```

@hajkmap/dev Please expand the list if you find more keys to be removed. 

**I propose we remove it in `develop` before 3.13.**

**Comment by jesade-vbg** [comment]
please do :)
