### ISSUE TITLE
Add possibility to change icon background in feature list

### ISSUE THREAD

**Issue by FredrikEkstrom79** [hajkmap/Hajk#1385]
# Updated: Documentation
In order for this to work, the feature must contain a property named **`_hajkiconbgcolor`**.
Allowed values for `_hajkiconbgcolor` are any valid MUI color values, as this goes straight into the `sx` prop. Basically it's:
- all the CSS literal values (e.g. `red`)
- other CSS values in HEX (e.g. `#ff0000`)
- values that refer to the MUI palette (e.g. `background.paper`)

See [MUI's documentation](https://mui.com/system/getting-started/the-sx-prop/) for details.

/ @jacobwod 

---

# Original issue
If the background of the icons can be set from a column from the current layer or directly from with in admin it would be much easier to find the right feature when multiple features is returned from search or infoclick.

![image](https://github.com/hajkmap/Hajk/assets/50202826/a4cb38cb-26f4-4fb8-88de-cfc13eeabe8a)

Like this
![image](https://github.com/hajkmap/Hajk/assets/50202826/24105831-ff58-4f61-8227-1a947094e064)

**Comment by jacobwod** [comment]
Coming up. See documentation in the edited original post.
