### ISSUE TITLE
Invalid plugin configuration in backend example configs

### ISSUE THREAD

**Issue by sweco-semara** [hajkmap/Hajk#1391]
Hajk backend map config examples contains an invalid plugin configuration. Specifically "bookmark" plugin, which does not exist.

**To Reproduce**

1. Use either .NET or NodeJS backend-based config with `backend/mapservice/App_Data/map_1.json` or `new-client/public/simpleMapConfig.json` as base
2. Open browser console
3. (Re-)load the map
4. Check browser console

**Expected behavior**
Quiet/empty console on using Hajk-supplied config examples. (_Currently also expects an empty warning, see also #1390, but the point in this bug report is that a specific error report is not expected after reproducing per above..._)

**Actual**
Console warning:
> App.js:396 The map configuration contains unavailable plugins: bookmark. Please check your map config and buildConfig.json.  

**Root Cause Analysis**
I think this might be a Hajk 2 leftover in the demo/example config? The bookmarks plugin in Hajk 3 seems to be introduced in #655 and from what I can see it has always been named with a plural "s"?

**Suggested Solution**
Simplest fix is probably to just rename "bookmark" to "boomarks" in both of the following example configs?
1. .NET backend sample config map_1.json [L437](https://github.com/hajkmap/Hajk/blob/master/backend/mapservice/App_Data/map_1.json#L437) in current master
1. NodeJS backend sample config map_1.json [L440](https://github.com/hajkmap/Hajk/blob/master/new-backend/App_Data/map_1.json#L440) in current master

(Not backwards compatible as a new plugin would then start showing in the demos, so another way to get rid of the warning is to just remove the whole plugin/tool config for "bookmark" from both files... But I think Hajk does not need to maintain a status quo for demo configs?)

**Comment by jacobwod** [comment]
Hi @sweco-semara, 

I absolutely agree. In fact, I've fixed it (outside of upstream though, so you had almost no chance finding it) in b10b50afdbebefa4161c6aed995e4413c413b00a and 89cdefa095dc94ba4f5befc66d3e1249bd3dd5c6. 

The first commit ensures that `preset` is forced into the array we check against. `preset` is a special case as it can exist in the map config object but can never be a part of the `activeTools` object and will thus always show up as a warning without this. 

The second commit ensures that we don't print an empty message.

Feel free to implement your solution though, as mine was never part of the main branch. Thanks.
