### ISSUE TITLE
Keep page state when restore/restart or using navigation buttons

### ISSUE THREAD

**Issue by kboortz** [hajkmap/Hajk#1398]
It is easy to accidentally leave the Hajk page or when having issues beforced to restart the browser or computer. Restoring the window/tab/session, Eniro and Google Maps restore the page to where you were. Hajk doesn't, and you have to redo the search, zoom level etc. Having many Hajk windows open makes this very time consuming.

When restoring a session, restoring a windows, restoring a tab, or using the back/forward button, I suggest you add the functionality so that the Hajk page reappear as it was before.

Note that there are other map system that lack this functionality. As an example, Länsstyrelsen "Informationskarta Örebro län" can handle the back/forward button, but if the window/tab is closed, restoring it will give you the start page.

**Comment by Hallbergs** [comment]
Take a look at #1252 

I think that the "App state in hash" (see more in the description of #1252 ) is a step in the right direction.

**Comment by jacobwod** [comment]
I agree with @Hallbergs. Looking at the description you provide, it sounds like #1252 is just what you're asking for. See for yourself at https://karta.halmstad.se.
