### ISSUE TITLE
Autofocus the Search field when app loads

### ISSUE THREAD

**Issue by jacobwod** [hajkmap/Hajk#1424]
We've heard from a number of users that the most common action they perform after opening Hajk is to search. They've asked us if it'd be possible to have the search field autofocused when Hajk loads.

I see that there's a need for such a solution, but I think this should be an option, configurable on a per-map-basis.

**Comment by jesade-vbg** [comment]
Maybe even a user setting in search settings? I actually don't think this should be forced in map config.
![image](https://github.com/hajkmap/Hajk/assets/73874338/de498c01-c743-4e7b-a809-5100b1636809)

**Comment by Hallbergs** [comment]
Nice addition! Controlling it on a per-user-basis would be nice as well!
