### ISSUE TITLE
Infoklick - filter 'equals' returns wrong argument

### ISSUE THREAD

**Issue by maan002** [hajkmap/Hajk#1427]
**Describe the bug**
In Infoklick, using the filter 'equals' with an attribute of type boolean seems to flip the result. 

**To Reproduce**
value = true
{value|equals(true, 'yes', 'no')}
Resultat: no

**Expected behavior**
'equals' should return 'yes' in the example above.

**Comment by jacobwod** [comment]
@jesade-vbg is correct. I'm not even sure if results from the WMS/WFS are always type-specific (I think only XML and GeoJSON responses are). Furthermore, they're being thrown into a `string` using Markdown (or HTML), so you'd end up with a `string` value anyway. So just compare strings, as @jesade-vbg suggests.
