### ISSUE TITLE
KIR plugin - "Exportera" does not use AD-settings

### ISSUE THREAD

**Issue by maan002** [hajkmap/Hajk#1433]
**Describe the bug**
All users can see the choices in the "Exportera" tab and press "Skapa Boendeförteckning" even if you configure that users must have a specific AD group to be able to export.

**Expected behavior**
Either the export tab should be disabled or the contents of the tab should be disabled.
A message should be displayed as to why the tab or content is disabled.

**Comment by jesade-vbg** [comment]
I dont think this i a bug, it's just unused visibleForGroups settings left in config. Read comment in PR.

**Comment by jesade-vbg** [comment]
Backend does not remove/filter at that nested level.
![image](https://github.com/hajkmap/Hajk/assets/73874338/2fd6d355-7249-4043-a078-9b0a80cb13e5)

**Comment by jesade-vbg** [comment]
My previous comments is related to the fact that I was testing with wrong backend and nodejs-backed lacks this functionality.
This will be adressed in #1438.

The sollution @maan002 presented in PR is working and has been merged.
