### ISSUE TITLE
Plugin: Fånga koordinat

### ISSUE THREAD

**Issue by erikedmark** [hajkmap/Hajk#144]
Fånga koordinat

**Comment by jacobwod** [comment]
**Önskemål**
1. Visa koordinat med **tre decimaler** (ha gärna antal decimaler som en inställning för verktyget)
1. **"Krysset" döljs av fingret på touch-enheter** i Hajk2, vilket gör det i princip oanvändbart. Kan lösas på lite olika sätt, exempelvis ett större kryss, eller att man även kan dra i kanterna på krysset. 
1. **Snappa** mot objekt som är synliga i kartan.

**Comment by jacobwod** [comment]
@sbk-linus I'm not sure if your done with this plugin or not, but I notice that it doesn't show the expected values. Instead I get this:
![bild](https://user-images.githubusercontent.com/110222/66457909-bd524400-ea71-11e9-9031-febbd7bffbd2.png)

**Comment by jacobwod** [comment]
For reference, users would appreciate if the new plugin could – at some point – have similar functionality to what was available in Hajk1. Here's a screenshot:
![Unknown](https://user-images.githubusercontent.com/110222/66475423-96a50500-ea93-11e9-8d35-c2ab14ca23dc.png)

**Comment by jacobwod** [comment]
Referenced remaining feature requests in #311, closing this.
