### ISSUE TITLE
Plugin: Utskrift

### ISSUE THREAD

**Issue by erikedmark** [hajkmap/Hajk#147]
Utskrift

**Comment by jacobwod** [comment]
# Proposal: Legend visible in print 
_NB: This proposal was added after `external-order:2018-12`_ and is not part of the original order.

When user prints the map, it should be possible to control whether the legend for active layers is visible or not. With legend visible the result could be something like this:
![image](https://user-images.githubusercontent.com/110222/48605496-3ab62700-e97d-11e8-8031-49cdc005025e.png)
