### ISSUE TITLE
Plugin: Skapa buffertzon

### ISSUE THREAD

**Issue by erikedmark** [hajkmap/Hajk#148]
Skapa buffertzon

**Comment by jacobwod** [comment]
Already done?

**Comment by jacobwod** [comment]
@FatemeHosseini Can you check this?

**Comment by jacobwod** [comment]
Seems to build fine and works well on Chrome/FF. **User has to select an object that already exists, so it's not possible to draw something (with the Draw plugin) and then buffer around it.** But I'm not sure whether it is intended to work so or not. Anyway, closing this for now. Additional changes (improvements) should go to another issue.

**Comment by jacobwod** [comment]
Buffer now works on objects from Draw plugin too, as of e8e097c0. Thanks for pointing out, @FatemeHosseini.
