### ISSUE TITLE
QrCode implementation in Print/Anchor

### ISSUE THREAD

**Issue by OlofSvahn** [hajkmap/Hajk#1482]
So as we all now, qr codes are cool, and therefore we should have them in hajk. Specifically in Print and Anchor (Utskrift and Dela).

I've already tested an implementation using the `enableAppStateInHash` and it seems to work fine. 

Qr codes can be implemented in both print:

![image](https://github.com/hajkmap/Hajk/assets/74307205/98743059-eff3-45f8-baa0-ba481ed0f7bf)
![image](https://github.com/hajkmap/Hajk/assets/74307205/1f051623-dc6a-473c-981f-27a5de6622da)

And in Anchor:

![image](https://github.com/hajkmap/Hajk/assets/74307205/4116d948-e6da-45fd-bd99-06dc635bc168)

And we should probably only allow qr code generation if  `enableAppStateInHash` is enabled. Question is, what do we show if  `enableAppStateInHash` is false? Nothing, or maybe inactive buttons? What do you think?

**Comment by jesade-vbg** [comment]
Really nice. Especially in the Share function!

**Comment by Hallbergs** [comment]
Cool!

**Comment by jesade-vbg** [comment]
Would be great if you could post new screenshots after your changes in Anchor. :)

**Comment by OlofSvahnVbg** [comment]
Fuller image:

![image](https://github.com/hajkmap/Hajk/assets/111860819/39f25fa0-6c64-4c35-a8d5-d0c06a82154b)

**Comment by OlofSvahnVbg** [comment]
And ignore the incorrect tooltip
