### ISSUE TITLE
Plugin: Search

### ISSUE THREAD

**Issue by erikedmark** [hajkmap/Hajk#150]
Sök

**Comment by jacobwod** [comment]
# Proposal 1: make it possible to configure sorting of search results
## Problem description
There are situations in which it should be possible to configure on which column search results are sorted, and whether ascending or descending, but we shouldn't be forced to display that given column. Say there's an "added date" column, and we want the search results to be returned in the order as they were added, and also put the latest results on top of the list. Today we can sort by that column only if it is displayed as first in the results. There is also no way to tell search engine to reverse the sorting order.

## Proposed solution
It should be configurable in admin GUI, where we have an extra input field, let's call it $SEARCH_ORDER. If $SEARCH_ORDER is not empty, the parsed string that goes out to WMS should add something like `ORDER BY $SEARCH_ORDER`. This will require admins to write correct values to $SEARCH_ORDER, but given that its value is `date_added, public_name DESC`, we would in the end get something like  `ORDER BY date_added, public_name DESC`and hence solve the problem.

**Comment by jacobwod** [comment]
# Proposal 2: Give user an option to turn wildcard search on/off
## Problem description
If users searches for `HALMSTAD 2:4`, the returned result may look something like this:
```
HALMSTAD 2:4
HALMSTAD 2:40
HALMSTAD 2:41
HALMSTAD 2:44
```
The reason is that we assume users wants to do a wildcard search, so the query that is sent looks something like `<ogc:Literal>HALMSTAD 2:4*</ogc:Literal>`. 

## Proposed solution
This can be solved in a number of ways, but the first one that comes to mind is **adding a checkbox next to the search box**. Checkbox's label could say something like "Enable wildcard search", and it's value would determine whether that `*` would be added to the search string or not. Unchecking the box would still make it possible for user to do wildcard searches, by manually adding `*` in their queries. But not adding it would give a finer control of what we actually search for.

**Comment by jacobwod** [comment]
> Another approach would be auto-completion in the search field so that found candidates drop down after three-four characters are typed. 
This one actually exists already and we'll keep it this way I guess.

**Comment by jacobwod** [comment]
# Proposal 3: Don't remove marking of found objects automatically
## Problem description
When users clicks a result the polygon/point is marked on the map. Now, when user changes tool, e.g. to turn on some more layers, the search mark will disappear. 

## Proposed solution
Don't destroy the vector layer that holds the marking when search plugin is deactivated. Let the user decide manually to clear the marking by e.g. a button in the search tool, or a floating button somewhere else in the GUI.

**Comment by jacobwod** [comment]
# Proposal 4: Allow marking of more than one found object at a time

## Problem description
When user preforms search a list of results is presented. That list can contain multiple items, e.g. a land property may return multiple shares of that property (e.g. HAGA 4:21>1, HAGA 4:21>2). There are cases where user wants to mark all of those results on the map. 

## Proposed solution
Allow marking several result items in results list. If an item is marked in the list, it should also be marked in the map, and vice versa. E.g. a tight coupling between the "selected" state of result list item and corresponding feature on the map should be implemented. Pseudo code example: 

`collectionOfMapFeatures[item.id].setSelected(item.state.selected)`

**Comment by sweco-seqtob** [comment]
I'd like som input how to move search plugin to the right in the application. Should we handle it as a widget or should we add another "column" above the widget column where we can render the search plugin? We want it floating and not in the appbar but to treat is as a widget might not be the right way, any suggestions? @erikedmark @jacobwod

**Comment by jacobwod** [comment]
@sweco-seqtob You're talking about the situation where we want to configure search as a "floating" input field, in the upper right corner of the map?

**Comment by jacobwod** [comment]
Perhaps the column which contains zoom buttons is a good alternative? Depends on how we want to put it (I haven't seen mockups for all possible solutions so it's hard to tell). As I see it there are two main ways of solving this:
a. on top of zoom buttons, in the very upper right corner
b. just left of zoom buttons, which means search won't be in the corner exactly

I think it's a good idea to do some quick mockups and compare how they look. If we then choose option a), the column with zoom buttons will do. If we pick b), it's probably better to place it in the "center" <div>. 
![image](https://user-images.githubusercontent.com/110222/59493882-3f4bab00-8e8c-11e9-84c8-198c2c2bb7a7.png)

Keep in mind that we'll need to handle mobile viewport sizes separatel.

**Comment by sweco-seqtob** [comment]
Yes we talked about having it floating above all widgets to the right but i think we will use the header for the moment. This should propably be discussed more thoroughly at a later time because it feels like we should not just squeeze it in.

**Comment by jacobwod** [comment]
If by the header, you mean AppBar, then certainly yes. The AppBar is the natural placeholder for a search field.

**Comment by sweco-seqtob** [comment]
Yes, i mean the AppBar. I will use the same searchbar for both center and the AppBar and if one dont want to use the spatial tools, they can be disabled from admin

**Comment by jacobwod** [comment]
I'm not expecting any of the proposals mentioned here to be implemented to 3.0. Moving issue to 3.1.

**Comment by sweco-sesqqq** [comment]
All proposed features above are implemented and pushed to master
