### ISSUE TITLE
Analytics: track click on links in Infoclick to see which files are being downloaded mostly 

### ISSUE THREAD

**Issue by jacobwod** [hajkmap/Hajk#1535]
Since we already have a built-in analytics solution (both Matomo and Plausible are supported at time being), it should be possible to fulfil this request my group has: we want to know if users are aware of the downloadable assets that we frequently link to in our infoclick dialogs. We could of course look into the web server's request log, but it has multiple cons, mostly it's not user-friendly at all for a typical Hajk administrator. 

Hence, adding a `linkClicked` event (or something like this) to Hajk would be really useful. The event should provide the URL (or some part of it), to make it possible to distinguish links. It's not yet decided how this should be implemented in detail, which parts should be hard-coded vs which should be Admin-settable. Should this be done automatically, or require some additional "trigger" in the layer's infoclick config? Do we need any specific Markdown syntax for this, some special CSS class on the links that should be tracked, etc?

Feel free to comment.

**Comment by jesade-vbg** [comment]
![image](https://github.com/hajkmap/Hajk/assets/73874338/a9786d7e-ae27-438b-85c9-30cf08e4338d)
It feels like some clicks like this might already be tracked automatically in Matomo? Atleast some filetypes.
https://matomo.org/faq/new-to-piwik/faq_47/#:~:text=Matomo%20(Piwik)%20automatically%20track%20these,reports%20them%20under%20Behavior%20%3E%20Downloads.

**Comment by jacobwod** [comment]
Thanks. This got me to actually search Plausible's docs too and it seems they have something similar: https://plausible.io/docs/file-downloads-tracking. I'll look into it.

**Comment by jacobwod** [comment]
Okay, so the [official Plausible tracker](https://github.com/plausible/plausible-tracker) is lacking some of the more recent updates (such as support for file download tracking), as well as it has a bug in the auto-tracking of outbound links (the bug is rather irritating as it makes browser to ignore the `target` property, so everything opens in the same window as Hajk, which is a bit buggy for files that we want to open in separate tabs…). 

So, I decided to replace the official tracker with a new(er) fork: https://github.com/Barbapapazes/plausible-tracker, where this issues are fixed. There are some internal code changes on how the tracker is initialised, but the external config API remains the same.

**Comment by jacobwod** [comment]
See e744adbf8522308ced7b1a52ac01a10a382e1397 for code.
