### ISSUE TITLE
Plugin: Navigation

### ISSUE THREAD

**Issue by erikedmark** [hajkmap/Hajk#155]
Navigation

**Comment by jacobwod** [comment]
Jag tittade på det, men det ser ut som att du glömde checka in vissa komponenter. I `RouteView` har du `import BreadCrumbs from "./components/BreadCrumbs.js";`, men `BreadCrumbs.js` finns inte i din commit. Så jag kunde inte bygga applikationen alls. 

Noterar också att du la till jQuery som beroende. Vi går ifrån det i version 3 av Hajk, så vi får hitta andra sätt att lösa det på (har dock inte sett var du använder jQuery i det du checkade in, så det är kanske bara att ta bort). Men har inte kunnat testa som sagt.

**Comment by jacobwod** [comment]
@hitomin21 Eller kan det vara så att du använde dig av `BreadCrumbs.js` som tidigare kanske var fristående men nu ingår i pluginet `simple_layerswitcher`? I så fall får vi också tänka om, om det ska bli en generisk komponent eller hur vi gör, för vi kan inte ha ett plugins som är beroende av ett annat. Vi pratar om det när du är tillbaka.
