### ISSUE TITLE
Plugin: Quick link

### ISSUE THREAD

**Issue by jacobwod** [hajkmap/Hajk#159]
Quick link to given coordinate and zoom level, with a nice label.

Could be placed next to search, in App bar, and used to quickly zoom to a population center in the municipality.

**Comment by jacobwod** [comment]
Already done?

**Comment by jacobwod** [comment]
Similar functionality exists in Informative plugin.

**Comment by jacobwod** [comment]
Is this needed, in a similar way of how it works in Hajk1? Discuss please.

**Comment by FredrikEkstrom79** [comment]
It's a fast way to jump to a location if you don't know where exactly it is.

**Comment by jacobwod** [comment]
Sure, and it's also pretty simple to implement. A list of places (text labels), with each label corresponding to predefined x, y, and z value. 

**The question that remains is rather of visual implementation: how do we make it fit in nicely into current design?** One solution could be similar to how MapSwitcher works: a button on the map that reveals a drop down on click:

![image](https://user-images.githubusercontent.com/110222/68125554-25c9ff00-ff12-11e9-8f8e-7b4e3e3303e1.png)

Another way is using the Speed Dial component, but that will be **limited to 3-6 items**, which might be too little: https://material-ui.com/components/speed-dial/#persistent-action-tooltips.
