### ISSUE TITLE
Make only one request per infoclick event (GetFeatureInfo)

### ISSUE THREAD

**Issue by jacobwod** [hajkmap/Hajk#178]
In Hajk 2, when user clicks the map, several requests are made to the WFS service – one request for each visible, queryable layer. 

This could be highly optimized (reducing number of made requests to ONE, no matter how many layers are visible) by using the `QUERY_LAYERS` parameter and include all layers to be queried, as a comma separated list. 

See documentation for WMS `GetFeatureInfo` request on how to format layer list: https://docs.geoserver.org/stable/en/user/services/wms/reference.html#getfeatureinfo.

**Comment by maan002** [comment]
WMS layers may come from different servers and have different URL:s.

**Comment by jacobwod** [comment]
Stale, closing.
