### ISSUE TITLE
WMS 1.3.0 BBOX

### ISSUE THREAD

**Issue by sbk-linus** [hajkmap/Hajk#198]
WMS layers with version 1.3.0 has the wrong order of parameters for BBOX. The request is using the format previous WMS versions uses, i.e. [xmin, ymin, xmax, ymax].

BBOX format for 1.3.0 should be [ymin, xmin, ymax, xmax].

**Comment by jacobwod** [comment]
@erikedmark points out [this GeoServer issue](http://osgeo-org.1560.x6.nabble.com/JIRA-GEOS-8206-WMS-1-3-0-Axis-ordering-for-non-geographic-coordinate-systems-td5326207.html
 ) as a reason and suggests a solution where OL changes the `axisOrientation` of the View:
```
const projection = new Projection({
  code: 'EPSG:1234',
  axisOrientation: 'neu',
  […]
});
```
