### ISSUE TITLE
Vectorlayer is not using infobox in admin

### ISSUE THREAD

**Issue by sweco-seqtob** [hajkmap/Hajk#209]

**Comment by sweco-seqtob** [comment]
Should this be handled as WMS-layers, per "layer"?

**Comment by jacobwod** [comment]
Good question. But is that even possible with the current state of Vector's admin tool? It renders layers as radio buttons (as opposed to checkboxes in WMS), so there's currently no way to construct a vector layer group in Hajk:
![image](https://user-images.githubusercontent.com/110222/57848622-a288e580-77d9-11e9-8e06-a94abbfca368.png)

Opinions?

**Comment by sweco-sesqqq** [comment]
Fixed
