### ISSUE TITLE
Make it possible to override infobox on a per-mapconfig-basis

### ISSUE THREAD

**Issue by jacobwod** [hajkmap/Hajk#210]
Rencent changes in Hajk3's admin set the `infobox` property only on sublayers (even if only one layer is added). 

In Hajk2 there was an option in each map config to override the infobox in order to customize it for a given map. This setting sat `infobox` value "globally" on the layer (as opposed to sublayers). Therefore this option has been removed in Hajk3, as an override there would even override the sublayer-specific setting.

What needs to be done to achieve similar (but greatly improved) functionality in Hajk3 is to **add an option in map config to further customize `infobox` (as well as more fields, such as `title`) on a per-map-basis**.

[See here](https://github.com/hajkmap/Hajk/commit/400c71a248142c5daded170b336aef94bc90fa46#commitcomment-33562997) for further description.

**Comment by jacobwod** [comment]
I recall that I've fixed something similar to this issue in the recent weeks. **The custom title part is not done of course**, but overriding of infobox should work as of 7f93e3f6cfb09032520bf2efbd130d4ff6bdc875. Related/duplicate of #395, isn't it @FredrikEkstrom79, @victoraxbom ?

**Comment by victoraxbom** [comment]
@jacobwod Yes, this seems to be a duplicate. Is the part you implemented in 7f93e3f6cfb09032520bf2efbd130d4ff6bdc875 still depending on autentification to be active?

**Comment by jacobwod** [comment]
@victoraxbom: Not in `client`, but I'm unsure whether you need the AD flag in admin's `config.json` in order to see the `<input>` that let's you override infobox on each layer. Please verify if you can as I don't have access at the moment.
