### ISSUE TITLE
GetFeatureInfo on a subset of a group layer contains too many layers in QUERY_LAYERS parameter

### ISSUE THREAD

**Issue by jacobwod** [hajkmap/Hajk#211]
**Problem**
Steps to Reproduce:

1. Make sure you have a WMS layer in Hajk's admin that contains at least two other layers. 
1. Make sure both sublayers have `Infoclick: true`
1. Go to your map. Open LayerSwitcher, expand your group layer and some of the sublayers, _but not all_.
1. Try to click to make a GetFeatureInfo-request. The following error shows up in console: `Unsupported response type: application/vnd.ogc.se_xml`.

That error is a result of the response, which if viewed separately correctly shows the problem we have to deal with:
```
QUERY_LAYERS contains layers not cited in LAYERS. It should be a proper subset of those instead
```

**Fix**
We must query only visible layers. So in this request: 
```
/wms?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetFeatureInfo&FORMAT=image%2Fpng&TRANSPARENT=true&QUERY_LAYERS=tf%3Atf_zon_1_rod%2Ctf%3Atf_zon_2_bla%2Ctf%3Atf_zon_3_gul&LAYERS=tf%3Atf_zon_1_rod%2Ctf%3Atf_zon_2_bla&INFO_FORMAT=application%2Fjson&SRS=EPSG%3A3008&TILED=false&STYLES=%2C%2C&FEATURE_COUNT=100&X=67&Y=229&WIDTH=256&HEIGHT=256&BBOX=108435.7168%2C6283387.84184%2C115603.7168%2C6290555.84184
``` 
QUERY_LAYERS should be a limited to items that also exist in LAYERS.

**Comment by erikedmark** [comment]
When a sublayer is updated layer updates it´s LAYERS param, with the updateParams method. There is one issue in the openlayers implementation. If the LAYERS array is empty the layer will not update. To solve this a workaround is made by adding just one layer and the add the CQL_FILTER: "EXLUDE" property, this will hide the layer and still update it´s state.

So, in short. The layer.getSource().getParams()["LAYERS"] property will contain the visible layers, except if the layer.getSource().getParams()["CQL_FILTER"] is not null or undefined, then the layer has no visible layers, even if the layer.getSource().getParams()["LAYERS"] may contain a layer.

**Comment by jacobwod** [comment]
Implemented, but I'm afraid I didn't take care of the CQL_FILTER as I don't have those "breadcrumb" enabled on any of my setups. I think it will query just fine, but sure it's not right to query and display results for a layer that is temporarily hidden. Feel free to test and fix.
