### ISSUE TITLE
Don't show info icon on layers that don't have additional information

### ISSUE THREAD

**Issue by jacobwod** [hajkmap/Hajk#228]
Currently the icon is grayed out, but perhaps there's not reason to show it at all if a layer doesn't have any additional info?
![image](https://user-images.githubusercontent.com/110222/59745508-451f0300-9275-11e9-9a1b-f46103e986d6.png)

**Comment by FredrikEkstrom79** [comment]
They are still present even if they are hidden.
Instead of visibility:hidden it should be display:none so the don´t take up space from the caption when they don't need to.

**Comment by jacobwod** [comment]
True @FredrikEkstrom79 , I'm not sure why this issue was closed in the first place, @sbk-linus?

**Comment by jacobwod** [comment]
Still not good for LayerGroupItems:
![bild](https://user-images.githubusercontent.com/110222/69638863-d3d15080-105b-11ea-80a0-36ffac0d2a2c.png)
