### ISSUE TITLE
Minimize/maximize behavior on Window

### ISSUE THREAD

**Issue by jacobwod** [hajkmap/Hajk#231]
I'm not sure that the minimize/maximize buttons behave as wanted. A lot of users have difficulty to understand the logic in it, so perhaps we should re-think how it's supposed to work?

![Jun-19-2019 09-42-32](https://user-images.githubusercontent.com/110222/59746282-db9ff400-9276-11e9-871c-9a4dd7917b60.gif)

**Comment by sbk-linus** [comment]
If plugins are positioned on top of the map it is not possible to drag and drop a panel around it. 

Perhaps this could be an additional feature to fix while working on this issue?

![image](https://user-images.githubusercontent.com/22494604/60340263-5a99d880-99ab-11e9-9e76-9e47c1675303.png)

**Comment by erikedmark** [comment]
Pull request added #251 (core/window-layout).
The windows is not aligning better. The containment is the map, not the center part. But the default alignment is still the center part, so the windows will be nicely placed and not covering too much.
Also solves some min/max issues.
