### ISSUE TITLE
Current scale indicator in map 

### ISSUE THREAD

**Issue by sbk-linus** [hajkmap/Hajk#233]
A scale bar should be displayed in the corner of the map.

![image](https://user-images.githubusercontent.com/22494604/59763021-dd7aaf00-9298-11e9-890c-3f730dff3946.png)

**Comment by jacobwod** [comment]
@sbk-linus Was this implemented as a custom control previously? The only scale-related control I can find in OL 5 is ScaleLine, and none of the options allow showing a numerical value like that one in screenshot.
