### ISSUE TITLE
User documentation

### ISSUE THREAD

**Issue by jacobwod** [hajkmap/Hajk#235]
There is an [ongoing effor on the GitHub Wiki](https://github.com/hajkmap/Hajk/wiki), but more need to contribute. Contact me if you don't have write permissions in Wiki (you need to have a GitHub account).

**Comment by jacobwod** [comment]
Far from done, postponing.

**Comment by ingvar-uddevalla** [comment]
Started to add documentation of 'Hajk Admin Utskrift' in wiki.

**Comment by jacobwod** [comment]
I'm closing this for now, feel free to re-open if needed.
