### ISSUE TITLE
Double click on map zooms in to max directly

### ISSUE THREAD

**Issue by jacobwod** [hajkmap/Hajk#255]
**Describe the bug**
When user double clicks on map, the viewer is supposed to zoom in one step at a time. But instead map zooms all the way down to max zoom in level. 

Using scroll wheel does not seem to work either. Instead, the user is stuck at max zoom in level.

**The bug did not exist in f278e0cf0fbe0bd370a7b1f8017b6c103b01b1e7 (v3.0.0-beta.1).**

**To Reproduce**
1. Open a map (notice that it starts in max zoom in level, no matter what you've defined in config)
1. Double click anywhere to zoom in
1. Map zooms in to max zoom level directly
1. Scroll to zoom doesn't work either
1. You can still use zoom in/out buttons

**Expected behavior**

**Screenshots**
![Bug - double click zooms in to max zoom directly instead of one step](https://user-images.githubusercontent.com/110222/63003567-b4316600-be78-11e9-9b46-2c164802f91d.gif)

**Desktop (please complete the following information):**
 - Browser Safari, Firefox, Chrome, possibly other

**Additional context**

**Comment by FatemeHosseini** [comment]
can you control if minZoom and maxZoom in map_1.json is right?
is maxZoom:s value bigger?

"maxZoom": 19,
"minZoom": 0,

**Comment by jacobwod** [comment]
> can you control if minZoom and maxZoom in map_1.json is right?
> is maxZoom:s value bigger?
> 
> "maxZoom": 19,
> "minZoom": 0,

Appreciate quick reply. No, maxZoom is a smaller value:
![image](https://user-images.githubusercontent.com/110222/63017310-4b58e680-be96-11e9-8a2a-7cc1d52d61b6.png) 

I haven't changed anything in my configs, only `git pull` latest code. If I revert to beta 1 everything is fine. 

What are your values @FatemeHosseini?

**Comment by jacobwod** [comment]
Confirmed it works if I change so that `maxZoom: 9, minZoom: 0`. But what's going on, did we change how it should behave recently?

**Comment by FatemeHosseini** [comment]
Good, I dont know when it changed.

**Comment by jacobwod** [comment]
@FatemeHosseini You had a similar issue and had to swap values for mix/max in your config too?

**Comment by jacobwod** [comment]
*Solution*
Just ensure that minZoom is smaller than maxZoom and it will be alright. Unsure how and why it worked the otherway around previously, but now it doesn't and it seems correct anyway.
