### ISSUE TITLE
Markerat sökområde stämmer inte med sökning

### ISSUE THREAD

**Issue by maria-sbk-gbg** [hajkmap/Hajk#260]
Om man klickar på gränsen mellan två eller flera områden så markeras båda i kartan men sökningen görs bara i det ena området. I sökfältet står "Markerat område: 1" vilket inte motsvarar grafiken men stämmer med sökningen. Behöver lösa så endast en (den som används vid sökning) yta är markerad i kartan.

**Comment by sweco-sesqqq** [comment]
The new search-component allows for multiple selections and should close this issue.
