### ISSUE TITLE
Rensa markeringar i kartan vid ny sökning

### ISSUE THREAD

**Issue by maria-sbk-gbg** [hajkmap/Hajk#261]
När man har markerat en eller flera sökträffar och därefter gör en ny sökning (utan att avbryta/rensa med krysset) så behålls den/de första markeringarna i kartan. Markeringarna försvinner i kartan medan man skriver in det nya sökordet och kommer inte tillbaka förrän man väljer att markera en träff i det nya sökresultatet. Tidigare markeringar ska rensas i samband med ny sökning.

**Comment by jacobwod** [comment]
Probably duplicate/closely related to #230.

**Comment by jacobwod** [comment]
I'm not sure this is fixed.

1. Search and select a result
1. Click on the feature in map (this will bring up the info click window)
1. Go to search and type another search string
1. Select one item in the results list (this will zoom the map to the clicked result)
1. The previously clicked result is still there, it is still selected and the info click window is visible (you might need to zoom out to see both results)
![Kapture 2019-11-14 at 15 08 33](https://user-images.githubusercontent.com/110222/68864018-b4980200-06f0-11ea-9b9b-bf26923ae969.gif)

Is this a bug or is it intended behaviour?

**Comment by sbk-linus** [comment]
It is a bug, but it's different to what is described in this issue.

In this issue the bug has to do with selecting items in the results list and not by info clicking a feature directly in the map. This is better explained in #230.
