### ISSUE TITLE
Områdessök-Markera. Det går inte att markera yta.

### ISSUE THREAD

**Issue by maria-sbk-gbg** [hajkmap/Hajk#263]
Områdessök-Markera. Det går inte att markera yta.

**Comment by jacobwod** [comment]
@maria-sbk-gbg Kan du verifiera om det går nu? Kan hända att jag fixade det samtidigt som jag rättade till en del annat i Sök.

**Comment by maria-sbk-gbg** [comment]
Med markera menar jag att använda verktyget Markera, dvs Sök genom att markera en polygon. Jag ber Linus uppdatera vår testmiljö så testar jag.

**Comment by sbk-linus** [comment]
Du kan testa nu, har uppdaterat.

**Comment by maria-sbk-gbg** [comment]
Tackar, det fungerar bra att markera polygon/objekt att söka i. 
![image](https://user-images.githubusercontent.com/54146057/65144472-b9557800-da17-11e9-81db-40e1d5ecff50.png)
