### ISSUE TITLE
Ändra antal sökträffar

### ISSUE THREAD

**Issue by maria-sbk-gbg** [hajkmap/Hajk#270]
Sätt antal sökträffar per lager till 1000.

**Comment by FatemeHosseini** [comment]
Hej Maria,
Jag önskar att denna issue åtgärdas tidigare. Det är bara att ändra **maxFeatures: 100,** till **maxFeatures: 1000,** i SearchModel.js, eller?
Jag hoppas att denna ändring sker redan i 3.0 :)

**Comment by FatemeHosseini** [comment]
går det att ställa in antalet  i admin-gränssnittet? Vi har en kris-karta som används av kris-gruppen, de vill att begränsningen skall tas bort så att de kan undersöka t.ex. när det händer något, hur många folk som bor i ett stort område; å andra sidan finns det vanliga användare som man vill begränsa antalet genom att sätta 100/1000.

**Comment by jacobwod** [comment]
Can you take a look at it @FatemeHosseini @victoraxbom ? Minor fix in `client` to read from config, plus some code in `admin` and `mapservice`.
