### ISSUE TITLE
Sök-funktionen: Inga "cards" dyker upp för funna lager m.m

### ISSUE THREAD

**Issue by ingvar-uddevalla** [hajkmap/Hajk#276]
**Så här är det:**

När man gjort sök med t ex radie, så syns sökmarkeringen (=cirkelytan) alltför svagt. Inga ”lagerkort” (cards)  dyker upp längst ner, dvs de små menyerna som ska visa vilka lager som hittats    (se bild nedan). Detta har fungerat förut.
Resultatrutan fastnar och går ej att stänga.  X knapp funkar ej.
![image](https://user-images.githubusercontent.com/54808837/64180560-42d84800-ce65-11e9-9bba-c537be6cd665.png)

**Så här vill vi ha det:**
I den version för Hajk Översiktsplan som Erik Edmark på WSP tog fram åt Uddevalla kommun (2.2 ?) fungerade det (se bild nedan)  dvs Lagerkort dyker upp längst ner som visar vilka lager som hittades. Lagerkorten har två knappar för lagerhantering: ögat för tänd/släck och kryss för ta bort. Önskvärt är även koppling till motsvarande avsnitt i Dokumenthanterarens text (något som funnits förut och hade ett ”T” som ikon).
![image](https://user-images.githubusercontent.com/54808837/64181089-2c7ebc00-ce66-11e9-879c-11eb1688bbf2.png)

**Versioner:**
Hajk 3 Beta. Testad huvudsakligen i Microsoft Edge. Ej testad i mobiltelefon.

**Notera**
Denna "issue" är en av de "Buggar/synpunkter på ÖP-verktygen" i HAJK 3 Beta" beskrivna 30 aug 2019 av användare i Uddevalla kommun.

**Comment by victoraxbom** [comment]
Sökningen fungerar som ni har tänkt er för oss, de små "lagerkorten" dyker upp som de ska vid sökning inom område och länkningen till texten i dokumenthanteraren fungerar. Kan det vara något i konfigurationen hos er som strular?

**Comment by ingvar-uddevalla** [comment]
Det funkade för oss hyfsat i Hjak 2.2, men inte nu i Hajk 3 Beta. Men visst kan det vara konfigurationsfel även i Hajk 3 Betan.

**Comment by ingvar-uddevalla** [comment]
Jag ser att Breadcrumbs (och widget plugin) nu finns som tillval i Admin. Superbra! Tyvärr verkar inte inställningarna sparas i json-filen och därmed händer inget vid testen sedan. Går detta att fixa?

**Comment by victoraxbom** [comment]
Jag har också testat nu och inställningarna för Breadcrumbs sparas som de ska för mig. Har ni byggt även backend så att det är den senaste?

**Comment by jacobwod** [comment]
@ingvar-uddevalla Helt rätt som @victoraxbom påpekar: ni måste bygga om `backend`. 

Stänger ärendet.

**Comment by ingvar-uddevalla** [comment]
@jacobwod @victoraxbom Backend är nu ombyggd (alla förändringar från dagen körs/byggs in på natten, så därför ser jag inte dessa förrän dagen efter). Tyvärr sparas fortfarande inte gjorda inställningar för showbreadscrumbs, title och description i <kartnamn>.json  Jag har testat att skapa en helt ny karta även testat i Chrome. Jag använder mest Microsoft Edge. Jag har sökt en hel del i JS-koderna, config-filer men det är svårt att hitta om något är fel.
