### ISSUE TITLE
Önskad Admin-dokumentation om hur man bygger indataformulär i modulen "Collector"/Tyck Till

### ISSUE THREAD

**Issue by ingvar-uddevalla** [hajkmap/Hajk#278]
**Så här är det:**
Vidareutveckling av ”Uddevallas” Tyck Till-verktyg (som ingick i den version för Hajk Översiktsplan som Erik Edmark på WSP tog fram åt Uddevalla kommun 2.2 ?) har gjorts mer generell i syfte att kunna fungera som ett egenanpassat indataformulär m.m. (nu omdöpt till modulen Collector). Det är säkert ett bra tänk, men det kräver att man som administratör behöver veta hur man skapar/bygger upp detta indataformulär, vilka funktioner som kan användas här i etc. Då det saknas uppdaterad dokumentation om detta (jag har i alla fall inte kunnat hitta detta i github) så blir detta svårt.
De två bilderna nedan visar hur det ser ut i Adminverktyget respektive i kartan.
![image](https://user-images.githubusercontent.com/54808837/64182144-0528ee80-ce68-11e9-82df-d875768577d9.png)

**Så här vill vi ha det:**
En stark önskas blir således en bättre Admin-dokumentation samt möjlighet att kunna skapa och använda en meny liknande i ”den version för Hajk Översiktsplan som Erik Edmark på WSP tog fram åt Uddevalla kommun (2.2 ?)”. I detta finns tydliga knappar med kommandon som utför vidare hantering. (Se de två bilderna nedan där bild två visar hur dialogen ser ut efter att man valt "Tyck till om en plats").
![image](https://user-images.githubusercontent.com/54808837/64182247-39041400-ce68-11e9-960b-3399dd3f8f3d.png)
![image](https://user-images.githubusercontent.com/54808837/64182267-3dc8c800-ce68-11e9-9440-09173b4e9e49.png)

**Notera**
Denna "issue" är en av de "Buggar/synpunkter på ÖP-verktygen" i HAJK 3 Beta" beskrivna 30 aug 2019 av användare i Uddevalla kommun.

**Comment by jacobwod** [comment]
Utgår från att @ingvar-uddevalla var nöjd med den förra kommentaren om Wikin, stänger ärendet.

**Comment by ingvar-uddevalla** [comment]
Ja, den var bra. Det gör verkligen skillnad att veta hur admin ska hanteras t ex genom wikin. Innan fick jag gå in i koden eller fråga er. En viss skillnad :-)

**Comment by jacobwod** [comment]
Bra. Du och Ylva får mer än gärna gå in i Wikin och fylla på med guider för andra plugins som ni känner er mer bekanta med. 👍

**Comment by ingvar-uddevalla** [comment]
Javisst!

**Comment by jacobwod** [comment]
Fint! Du/ni ser vad som är kvar här: https://github.com/hajkmap/Hajk/wiki/Användardokumentation-HAJK3:-Status. Ta gärna kontakt med @victoraxbom om ni har frågor om hur man editerar i Wikin eller liknande.

**Comment by ingvar-uddevalla** [comment]
Jag börjar med kapitlet "Dokumenthanteraren" och använder den text som finns i Admin-manualen för Hajk version 2.1.1. Jag ska sen justera denna, byta ut skärmbilder etc. @victoraxbom du får gärna kolla över den sedan, då jag har för mig att ni lagt till förbättrade utskriftsfunktioner, som jag inte har full koll på.

**Comment by victoraxbom** [comment]
Toppen, jag kan kolla över det sen, som du säger så har vi lagt till utskrift och teckenförklaring i den.

**Comment by ingvar-uddevalla** [comment]
Fråga @victoraxbom : Bilderna i wikin är ju URL:er till bilder som jag förmodar du laddat upp på plats i githuben, t ex user-images.githubusercontent/......png Hur och var laddar jag in dessa?

**Comment by victoraxbom** [comment]
@ingvar-uddevalla 
Jag gjorde egentligen en liten fullösning för att få upp dem snabbt. Om du drar en bild in här i textrutan där du skriver kommentarer så laddas bilden upp och du får en länk som kan användas även i wikin. 
Egentligen borde vi nog samla alla bilder och lägga upp dem i en mapp i repositoryn, men blir kanske lite omständligt att skapa pull requests för varje bild vi ska ha in. Tänker att vi kan göra det när alla delar är klara och bara länka om bilderna då. Om det inte går att fler får commit-rättigheter till bara enstaka mappar? @jacobwod

**Comment by ingvar-uddevalla** [comment]
OK! Ska hitta ett bättre kommentarsfält än detta kanske. Jag börjar med tre bilder enligt din "fullösning".
![image](https://user-images.githubusercontent.com/54808837/65250121-59350380-daf5-11e9-8e37-a265cab5c1e1.png)
![image](https://user-images.githubusercontent.com/54808837/65250133-63570200-daf5-11e9-8873-f4f09dcc6bfa.png)
![image](https://user-images.githubusercontent.com/54808837/65250169-71a51e00-daf5-11e9-9819-0ce8b7885401.png)

**Comment by victoraxbom** [comment]
@ingvar-uddevalla Du behöver inte spara kommentaren med bilderna, räcker att dra in och kopiera länken

**Comment by ingvar-uddevalla** [comment]
Ah, of course. Tack @victoraxbom :-)

**Comment by jacobwod** [comment]
Jag tycker inte det är nån fullösninig. Det är tanken att man jobbar så, både i issues, kommentarer och wikin. Kör på det som ni gör. Det hade jag gjort.

Vänligen,
Jacob

GIS-utvecklare
Avdelningen för geodata
Byggnadskontoret
Halmstads kommun



On Thu, Sep 19, 2019 at 3:58 PM +0200, "Ingvar Petersson" <notifications@github.com<mailto:notifications@github.com>> wrote:


Ah, of course. Tack @victoraxbom<https://github.com/victoraxbom> :-)
