### ISSUE TITLE
lås upp verktygspanelen

### ISSUE THREAD

**Issue by FatemeHosseini** [hajkmap/Hajk#281]
**Beskrivning av bugg**
om man har några 'Window-panelContent' aktiva i kartvyn och låser upp verktygspanelen utvidgas fönstrets bredd och om man hade en 'Window-panelContent' till höger om sidan, göms en del av panelen och man blir tvungen att dra panelen lite år vänster istället. 
![Skärmklipp](https://user-images.githubusercontent.com/36195301/65145973-19015280-da1b-11e9-9233-e2fad0368711.PNG)

**Comment by jacobwod** [comment]
Stämmer bra, känt från början. Kräver lite arbete i Rnd-komponenten men ska gå att lösa.

**Comment by jacobwod** [comment]
@FatemeHosseini Truly fixed as of 912840a18ca88ede22345f5b3cb7afcd823b672d.
