### ISSUE TITLE
Layerswitcher -> lagergrupp

### ISSUE THREAD

**Issue by FatemeHosseini** [hajkmap/Hajk#282]
Ett lager som består av flera wms:er visas som ett undergrupp i lagerhanterare.

I admingränssnittet:
![image](https://user-images.githubusercontent.com/36195301/65146450-1e12d180-da1c-11e9-9f44-39349383e005.png)

I klienten:
![lagerhanterare](https://user-images.githubusercontent.com/36195301/65146470-2c60ed80-da1c-11e9-84ea-4e23a64f17f6.PNG)

Kollektivtrafik är ett lager som består av två WMS:er. Den ska visas i samma nivå som lagret Lax och Mätpunkter men det visas som att Kollektivtrafik är underlagergrupp för Lax.

**Comment by jacobwod** [comment]
Ja, trodde att @sbk-linus  skulle ta hand om det när han sa att han fixar LayerSwitcher, men jag får väl kolla på det också.

**Comment by sbk-linus** [comment]
De ligger i samma nivå men eftersom pil-ikonen endast finns på lagergrupper så ser det ut som att det blir en undergrupp. Alternativ på lösning kan vara att lägga till _margin_ till vänster om kryss-ikonen eller att byta plats på pil-ikonen och kryss-ikonen.

**Comment by jacobwod** [comment]
Vi kan testa oss fram eller så kan vi titta på olika alternativ som finns. Hade ni några mockups? Även om de är gamla nu och en del är implementerat annorlunda än i dem: lägg upp dem här så har vi nåt att utgå ifrån.

**Comment by sbk-linus** [comment]
![image](https://user-images.githubusercontent.com/22494604/65152520-6b953b80-da28-11e9-9791-b9cce33f02a5.png)

**Comment by jacobwod** [comment]
Det ser väl bra ut. 

En sak som ställer till det och som man kanske inte tagit hänsyn till i mockupen är att **toggla alla-knappen är valbar i admin**. Så det är inte säkert vi har den framför varje lagergrupp, och då förstörs den fina ordningen och blir typ såhär: 
![image](https://user-images.githubusercontent.com/110222/65153003-49e88400-da29-11e9-8930-dabc98e29341.png)

Som Analyser och underlag ovan. 

Och det måste ju hanteras. Förslagsvis med en `disabled` checkbox. Men då finns risken att nån kommer och klagar på att vi har en massa checkboxar som ändå inte går att klicka på, och då vill man inte ha dem alls. 

Men vi måste ta ställning här. Spontant, för en konsekvent lista, lutar jag åt utgråade checkboxar.

**Comment by sbk-linus** [comment]
Precis, det måste finnas någon ikon där som _placeholder_ för att hålla det enhetligt. Kan testa hur det blir.

**Comment by victoraxbom** [comment]
Som det är på "Administrativ indelning" i mockupen är ju ett alternativ som känns bra. Som en bonus skulle ju gruppen kunna öppnas upp (som det fungerar med pilen) om man ändå trycker på den.

**Comment by jacobwod** [comment]
Håller med om att `expand/close` ska fungera oavsett om `togglable=true|false`.

**Comment by sbk-linus** [comment]
Så här ser den nya designen ut. Testa gärna och tyck till.

![image](https://user-images.githubusercontent.com/22494604/65225889-34756780-dac6-11e9-80ec-a88549c96edc.png)

**Comment by FatemeHosseini** [comment]
Det ser bra ut Linus, GILLAR

**Comment by jacobwod** [comment]
Är det nåt kvar på den här eller kan den stängas @FatemeHosseini , @sbk-linus ?
