### ISSUE TITLE
Toggle all for groups/layer groups should work as expected

### ISSUE THREAD

**Issue by FatemeHosseini** [hajkmap/Hajk#283]
Lagergrupper med 'Toggla alla-knapp' som själv innehåller underlagergrupper, inte kan tända lager som ligger i underlagergrupper; oavsett om underlagergruppen har 'Toggla alla-knapp' aktiverad eller inte.

![image](https://user-images.githubusercontent.com/36195301/65147065-99c14e00-da1d-11e9-8a81-249aa2f347a7.png)

**Comment by FatemeHosseini** [comment]
Jag hittade en annan intressant nu när jag testar. Se bilderna nedan, **Mätpunkter** och **Lagergrupp nivå1** ligger i samma nivå. Om jag tänder **Mätpunkter** blir **Kartlager** grå men om jag tänder **Lagergrupp nivå1** händer det inte något.
![image](https://user-images.githubusercontent.com/36195301/65148318-3b499f00-da20-11e9-8e4b-0fd41c42d92d.png)

![image](https://user-images.githubusercontent.com/36195301/65148345-47cdf780-da20-11e9-80f8-98df8fb2f07f.png)

**Comment by jacobwod** [comment]
Har testat här och tyvärr kvarstår issuen @sbk-linus @FatemeHosseini:

![Issue 283 LayerSwitcher](https://user-images.githubusercontent.com/110222/65497609-cf04ea80-deba-11e9-8dba-89816a14b373.gif)

Konfigurerat i admin enligt följande (med "vanliga, hajk2-grupper"):
![bild](https://user-images.githubusercontent.com/110222/65497690-ea6ff580-deba-11e9-8a0f-8b2bdfdeee65.png)

**Comment by jacobwod** [comment]
Lyckligtvis påverkas __bara Hajk2-grupper__.

De nya Hajk3-grupperna hänger med vid toggling av huvudgrupp. __Däremot så är det olika indrag på de olika grupptyperna, @sbk-linus.__ I nedanstående bild är de båda _Hajk-grupperna_ samt _Undergrupp_ på samma nivå, direkt under _Kök_. Men man får intrycket att _Undergrupp_ ligger som _Kök->Hajk-grupp->Undergrupp_, vilket det alltså __inte__ gör. Kan du fixa till stylingen?

![bild](https://user-images.githubusercontent.com/110222/65497859-39b62600-debb-11e9-9f36-12fdaba763c5.png)

**Comment by jacobwod** [comment]
@sbk-linus Din senaste commit verkar inte ge några resultat här, se hur "Undergrupp" stylas.

<img width="228" alt="image" src="https://user-images.githubusercontent.com/110222/65626167-635f7200-dfcd-11e9-9595-e70a2593b104.png">

Bortsett från stylingen har vi även problemet med togglingen. Är det nåt du tittar på också?

**Comment by sbk-linus** [comment]
Konfigurerade lagren på samma sätt som i exemplet, men det såg inte likadant ut. Har du någon _config_ du skulle kunna dela?

**Comment by jacobwod** [comment]
Givetvis, men utan tillhörande `layers.json` kommer du förvisso se lagren men inte kunna ladda dem. Jag är osäker på om Hajk kommer "veta" att några av lagren är av typen hajk3-lagergrupp, så det är osäkert hur dessa kommer stylas hos dig. Men här är det relevanta avsnittet:

```javascript
{"groups":[{"id":"59b47b05-53ed-58ab-86e2-de5b13863384","parent":"-1","name":"Kök","toggled":true,"expanded":true,"layers":[{"id":"187","visibleAtStart":false,"drawOrder":1000,"visibleForGroups":null,"infobox":null},{"id":"186","visibleAtStart":false,"drawOrder":1000,"visibleForGroups":null,"infobox":null},{"id":"406","visibleAtStart":false,"drawOrder":1000,"visibleForGroups":null,"infobox":null},{"id":"647","visibleAtStart":false,"drawOrder":1000,"visibleForGroups":null,"infobox":null},{"id":"646","visibleAtStart":false,"drawOrder":1000,"visibleForGroups":null,"infobox":null}],"groups":[{"id":"222e8cae-2137-034f-e609-288a594fe19f","parent":"59b47b05-53ed-58ab-86e2-de5b13863384","name":"Undergrupp","toggled":true,"expanded":true,"layers":[{"id":"100","visibleAtStart":false,"drawOrder":1000,"visibleForGroups":null,"infobox":null},{"id":"380","visibleAtStart":false,"drawOrder":1000,"visibleForGroups":null,"infobox":null}],"groups":[]}]},{"id":"11f7c430-ec36-0526-aed9-422f67a745ee","parent":"-1","name":"En grupp","toggled":true,"expanded":true,"layers":[{"id":"648","visibleAtStart":false,"drawOrder":1000,"visibleForGroups":null,"infobox":null},{"id":"641","visibleAtStart":false,"drawOrder":1000,"visibleForGroups":null,"infobox":null}],"groups":[]}]}
```

I admin är det som sagt så här: `Undergrupp` är på samma nivå som de två `Hajk-grupperna`, båda har alltså `Kök` som förälder. 
<img width="241" alt="image" src="https://user-images.githubusercontent.com/110222/65669212-6dbc5300-e043-11e9-818e-761b91d77bfa.png">

**Comment by sbk-linus** [comment]
Kan inte återskapa buggen i min utvecklingsmiljö. Skulle du kunna kolla på detta istället, @jacobwod?

**Comment by jacobwod** [comment]
OK får kolla när jag är tillbaka mitten på nästa vecka.

**Comment by FatemeHosseini** [comment]
"Tänd alla"-knappen fungerar inte när man har mera nivåer, se exemplet nedan.
![image](https://user-images.githubusercontent.com/36195301/66486919-c52eda00-eaab-11e9-8eb7-10c836484525.png)

Jag kan  bara tända alla som hamnar på lagergruppen som heter Busstrafik.

**Comment by jacobwod** [comment]
Du menar att det händer ingenting när du kryssar i "TRANSPORTER OCH INFRASTRUKTUR" eller "Transporter"?

**Comment by FatemeHosseini** [comment]
Japp!

**Comment by jacobwod** [comment]
Kollade på det och det ser inte bra ut. **Toggle all verkar endast "ta" på det som finns definierat som lager i OpenLayers `layers` array.** "Våra" egna grupper som skapas i admin är ju inte det. Resultatet blir att de förbises av toggle:
![bug-se12138221](https://user-images.githubusercontent.com/110222/66755330-11a55b80-ee98-11e9-8e47-360d5cb9de78.gif)

Inställt såhär i admin:
![bild](https://user-images.githubusercontent.com/110222/66755391-2a157600-ee98-11e9-84dc-c82366c197fe.png)

**Felet ligger i att vi loopar genom ett objekt som inte innehåller våra grupper.** Det ser man tydligt här, **allt som händer vidare i `toggleLayers()` utgår från arrayen som fås tillbaka från OpenLayers:** 
https://github.com/hajkmap/Hajk/blob/master/new-client/src/plugins/layerswitcher/components/LayerGroup.js#L180

**Comment by FatemeHosseini** [comment]
Jag kan tända alla lager som visas i bilden nedan men checkboxen blir inte ifylld.
![image](https://user-images.githubusercontent.com/36195301/68599390-c5eacf80-04a0-11ea-9cc2-907ce78594b8.png)

**Comment by sweco-seqtob** [comment]
Vet inte om den här buggen fortfarande är aktiv men jag har en PR på gång som löser "hajkgrupper" i "hajkgrupper" för lagerhanteraren.

**Comment by jacobwod** [comment]
> Vet inte om den här buggen fortfarande är aktiv men jag har en PR på gång som löser "hajkgrupper" i "hajkgrupper" för lagerhanteraren. 
> 
> 

Ja, fortfarande öppen så välkommen med din PR!

**Comment by sweco-seqtob** [comment]
@jacobwod found another bug when having one layer and a group in a group and only checked they layer.
Fixed by commit #21e7545f52dc04b3627b6cf2fba376a848b43c85

**Comment by jacobwod** [comment]
Well done, merging in.

**Comment by jacobwod** [comment]
Ah it's already in `master`, perfect. I can confirm that this seems to squash down the last edge case I could find.

Before:
![Skärmavbild 2021-01-26 kl  15 11 21](https://user-images.githubusercontent.com/110222/105966714-4e916380-6085-11eb-8075-702e80415fd6.png)

After:
![Skärmavbild 2021-01-27 kl  09 51 01](https://user-images.githubusercontent.com/110222/105966720-4f29fa00-6085-11eb-8f93-304aae74cc68.png)

Closing. 👍
