### ISSUE TITLE
Improvments to Window managmenet

### ISSUE THREAD

**Issue by jacobwod** [hajkmap/Hajk#285]
_Please note that some of these might make it to 3.0, even if the issue is tagged as 3.1._

Window management needs some further improvement:
- Multiple Windows can be opened simultaneously
- Admin can configure if a Window should auto-close when other windows are opened or not
- Admin can configure if a Window will open on left or right side of the screen. This setting, called `position` must be independent of the `target` setting, that determines whether a plugin will render in Drawer or as left or right Widget.

**Comment by jacobwod** [comment]
Partly fixed in 912840a18ca88ede22345f5b3cb7afcd823b672d

**Comment by jacobwod** [comment]
`position` part fixed in 2517e2285914d3ad517fb93acbf187930224fc52 and a couple of following commits.

This leaves us with "Admin can configure if a Window should auto-close when other windows are opened or not" left, and I feel we should discuss if we want to allow this or not. It opens up for a lot of confusion, but also gives admins tons of flexibility when it comes to deciding how Hajk behaves.

**Comment by FredrikEkstrom79** [comment]
Personaly i prefer to be able to open more than one window.

**Comment by victoraxbom** [comment]
Everything in this issue is solved except the part that is broken out to #376 . I'm closing it
