### ISSUE TITLE
Export in Informative does not work

### ISSUE THREAD

**Issue by jacobwod** [hajkmap/Hajk#305]
**Describe the bug**
When using the Informative plugin (in most instances called *Översiktsplan*) there is an option to print the text content of the plugin to PDF. However, click on the Print icon does not result in a PDF. An error is shown when user previews the response in Developer Tools' Network tab.

**To Reproduce**
1. Configure Informative and verify it's working
1. Open a chapter in Informative
1. Click on the Printer icon that should export to PDF
1. You will get a *Download* link that does not work and if you inspect the response sent from server, there will be further error info.

**Expected behavior**
PDF gets downloaded.

**Screenshots**
![bild](https://user-images.githubusercontent.com/110222/67488983-0c52c880-f671-11e9-81a6-a57fd5f44708.png)

**Debug info**
```
Server Error in '/mapservice3' Application.
Object reference not set to an instance of an object.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.NullReferenceException: Object reference not set to an instance of an object.

[NullReferenceException: Object reference not set to an instance of an object.]
MapService.Models.Config.WMSConfig.AsInfo(Int32 zIndex) in D:\Hajk\backend\mapservice\Models\Config\WMSConfig.cs:24
MapService.Components.<>c.<AppendMap>b__16_1(WMSConfig layer) in D:\Hajk\backend\mapservice\Components\DocumentCreator.cs:236
```

**Comment by victoraxbom** [comment]
Det fungerar som det ska för mig. Jag har testat både kapitel med karta kopplad och kapitel utan karta kopplad. Kan det bero på något kartlager du har kopplat inte nås eller liknande?

**Comment by jacobwod** [comment]
Ok bra. Får jag också fråga hur aktuell din backend är? Skulle du kunna kompilera en ny men behålla din App_Data och se om det är nåt som har hänt där i och med de senaste uppdateringarna? Troligtvis är det våra konfigurationsfiler, men vill ändå veta att senaste `master` är OK.

**Comment by victoraxbom** [comment]
Jag kompilerade den helt ny för att testa så `master` borde vara okej!

**Comment by jacobwod** [comment]
Tack!

**Comment by FredrikEkstrom79** [comment]
Det fungerar så länge vi inte har något kopplat kartlager till dokumentet. Så fort vi lägger till ett lager blir det detta fel.

Har ni i Kungsbacka  kopplat lager till ert dokument?

**Comment by FatemeHosseini** [comment]
Jag får det att fungera med kartkopplingen.

**Comment by jacobwod** [comment]
@FatemeHosseini @victoraxbom Vad är det för lager ni har kopplade? Vanliga eller grupplager? WMS (1.1.0 eller 1.3.0) eller Vektor?

**Comment by FatemeHosseini** [comment]
alla är WMS från QGISServer och GeoServer, Både vanliga och grupplager, 1.1.1 och 1.3.0

**Comment by jacobwod** [comment]
Changing milestone from 3.0 to 3.x, as it might not affect 3.0 release after all.

**Comment by jacobwod** [comment]
Will soon be super-seeded by the upcoming Documents-plugin, which has a client-based print.
