### ISSUE TITLE
Filter function on vectorlayer not working

### ISSUE THREAD

**Issue by victoraxbom** [hajkmap/Hajk#318]
There are two ways of filtering a vectorlayer in Hajk. The first is a pre-filter set up by an administrator in the admin interface when the vectorlayer is created. The second one is set up by the user directly in the layer manager (if filtering is enabled).

The first one is working but the second one doesn't work. The activate button just clears the layer.

![image](https://user-images.githubusercontent.com/3994163/68130990-97a74600-ff1c-11e9-932a-a96b28108de0.png)

**Comment by jacobwod** [comment]
I  can confirm this but must dig deeper before fixing. I didn't find any relevant examples of filtering vector layers in OL, but obviously the current solution doesn't work. Here's the method that's supposed to activate filter:

```javascript
setFilter = e => {
    const { filterAttribute, filterValue, filterComparer } = this.state;
    var vectorSource = this.props.layer.getSource();
    this.features = vectorSource.getFeatures();
    this.props.layer.set("filterAttribute", filterAttribute);
    this.props.layer.set("filterValue", filterValue);
    this.props.layer.set("filterComparer", filterComparer);
    vectorSource.clear();
  };
```

**Comment by victoraxbom** [comment]
`vectorSource.refresh();` instead of `vectorSource.clear();` seems to fix the problem. Don't know why you would like to clear the layer without adding new features again.

**Comment by victoraxbom** [comment]
As it is now, the filter function actually works if you set the filter before turning on the layer and populate it with features. But then you cannot change the filter

**Comment by jacobwod** [comment]
I agree @victoraxbom. However, I tried this out with a huge layer (all address points in the municipality) and it was really slow getting the unfiltered results. So it's good to have the ability to filter prior first request. 

But the subsequent request should probably result in something like:
1. hide all features previously shown
1. take the new filter settings into account and do GetFeature request to the WFS
1. render

As it is now, it looks like we're only try to filter in already existing results, which limits what is shown if user sets filter *prior* the first request. What is your opinion?

**Comment by victoraxbom** [comment]
I agree, you should be able to set a pre-filter. But do we really only use the existing result as it is now? The WFS-request is always on the whole layer and the filtering is handled only in HAJK. So by changing the filter and do a new request (ex. with `vectorSource.refresh();`) you get the whole layer again compared to the new filter. 

But your solution seems to solve it if we send the filter with the WFS-request instead of requesting all features and do the filtering in HAJK. But that would only work if the layer is a WFS-layer and not as geojson from another source

**Comment by jacobwod** [comment]
> But that would only work if the layer is a WFS-layer and not as geojson from another source

That's right. So we need to filter on client side anyway, right?

**Comment by victoraxbom** [comment]
Yes, at least for the geojson option then
