### ISSUE TITLE
The tool "Visa koordinat" does not update on subsequent clicks. 

### ISSUE THREAD

**Issue by matself** [hajkmap/Hajk#319]
**Describe the bug**
The tool to capture and show map coordinates only shows the coordinate for the first clicked point. Subsequent clicks on the map canvas moves the pointer but does not update the coordinate values.

**To Reproduce**
Steps to reproduce the behaviour:
1. Activate and configure the tool 'Visa koordinat'
2. Open a the map.
3. Select the tool. A help text is shown on a blue brick, and an empty tool box.
4. Click a point. Numbers are shown.
5. Click another point. The cursor moves but numbers are not updated.
The application freezes briefly after the following clicks.

**Expected behaviour**
The expected behaviour is that the tool dialog updates with new coordinates for following clicks, until the user closes the tool.

**Screenshots**
Configuration
![image](https://user-images.githubusercontent.com/12749960/68323721-4dfa5f00-00c6-11ea-8ece-4f2c0b0f7bb8.png)

**Desktop (please complete the following information):**
 - OS: Windows 
 - Browser Chrome
 - Version 78.0.3904.87 (Official Build) (64-bit)

**Comment by jacobwod** [comment]
I can't replicate the issue, see screenshot:
![Coordinates work](https://user-images.githubusercontent.com/110222/68465668-2fee4500-0213-11ea-8430-985654b880b1.gif)

Any clues from Console in Developer tools?

**Comment by matself** [comment]
Hi Jacob!
After activating the coordinate picker, NO network activity is recorded.
Not for the first click, which returns coordinates, neither for following
clicks that return no coordinates.
This goes for two HAJK3 instances, one on our network and one in the cloud.
Also goes for Chrome, Firefox and Edge (msie does not show those controls)

Feel free to check http://gisby.kommunkarta.online for test.
Or http://gisby.kommunkarta.online/?m=karta_2

Best regards, Mats.E


*GisKraft*, Geodatakonsult

Mats Elfström, Marsvinsholms stationsväg 80, 271 93 Ystad, Sweden
tel: +46 70 595 39 35 / web: www.giskraft.com


Den fre 8 nov. 2019 kl 10:33 skrev Jacob Wodzyński <notifications@github.com

**Comment by jacobwod** [comment]
I didn't expected any network activity for getting coordinates. 

> Any clues from **Console** in Developer tools?

**Comment by FredrikEkstrom79** [comment]
When you have configured a coordinate transformation it fails to show coordinates.
![image](https://user-images.githubusercontent.com/50202826/68475134-8feee680-0227-11ea-8633-4d8f7fac64f4.png)
![image](https://user-images.githubusercontent.com/50202826/68475002-35ee2100-0227-11ea-80ef-15c321c6d054.png)
If no custom is defined it works (it will only show WGS84)
![image](https://user-images.githubusercontent.com/50202826/68475182-b44ac300-0227-11ea-8a6f-412f470b413b.png)
![image](https://user-images.githubusercontent.com/50202826/68475210-c75d9300-0227-11ea-8a4b-9be33a7c2564.png)

**Comment by jacobwod** [comment]
That's correct. 

**When there is not configuration of the plugin in `admin`, it works fine and shows WGS84 coordinates. But as soon as you configure something, error shown in @FredrikEkstrom79 comment above show up, on each click.** 

@sbk-linus, will you look at this?
