### ISSUE TITLE
'Kartväljaren' only shows a map with the title 'Hajk 3 Demo'

### ISSUE THREAD

**Issue by matself** [hajkmap/Hajk#320]
**Describe the bug**
The map select tool only shows a map with the title 'Hajk 3 Demo', if such a map file is present. And regardless of what the json file is called. Even if the file names are strictly a-z,1-9.
If no such map is present, nothing is shown.
The present map title is presented correctly.

**To Reproduce**
1. Make a couple of new maps. Rename the map_1.json file. 
2. Open one of the new maps.
2. Click the map selector. Only the Hajk 3 Demo map is listed.
3. Close HAJK and remove the renamed map_1 file from the folder, or make sure that no map is titled Hajk 3 demo.
4. Open HAJK with any map. 
5. Click the map selector. Only a tiny square displays, with no map list.

**Expected behavior**
The tool should list the Titles of all available map files in the folder.

**Screenshots**
![image](https://user-images.githubusercontent.com/12749960/68329048-bd754c00-00d0-11ea-8720-475e5c8e86cd.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 78.0.3904.87 (Official Build) (64-bit)[e.g. 22]

**Comment by jacobwod** [comment]
Open the Network tab in Developer tools and filter for `userspecificmaps` which is the request that is made to populate dropdown with values. What is your response?

```http
GET https://example.com/mapservice/config/userspecificmaps
```

```javascript
[
   {
      "mapConfigurationName":"jw",
      "mapConfigurationTitle":"Jacobs testkarta"
   },
   {
      "mapConfigurationName":"mbk",
      "mapConfigurationTitle":"MBK-karta (beta)"
   },
   {
      "mapConfigurationName":"op",
      "mapConfigurationTitle":"Framtidsplan 2030 som har en lång titel"
   },
   {
      "mapConfigurationName":"test",
      "mapConfigurationTitle":"Testkarta"
   }
]
```

**Comment by matself** [comment]
Hi Jacob!
On click on the Map selector, the debugger records NO network activity. The
text Hajk 3 Demo appears nevertheless.  Click on this label loads the map.
Or reloads it if it's the current one.
This goes for two HAJK3 instances, one on our network and one in the cloud.
Also goes for Chrome, Firefox and Edge (msie does not show those controls)

Feel free to check http://gisby.kommunkarta.online for test.
Or http://gisby.kommunkarta.online/?m=karta_2

Best regards, Mats.E


*GisKraft*, Geodatakonsult

Mats Elfström, Marsvinsholms stationsväg 80, 271 93 Ystad, Sweden
tel: +46 70 595 39 35 / web: www.giskraft.com


Den fre 8 nov. 2019 kl 10:28 skrev Jacob Wodzyński <notifications@github.com

**Comment by jacobwod** [comment]
The request is being made on app load. You have a response and it contains one map, and that map is visible in the dropdown. This is the case for both setups you've referenced:
![bild](https://user-images.githubusercontent.com/110222/68467843-38e11580-0217-11ea-9062-fb9de337e498.png)

![bild](https://user-images.githubusercontent.com/110222/68467927-5ca45b80-0217-11ea-941a-434491353bc1.png)

**Comment by matself** [comment]
That is precisely the problem, that only that one map is returned.
Here are the contents of App_data on the Gisby Instance.
Further, if there is NO map_1.json file, nothing is returned.


*GisKraft*, Geodatakonsult

Mats Elfström, Marsvinsholms stationsväg 80, 271 93 Ystad, Sweden
tel: +46 70 595 39 35 / web: www.giskraft.com


Den fre 8 nov. 2019 kl 11:03 skrev Jacob Wodzyński <notifications@github.com

**Comment by jacobwod** [comment]
I can't see any screenshots @matself . But in general, make sure to use lowercase letters, no special characters except underscore (_). 

Also, *ensure that you've ticked this setting for each map that should show up in MapSwitcher* (the last checkbox):
![image](https://user-images.githubusercontent.com/110222/68475397-510d6080-0228-11ea-95b1-c8fb378243a7.png)

**Comment by matself** [comment]
I see. That looks obvious. But I do not have that check box.
![image](https://user-images.githubusercontent.com/12749960/68477095-ced36b00-022c-11ea-9404-5db96c8b92c8.png)

**Comment by jacobwod** [comment]
Can somebody else check if they have this choice in `admin`? I don't have any uncommitted changes so it should've been uploaded, but if it's not I'll try to edit the relevant file again to push the changes.

**Comment by victoraxbom** [comment]
The checkbox is only visible if you activate authentication. 
`"authentication_active": true` in admin/config.json
Should preferably work even without authentication active

**Comment by jacobwod** [comment]
Thank you @victoraxbom. I agree that this option should not be dependent on AD authentication setting. Weird though, as I had no idea that this setting had effect on what's visible in `admin`. How can that be?

**Comment by victoraxbom** [comment]
> Thank you @victoraxbom. I agree that this option should not be dependent on AD authentication setting. Weird though, as I had no idea that this setting had effect on what's visible in `admin`. How can that be?

It's the same with the input boxes for AD-groups, but that makes more sense. Don't know why also the theme map checkbox is hided, Seems a bit strange when you can use the function even without AD authentication

**Comment by jacobwod** [comment]
Thanks for help with debugging this. Input boxes for AD group still shown only if `"authentication_active": true` – there's no reason to show it otherwise. But settings that control MapSwitcher (visibility in other maps and title) are now visible regardless of AD authentication value.

**Comment by jacobwod** [comment]
And @matself: you'll need to either compile `admin` on your own from `master` or wait till next release (no release date yet but perhaps somebody can help you out with this).

**Comment by matself** [comment]
I would be ok with waiting for a new release if I knew that one was coming in a week or so.
A regular release schedule would really be helpful for us that run production sites. Especially now when there is a new release, likely to receive frequent bug fixes. 
If you are a regular user, I think it is kind of hard to have to set up a compiler and development environment only to get the latest version of Hajk 3. Also, it would introduce even more parameters that can go wrong and leave an even more questionable result with regards to bug reporting. Further, each user/tester will potentially run a different version of the code, rendering bug reporting and bug tracing even more difficult.

**Comment by jacobwod** [comment]
I agree that non-developers should stick with pre-compiled releases. We will discuss the release policy in an upcoming developer meeting and hopefully come up with something that works for everyone.
