### ISSUE TITLE
Snabbval (preset) is missing in Hajk3 - new-client

### ISSUE THREAD

**Issue by perosoderstrom** [hajkmap/Hajk#323]
**Describe the bug**
You can configure preset in new-admin but the plugin does not show up in Hajk3 new-client. I guess the plugin is not yet migrated from Hajk2 to Hajk3. There is no folder "preset" in new-client/src/plugins.

**Expected behavior**
When configured and activated in Admin, the plugin Snabbval should show up in client.

**Comment by jacobwod** [comment]
You're right @perosoderstrom, but I'll close this issue since that functionality is already described in #152, and then further expanded upon in #159. Please see if #159 it fulfills your requirements, feel free to comment if something's missing.

**Comment by jacobwod** [comment]
When I think about it tough: we could in the meantime add some info about the plugin not being implemented in `admin` (or hide the configuration). I understand if users get confused the way it works now.

**Comment by perosoderstrom** [comment]
I have created a branch plugin-preset with code for the plugin. Right now it is implemented as an ordinary plugin, whith possible placement in toolbar or left or right (referring to the discussion in issue #159 ).

**Comment by jacobwod** [comment]
This is closed as of #336. The current implementation does however display a Window. Another option would be to do something similar to MapSwitcher, see [this comment](https://github.com/hajkmap/Hajk/issues/159#issuecomment-549362117). It's a rather small fix to convert this `BaseWindowPlugin` to a free floating button below the zoom buttons, but the **question that remains is whether we want it to be free floating or a window based plugin?**
