### ISSUE TITLE
Make it possible to download (export) a layer as KML

### ISSUE THREAD

**Issue by jacobwod** [hajkmap/Hajk#325]
A button in LayerSwitcher, next to layer's name, allows user to download the selected layer as KML.

**Comment by jacobwod** [comment]
Experimental feature needs to be enabled by editing `appConfig.json` and adding:
```javascript
  "experimentalDownloadLink": true
```

The result will be something like this:
![image](https://user-images.githubusercontent.com/110222/68584616-59f86f00-0480-11ea-8e7c-df12591315ba.png)

**Comment by victoraxbom** [comment]
Nice! Would be a nice addition if you also could upload and handle a kml in the layerswitcher. Like the import function in the draw plugin, but more accessible and integrated with the rest of the layers

**Comment by jacobwod** [comment]
I thought about import and think that the drag-and-drop interaction of OpenLayers is a good start. It supports KML among other formats. It's rather simple to implement (see [example](https://openlayers.org/en/latest/examples/drag-and-drop.html)), the only obstacle is how to integrate the imported layer into LayerSwitcher. Feel free to experiment! :)
