### ISSUE TITLE
LayerSwitcher - parent not checked when missing layer as child

### ISSUE THREAD

**Issue by FredrikEkstrom79** [hajkmap/Hajk#327]
When there is no layer directly under the parent the parent don't get cheched.
No layer as children (only groups as children)
![image](https://user-images.githubusercontent.com/50202826/68647969-7f888580-051f-11ea-8eea-e8c2dc55bc7b.png)
![image](https://user-images.githubusercontent.com/50202826/68647939-6a135b80-051f-11ea-994a-080943cfffe1.png)

With a layer as children (and groups)
Parent now get checked as expected and all the children
![image](https://user-images.githubusercontent.com/50202826/68648029-a941ac80-051f-11ea-8069-d12af2f6a78e.png)
![image](https://user-images.githubusercontent.com/50202826/68648036-ac3c9d00-051f-11ea-94c1-63c96a4e4a33.png)

**Comment by jacobwod** [comment]
An older issue, #283 describes this as well. Locking this thread, please continue discussion in #283.
