### ISSUE TITLE
Reduce default width/height for GetLegendGraphic request

### ISSUE THREAD

**Issue by jacobwod** [hajkmap/Hajk#329]
It seems that the legend that is requested by default is not well suited for most use cases in Hajk: the resulting image is often way too large, disproportianal to the surrounding text and UI elements :

![image](https://user-images.githubusercontent.com/110222/68858269-f458ec80-06e4-11ea-9d5d-b010eedb4f3c.png)

![image](https://user-images.githubusercontent.com/110222/68858282-fcb12780-06e4-11ea-9c5c-2970a429bba3.png)

I found that the value is (for some reason) hard coded in `ConfigMapper.js`:
```javascript
var w = 60;
var h = 60;
```

**I propose changing this to a smaller value, I've had good results by using 30 as w/h instead.** Opinions?

**Comment by FredrikEkstrom79** [comment]
Sounds good

**Comment by victoraxbom** [comment]
Isn’t it already possible for admin to adjust this with the legend options string? Doesn’t mean we can’t change the default anyway, your proposal with a smaller one looks good

**Comment by jacobwod** [comment]
I think these are different parameters. See that `60`s in the string below? That's what I'm thinking about. Legend options string is just the last parameter in query string, namely `legend_options`.

```
https://geoserverng.halmstad.se/geoserver/wms?REQUEST=GetLegendGraphic&VERSION=1.0.0&FORMAT=image/png&WIDTH=60&HEIGHT=60&LAYER=webbkarta:dpmap_byggnader_vy&STYLE=webbkarta:Byggnader_primarkartan_linje_vy&legend_options=fontName:Roboto;fontAntiAliasing:true;fontColor:0x333333;fontSize:14;dpi:90;forceLabels:on```

We'd like to commit a change with 30 as the new default.
