### ISSUE TITLE
Enable single tile requests for WMS 1.3.0

### ISSUE THREAD

**Issue by jacobwod** [hajkmap/Hajk#331]
Currently it is not possible to check the "single tile" checkbox in `admin` for WMS layers with 1.3.0 version. It's super simple to fix however, by removing this row:
```javascript
// In wmslayerform.jsx
disabled={this.state.version === "1.3.0"}
```
We've done it here and tested out by setting up some 1.3.0 layers as single tile. 

**We could not notice any problems with that setup.** So we wonder: what is the reason for disabling this option for 1.3.0? Note that there is no information on single tile request not being supported for 1.3.0 in any WMS specification.

**Comment by FredrikEkstrom79** [comment]
GeoServers preview allow it so there is no problem with WMS 1.3.0 and single tile

**Comment by jacobwod** [comment]
@sbk-linus ?

**Comment by victoraxbom** [comment]
I haven’t found any problems with single tile and 1.3.0. Maybe some problems with an earlier version of openlayers?

**Comment by jacobwod** [comment]
Perhaps. But as you say, it works fine now. We should change as proposed, and if somebody doesn't want to use it, just don't check `single tile` in your `admin`. I think it's better than disabling the option for everyone, right?

**Comment by victoraxbom** [comment]
I agree

**Comment by sbk-linus** [comment]
It was probably a temporary solution for a bug in OpenLayers. However, it seems to be working now and we should implement the fix as suggested.
