### ISSUE TITLE
Search in Hajk3 not showing all fields typed in admin

### ISSUE THREAD

**Issue by FredrikEkstrom79** [hajkmap/Hajk#333]
The search result only shows the first field when you have typed in more then one field to show
![bild](https://user-images.githubusercontent.com/50202826/69237118-38406b80-0b95-11ea-9db2-a7e7db8bf84e.png)
![bild](https://user-images.githubusercontent.com/50202826/69237176-5c03b180-0b95-11ea-8394-67cc2550c7e1.png)

In Hajk2 it worked fine
![bild](https://user-images.githubusercontent.com/50202826/69237366-d3d1dc00-0b95-11ea-96e7-4be71c8a5712.png)

**Comment by jacobwod** [comment]
In upcoming fix the fields are joined with ` ,`, just as they were in Hajk 2. As usual, this could be an option in admin, allowing for joining with other characters, such as white space or ` - `. But for now, I'm closing this as issue is solved.
