### ISSUE TITLE
Certain KML files can not be imported due to styling in files 

### ISSUE THREAD

**Issue by sweco-seljoo** [hajkmap/Hajk#334]
Some, not all, KML files is not possible to import and be drawn through the function "Import" in Draw plugin.  We have found that differences in how styling is defined in KML-files. Some tools may put "style" inline and som put them in separate elements.

**Steps to reproduce the behavior:**
1. Try to import the attached file 
[KML-Can-not-be-imported.txt](https://github.com/hajkmap/Hajk/files/3873893/KML-Can-not-be-imported.txt)

**Expected behavior**
Should be drawn as any other KML file that is imported.

**Proposal for solution**
We have found a simple code change in Plugin/draw/DrawModel.js that works. Its how feature.getStyleFuncion() is called.

**Comment by jacobwod** [comment]
Great! Since you already have a fix, can you make a pull request with it?
