### ISSUE TITLE
Can't get rid of one layer in `selectedSources` option for Search

### ISSUE THREAD

**Issue by jacobwod** [hajkmap/Hajk#338]
**Describe the bug**
No matter how I configure Search plugin, I can't get rid of one layer in the `selectedSources` option.

*Radius search deactivated, no sources selected:*
![Skärmavbild 2019-11-25 kl  11 29 10](https://user-images.githubusercontent.com/110222/69532909-18cf8700-0f77-11ea-86b0-2c8d55e360ed.png)

*Still there's one layer ID in the map config:*
![Skärmavbild 2019-11-25 kl  11 28 49](https://user-images.githubusercontent.com/110222/69532958-369cec00-0f77-11ea-88bb-848bfd74bfe1.png)

And that comes **from the PUT** request in `admin`, so it seems that admin writes stuff that aren't selected.
```
Förfrågan-URL:https://interntestkarta.halmstad.se/mapservice/settings/toolsettings?mapFile=jw.json
Förfråganmetod:PUT
Fjärradress:0.0.0.0:443
```

**Anyone else noticed that?**

**Comment by sweco-sesqqq** [comment]
Seems to be fixed in the new search-component

**Comment by jacobwod** [comment]
Ah! Didn't we just run into something like this yesterday? Can't remember exactly but I think it could be related…

**Comment by sweco-sesqqq** [comment]
We did! You couldn't get rid of the first layer in the map-object(?) layers-array. I don't remember fully either.

They might be related, but i think we checked this a while back and made sure everything worked as expected.
