### ISSUE TITLE
Error with GeoJSON vector layer

### ISSUE THREAD

**Issue by perosoderstrom** [hajkmap/Hajk#339]
**Describe the bug**
If you configure a GeoJSON vector layer in admin and add it to a map you get an error in client when you start the map.

**To Reproduce**
1. Add a GeoJSON vector layer in admin
2. Add that layer to a map
3. Open the map

**Screenshots**

![Geojson-issue](https://user-images.githubusercontent.com/51197693/69617578-b17a0b80-1038-11ea-8ba9-4852de2d55a5.PNG)

**Fix**
Edit in Hajk\new-client\src\models\layers\VectorLayer.js

![Geojson-issue-code](https://user-images.githubusercontent.com/51197693/69617638-c6ef3580-1038-11ea-8bb2-d959014b1f5a.PNG)

**Comment by jacobwod** [comment]
Closed by #348
