### ISSUE TITLE
Convert Preset from BaseWindowPlugin to a free float button, like MapSwitcher

### ISSUE THREAD

**Issue by jacobwod** [hajkmap/Hajk#340]
#336 closed #323

The current implementation does however display a Window. Another option would be to do something similar to MapSwitcher, see [this comment](https://github.com/hajkmap/Hajk/issues/159#issuecomment-549362117). It's a rather small fix to convert this `BaseWindowPlugin` to a free floating button below the zoom buttons, but the **question that remains is whether we want it to be free floating or a window based plugin?**

_Originally posted by @jacobwod in https://github.com/hajkmap/Hajk/issues/323#issuecomment-557533311_

Update 2019-11-26: We decided on changing the plugin from being BaseWindowPlugin-based to something more like MapSwitcher component is currently.

**Comment by perosoderstrom** [comment]
I can have a look at this, probably next week if it's ok.

**Comment by jacobwod** [comment]
Absolutely. I took a quick look and noticed that we will need to handle a special case here (similar to Search): AppModel renders all plugins that it finds, and in this case we don't want AppModel to render it, so it must be excluded. There are many ways to do it and I'm not done thinking about it yet. But an idea I had was to remove `target: footer` from Preset's options. (That's because AppModel looks for plugins that have `target==='left'|'right'|'toolbar'`.) 

I think this would be the right way, but it would require changes to Admin and MapService too.

So don't rush @perosoderstrom, but of course if you have time: feel free to take a look. 😄 I'll try to respond as soon as I can.

**Comment by perosoderstrom** [comment]
Shall it be only as free floating or, with an option in Admin, either BaseWindowPlugin or free floating? Either way I think both Admin and MapService needs to be changed. When I start I will start with the client so this decision can wait.

**Comment by jacobwod** [comment]
If you start asking the community, the usual answer you'll get is that "it would be nice if it's an option"… Sometimes it's better just not to ask. 😉 

But seriously, I think that if free floating button with dropdown is available, it would be the most used variant.

**Comment by perosoderstrom** [comment]
@jacobwod Should we convert this to a control in a similar way as the free floating Information plugin?

**Comment by jacobwod** [comment]
Hi @persoderstrom. Glad you already saw the Information control I committed earlier today. 😄 

Yes, I think that'd be the correct approach if we let go of the Drawer/Widget button completely (which I think we should – we can't have options for everything). 

I noticed it helps to work on the `admin` part when converting the plugin. You will want to add/remove properties in the `options` array of Preset (e.g. remove `target` which won't be used anymore). 

You can of course edit your map config by hand when developing and ask for help with fixing the `admin` part later on. 👍

**Comment by perosoderstrom** [comment]
I have converted the client to free floating. BaseWindow is not an option anymore ;-)

Next step will be Admin and MapService.

**Comment by jacobwod** [comment]
Great! Are you working in a branch? If you want to, I can take a look before you do the PR (pull request).

Admin needs changes, but I'm not certain you need to do anything in MapService. It seems as for tools, MapService writes whatever is sent in the `save()` function from each given tool. When you look inside a tool admin page (e.g. preset.jsx), you will see that you (unfortunately) have to change whatever is saved in three places:
1. `defaultState` variable
1. in constructor, when it sets `this.whatver`
1. in `save()`

**Comment by perosoderstrom** [comment]
I have pushed changes in client and admin to branch `preset-free-floatin-button`. I don't think Mapservice needs to be changed. In admin I commented out the obsolete code, so this, and for sure some more, has to be cleaned. The old plugin in new-client shall also be deleted. @jacobwod , Have a look and test it when you have time.

**Comment by jacobwod** [comment]
Great @persoderstrom. I've done and pushed some changes to the branch, and I think it's ready for PR towards `master` now.

**Comment by jacobwod** [comment]
@perosoderstrom I'll do the rebase from `master` and then PR if it's ok? There are some conflicts that I can take care of.

**Comment by perosoderstrom** [comment]
Please do, @jacobwod .

**Comment by jacobwod** [comment]
Done. Looking at the PR I was afraid that I somehow duplicated it all (commits appear twice). But in the end it seems that we've got all needed changes and conflict fixes, so it should all be in `master` now. 

Well done, @perosoderstrom!
