### ISSUE TITLE
Add option to also include layers in preset plugin

### ISSUE THREAD

**Issue by victoraxbom** [hajkmap/Hajk#342]
As now the preset plugin supports zoom to a specified coordinate. It would be a great addition if it also, if set up by the admin, could turn on preset layers. 

This could as an example be used if you would lika a slim map with just a few layer configurations preset.

**Comment by perosoderstrom** [comment]
Does not [Dela / Länk till kartan](https://github.com/hajkmap/Hajk/wiki/Anv%C3%A4ndardokumentation-HAJK3-L%C3%A4nk-till-kartan) solve this?

**Comment by victoraxbom** [comment]
The idea was that this would be more like the map switcher except that you don't need to configure multiple maps with their own config. But might just end up with a lot of duplicate similiar functionality in different plugins

**Comment by perosoderstrom** [comment]
I can see the use of that. An even simpler map switcher where you can switch the content of the current map and still have all the layers and tools available. Could perhaps be used for some of Kungsbackas internal theme maps?

**Comment by jacobwod** [comment]
It _could_ end up being similar in functionality to already existing plugins, sure. But I can also see why we'd want Preset to change layers. 

I would like to implement it in a way that does not collide with current behavior of Preset. So, if a preset link lacks the `l`-parameter, we don't touch layers at all - whatever is on is on. But if, for example, `l=4,201,422`, then we will turn off all layers other then the specified ones and turn on only 4, 201 and 422. **Now the best part:** if we supply an empty `l=`, this will be translated by Preset as "hide all layers other then [empty], show only [empty]", so we can ensure that everything is switched off (if that's what we want, as admins). Opinions?

**Comment by victoraxbom** [comment]
@perosoderstrom Could for sure be an alternative for some of the theme maps! 

@jacobwod Sounds lika a good implementation. 
Some indication should be given to the user that all layers will be switch off in case the preset link use the last part with an empty `l=`.

**Comment by linusfj** [comment]
What's left to do is adding functionality to turn on layers from the `l`-parameter.
