### ISSUE TITLE
Problem if getCapabilities-url and getMap-url differs

### ISSUE THREAD

**Issue by perosoderstrom** [hajkmap/Hajk#345]
In layer admin you write the url to a getCapabilities service from which you get a list of layers. 
Hajk then assumes that the getMap-url for a layer is ths same as the getCapablilties url, but that is not allways the case.

An example from SGU:
Url in admin: `https://resource.sgu.se/service/wms/130/brunnar`

sends the request: `https://resource.sgu.se/service/wms/130/brunnar?service=WMS&request=GetCapabilities&version=1.3.0`

which gives a different Url to getMap: `<OnlineResource xlink:type="simple" xlink:href="http://maps3.sgu.se:80/geoserver/ows?SERVICE=WMS&"/>`

and it is this getMap-url Hajk should use for the layer.

**Describe the solution you'd like**
Hajk should handle different url's for getCapablities and getMap.

**Comment by jacobwod** [comment]
## Intro
Well, this is interesting. I have no idea why this was done like that, but it seems to have been this way "always". Anyway, we should absolutely correct it. 

The place to do that would be in Admin UI (that's where we call `GetCapabilities`) and where we create our `layer` object that has an `url` property. That property equals to – as you've noted – whatever is in the URL field that we've filled in to request the capabilities:
![Skärmavbild 2021-11-04 kl  10 38 19](https://user-images.githubusercontent.com/110222/140291242-ea94a1e3-6da9-4557-8f98-d10f2f475210.png)

**So yes, the first part of the URL used in Client UI for `Request=GetMap` will essentially be equal to whatever we've entered to `Request=GetCapabilities` in the first place. That's not right.**

But, it works for a lot of cases. 

We could grab the URL from the value of `OnlineResource` that we get from `GetCapabilities`. That would be more standard-compliant. 

But that will lead to a lot of issues that some of us might not be aware of right now. 

## The problem
A lot of setups run behind proxies and load balancers. The actual WMS service might be running deep down on some obscure port on some machine that's not aware of the proxy in front of it (why should it be?!). So here's an example: I can access the `GetCapabilities` on `example.com`, and I happen to know that I also can access `GetMap` on the same URL. _If we'd use the value that comes from the WMS response, however, I'm pretty certain there wouldn't be any map to show._ Take a look at this:
![Skärmavbild 2021-11-04 kl  10 35 23](https://user-images.githubusercontent.com/110222/140292045-ffa08da6-999f-42f1-9e07-45c3869aef7b.png)

This example comes from QGIS Server which runs _somewhere_ (and I don't actually care), but I know where it's exposed to the outside world. The service itself doesn't know that and thinks that "you can reach me at `localhost`".

## A possible solution
I think that I could control the value given by QGIS Server by typing my actual URL into this field:
![Skärmavbild 2021-11-04 kl  10 36 20](https://user-images.githubusercontent.com/110222/140292360-f54211db-0920-43e8-94c8-4dc6cb1a49ae.png)

But I'd run into problems when I want to expose the same WMS instance behind different proxies. This is an actual use case for us: we have `a.example.com`, `b.example.com` and `c.example.com`. They all use the same GeoServers underneath, but they're exposed on different subdomains to avoid CORS problems. So I have Hajk on `a.example.com`, and it's corresponding GeoServer can be reached on `a.example.com/geoserver`. All the layers in this setup are read from `a.example.com/geoserver/wms`. This wouldn't work if I'd set some _advertised URL_ in GeoServer, as **I would be forced to pick just one of the subdomains**. 

I feel that we must be very careful with introducing this kind of change. I'd like to hear your opinions, @perosoderstrom , @WCarlsson, @Hallbergs?

**Comment by perosoderstrom** [comment]
A simple way to solve this might be to add an extra field for getMap URL ("_getMap-URL om annan än Url*_"). If you run into this problem you would at least have a way to configure a separate getMap URL. Maybe the _OnlineResource_ can be exposed in admin as a (good!) hint.

This will leave it to the admin to enter a proper, working URL. 

If the getMap URL is empty, use the GetCapabilities URL.

**Comment by Hallbergs** [comment]
Very interesting indeed. I agree that we should be very careful when dealing with this, many (including me) got their geoservers behind proxies as you say @jacobwod. @perosoderstrom Your solution feels like a safe way to get a simple fix out for the users dealing with this issue.

**Comment by perosoderstrom** [comment]
As it is a rare problem a simple solution is sufficient. 
And it is allways the admins responsibility to get a correct URL.

**Comment by jacobwod** [comment]
I like it too, @perosoderstrom. I propose we decide that we will implement it like this. Perhaps with some aid for the admin (we could read `OnlineResource` from GetCapabilities, and have a checkbox next to a pre-filled text field, that would override the URL). 

I'm in the middle of some backend work however, so it won't be fixed right away by me. If anyone else has time to take a look - feel free to do that. 👍

**Comment by WCarlsson** [comment]
@Hallbergs did you have time to look at this?

**Comment by Hallbergs** [comment]
Done @WCarlsson

**Comment by Hallbergs** [comment]
The fix only applies to WMS-layers. I hope this is enough. The fix is currently in develop and will be released in 3.9.
