### ISSUE TITLE
Notistack from Coordinate doesn't disappear after user clicks in map

### ISSUE THREAD

**Issue by jacobwod** [hajkmap/Hajk#352]
Seems like an issue related to #308 has surfaced. 

![bild](https://user-images.githubusercontent.com/110222/69803444-7adcf600-11dc-11ea-97d3-ec3722f675df.png)

**Comment by jacobwod** [comment]
Perhaps not a problem on desktop (and I can see why we want this box to be visible as long as the tool is active). Nevertheless it becomes problematic in mobile viewports:

![bild](https://user-images.githubusercontent.com/110222/69805296-ad88ed80-11e0-11ea-8b6c-3dbd5da720af.png)

We can solve this in a number of ways:
1. Hide the blue box after the first click.
  1.1 But user won't know if the tool is still active or not - can be misleading.
1. Show the blue box on screen `bottom` instead of `top`, at least for small screens.
  2.1 Can break some UX standards from Material?
1. Leave some space free above the Window, even on small screens. 
  3.1 But then, how much space should we leave? This certain phrase happens to take up just one row, but what happens if we show a longer message? Then the blue box will overlap on Window on mobile screens, and we have the same issue as in the screenshot.

**Comment by sbk-linus** [comment]
Another alternative is to add a **close button** to the snackbar message. By doing this, we can almost assume the user have read the message before closing it.

**Comment by jacobwod** [comment]
Sure, we can try that. I'm afraid thought that it'll still be a bit confusing, especially in mobile. If you click on 'Close', does that mean that only the snackar closes, or is the "click to get coordinates"-function closed too? 

What about option 2 in my first message, would that require more work than adding a button? Either way, try and see – especially on mobiles – which one feels best.
