### ISSUE TITLE
Problem using recursiveADsearch in Web.config

### ISSUE THREAD

**Issue by maan002** [hajkmap/Hajk#366]
To support AD-Groups in AD-Groups (i.e. nested AD-Groups) one should be able to change the parameter `recursiveADsearch` in Web.config from "false" to "true".

Doing this will result in error:
`System.DirectoryServices.AccountManagement.PrincipalOperationException: While trying to retrieve the authorization groups, an error (5) occurred.`
It's the method `GetAuthorizationGroups()` that generates the error.

The most relevant information found so far is:
https://stackoverflow.com/questions/26849669/why-might-userprincipal-getauthorizationgroups-fail-for-one-principal-but-not

**Comment by varberg** [comment]
This probably depends on the rights the configured user has in the AD.

**Comment by jacobwod** [comment]
Is this something you intend to fix or can we close it?
