### ISSUE TITLE
Add a Rotate Control to Map that rotates the View back to default (North is up)

### ISSUE THREAD

**Issue by FatemeHosseini** [hajkmap/Hajk#368]
**Om man jobbar i mobil, ipad eller touch-skärm, kan rotera i kartan**
Det behövs en plugin (som en knapp) som roterar tillbaka så att norr är upp i kartan. 
OnClick -> norr-upp

![image](https://user-images.githubusercontent.com/36195301/70522667-dc3c8780-1b41-11ea-9c3f-13698123b6bb.png)

**En förbättring är om  ikonen kan rotera när man roterar i kartan så att man ser vilket håll är norr**
![image](https://user-images.githubusercontent.com/36195301/70523120-a21fb580-1b42-11ea-91de-e6fd9c381f2c.png)

**Comment by jacobwod** [comment]
Whoever wants to implement this: try to follow the same approach as in `src/controls/Zoom.js`. There is a built-in OL Contorl, `ol/control/Rotate` that solves this. But simply activating it in `AppModel.js` would render a Component slightly different from our existing buttons (which are built with Material UI). So please see how Zoom is done and try to follow the same approach for Rotate.

**Comment by jacobwod** [comment]
I'm done with this one. Not sure about the icon however. Input on icon choice for this (as well as other Controls and Plugins) is welcome. **Make sure to pick something from https://material-ui.com/components/material-icons/.**
