### ISSUE TITLE
Add a separator to entities in Attribution

### ISSUE THREAD

**Issue by jacobwod** [hajkmap/Hajk#370]
Multiple entries in the Attribution control should be separated with a comma character instead of whitespace, as they are currently:
<img width="252" alt="bild" src="https://user-images.githubusercontent.com/110222/70604389-e9687d80-1bf8-11ea-85cc-0bcccf8fd5c0.png">

**Comment by jacobwod** [comment]
I thought this would be easy, but I can't find any delimiter/separator parameter for the Attribution control: https://openlayers.org/en/latest/apidoc/module-ol_control_Attribution-Attribution.html. It looks as old versions of OpenLayers had this (see this docs for OL 2: http://dev.openlayers.org/docs/files/OpenLayers/Control/Attribution-js.html#OpenLayers.Control.Attribution.separator) but now it's nowhere to be found. Any clues?

**Comment by Ducarouge** [comment]
In the latest version of openlayers the attributions separator is set in .CSS :
```
.ol-attribution li:not(:last-child):after {
  content: ", ";
}
```

**Comment by jacobwod** [comment]
Fantastic @Ducarouge, thank you for help with closing this long-standing issue!

![Skärmavbild 2021-03-04 kl  14 43 49](https://user-images.githubusercontent.com/110222/109972972-220dde80-7cf8-11eb-83d0-76c84e276120.png)
