### ISSUE TITLE
Edit plugin: `geom` isn't written to correct column when inserting new features to WFS-T

### ISSUE THREAD

**Issue by jacobwod** [hajkmap/Hajk#372]
When I want to add a new point using the Edit plugin, I can not get Hajk to write the `geom` column. 

I narrowed down the bug by sending test POST requests.

I have a PostGIS table with the following structure:
```sql
CREATE TABLE public."myTest"
(
    id integer NOT NULL DEFAULT nextval('"myTest_id_seq"'::regclass),
    freetext character varying COLLATE pg_catalog."default",
    geom geometry(Point,3008),
    CONSTRAINT "myTest_pkey" PRIMARY KEY (id)
)
```

Good enough. Now, when I want to add a point in Hajk, the following requst is sent:
```xml
<Transaction xmlns="http://www.opengis.net/wfs" service="WFS" version="1.1.0" xsi:schemaLocation="http://www.opengis.net/wfs http://schemas.opengis.net/wfs/1.1.0/wfs.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <Insert>
        <myTest xmlns="http://karta.halmstad.se/geoservertest">
            <geometry>
                <Point xmlns="http://www.opengis.net/gml" srsName="EPSG:3008">
                    <pos srsDimension="2">118142.41171358005 6298177.226006613</pos>
                </Point>
            </geometry>
            <freetext>Some text</freetext>
        </myTest>
    </Insert>
</Transaction>
```

So the `freetext` column is written, but `geom` is empty after such an `Insert`. 

**I figured that it's kind of strange that Hajk writes to `geometry` instead of `geom`, as the column is called `geom` in DB. So I re-sent the POST request with following body:**

```xml
<Transaction xmlns="http://www.opengis.net/wfs" service="WFS" version="1.1.0" xsi:schemaLocation="http://www.opengis.net/wfs http://schemas.opengis.net/wfs/1.1.0/wfs.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <Insert>
        <myTest xmlns="http://karta.halmstad.se/geoservertest">
            <geom>
                <Point xmlns="http://www.opengis.net/gml" srsName="EPSG:3008">
                    <pos srsDimension="2">118142.41171358005 6298177.226006613</pos>
                </Point>
            </geom>
            <freetext>Some text</freetext>
        </myTest>
    </Insert>
</Transaction>
```

**And that POST resulted in a correctly inserted row, including `geom`.**

**Comment by jacobwod** [comment]
Found the reason in OpenLayer's docs:
> Get the name of the feature's default geometry. By default, the default `geometry` is named geometry.

**Comment by jacobwod** [comment]
This is a bit counterintuitive: it looks as geometryName is actually being read. We do an attempt when the table data is loaded, and we take a look at the _first_ row. That first row's geometryName is then being used to setGeometryName for the new features that will be written.

```javascript
loadDataSuccess = data => {
    var format = new WFS();
    var features;
    try {
      features = format.readFeatures(data);
    } catch (e) { }
    if (features.length > 0) {
      this.geometryName = features[0].getGeometryName();
    }
```

So what happened to me earlier was that **there were no entries in the table, so `features.length` was 0, and the default Open Layers' geometryName (`geometry`) was used**, whereas my table didn't contain any column with that name.

**Is this a problem? Should we expect users to have data inside the table already? Or should we edit `admin` so there is a possibility to specify another default geometry name, in case no rows are found?**

**Comment by victoraxbom** [comment]
That explains why `geom` as geometryname works for us, we already have some entries in our tables. The best solution would propably be to let the admin set the default column. Anyway we should add a note about this in the documentation

**Comment by jacobwod** [comment]
Great that you've documented this already.

Yes, I thought briefly about adding this as an option in admin. But another quick fix would be to default to `geom` – which seems to be default both for PostGIS, FME (at least when writing data to PostGIS) and QGIS (via WFS to GeoServer). Seems like there's more consensus for `geom` than for OL's choice, `geometry`.

**Comment by jacobwod** [comment]
BTW, I ran into some issues when I defined some other data types in PostGIS:

`int`, `number` and `date` seem to be handled somehow, but `boolean` is not. I thought that something like <div field="myBooleanField" label="Do you agree?"></div> would render a checkbox, but it didn't. 

I saw that you've documented some types in Wiki for the Edit plugin. Do you perhaps have any idea how to create checkboxes in Collector as well? As I read the code, it seems that `flerval` is somehow transformed to an `<input type="checkbox">`. But `flerval` requires the database data type to be `string`, which is a bit counterintuitive – normally you'd expect `boolean` there.

**Comment by victoraxbom** [comment]
To change default to `geom` would be a good quick fix. 

`flerval` renders as you said checkboxes. The chosen alternatives is then concenated to a string with `,` as delimiter. I wouldn't restrict this to only `boolean` fields as you possibly want to have more alternatives then just true or false. For an example, we use it like this in Collector:

![image](https://user-images.githubusercontent.com/3994163/70782496-6164ae00-1d87-11ea-9f97-a9fa39a06d21.png)


But if you have `boolean` as data field, you should be able to use checkbox or even drop-list (with yes or no) as alternative. And default to checkbox maybe?

**Comment by jacobwod** [comment]
Ah, that's how `flerval` is supposed to be used. Thanks for the clarification.

Yes, my (mistaken) understanding of it was that it renders just one checkbox at time, hence I thought that `boolean` would do as data type. But now I understand why it's `text`. We'll keep it this way.
