### ISSUE TITLE
Search component: Limit WFS sources if s-param is present

### ISSUE THREAD

**Issue by jacobwod** [hajkmap/Hajk#373]
**Left to do:** 
* Limit WFS sources if s-param is present

---
Similary to how it works in Hajk2, we should **read the `s` and `v` parameters**. 

If `s` is not null, the value of `s` will be used to limit which WFS search service (configured in admin) is being search. 

The value of `v` is simply the search phrase. 

If `s` is falsy, but `v` exists, the search should happen for all defined WFS search sources `filter=*`.

**Comment by sweco-sesqqq** [comment]
This feature is pushed to master. Query-params are s for sources and q for searchString
