### ISSUE TITLE
Infoclick doesn't always mark features as selected

### ISSUE THREAD

**Issue by jacobwod** [hajkmap/Hajk#399]
**Update 2020-02-05: this seems quite serious, see [comment below](https://github.com/hajkmap/Hajk/issues/399#issuecomment-582315931).**

It seems as features with `type === 'MultiPolygon'` or `'MultiPoint'` don't the usual styling when clicked and selected in Infoclick: 
![bild](https://user-images.githubusercontent.com/110222/73449325-2fbd9b80-4363-11ea-8197-af8458e97942.png)

The correct behavior is to show which feature has been selected by adding a stroke to the feature, like this:
![bild](https://user-images.githubusercontent.com/110222/73449366-482db600-4363-11ea-9832-2160aed22afd.png)

**For now I can only see this occur for features with those previously mentioned types.** 
![bild](https://user-images.githubusercontent.com/110222/73449421-685d7500-4363-11ea-9ea9-8a9b14cead21.png)

**Comment by FredrikEkstrom79** [comment]
Other layers with MultiPolygon works so that is not the problem with this layer.

**Comment by FredrikEkstrom79** [comment]
If the layer is in EPSG:3008 but is set to EPSG:3006 in admin this problem will happen so this is not a problem with Hajk, just i miss in configuration as it seems.

**Comment by jacobwod** [comment]
**So basically, if someone has this problem: make sure that you have set the correct projection in `admin`.**

**Comment by FredrikEkstrom79** [comment]
After little more testing it seems more like you have to set the maps coordinate system on the layer even if it's not the right one for the layer. The layer will show up in the right place on the map but this seems wrong.

This layer is in EPSG:3006 (setting it right in admin makes the layer not being marked)
![image](https://user-images.githubusercontent.com/50202826/73827994-cc1eec80-4800-11ea-8b26-9edf4215f710.png)
![image](https://user-images.githubusercontent.com/50202826/73828086-f53f7d00-4800-11ea-8450-ff4b98b3b1bd.png)
Changing to the maps EPSG:3008 on the layer in admin makes it to be marked
![image](https://user-images.githubusercontent.com/50202826/73828306-49e2f800-4801-11ea-94ed-ee559b6424c9.png)
![image](https://user-images.githubusercontent.com/50202826/73828267-39cb1880-4801-11ea-8aa0-be401f90f304.png)

So this seems to be a bug/problem in Hajk when selecting layers not in the same coordinate system that the maps has.

**Comment by jacobwod** [comment]
Stale, closing.
