### ISSUE TITLE
Transparency slider is inverted

### ISSUE THREAD

**Issue by FredrikEkstrom79** [hajkmap/Hajk#404]
The slider is inverted when setting transparency on a layer Right to Left
![image](https://user-images.githubusercontent.com/50202826/73832342-4868fe00-4808-11ea-8fe4-fdebb7c9ce48.png)
![image](https://user-images.githubusercontent.com/50202826/73832438-74847f00-4808-11ea-8bb9-e3858ec225b3.png)

All other program set the value from Left (0%) to Right (100%)

**Comment by victoraxbom** [comment]
I agree, either you could call it opacity or transparancy but for both it usally starts with 0% to the left and 100% to the right. When using opacity it should be fully visible and start at 100%. 
But I do think transparancy is a term more known to people

**Comment by jacobwod** [comment]
Stale, new LS is in workings.
