### ISSUE TITLE
Söka i lagerhanterare

### ISSUE THREAD

**Issue by FatemeHosseini** [hajkmap/Hajk#407]
### **Att kunna söka på allt som visas i lagerhanteraren**
Att kunna söka på allt som visas i lagerhanteraren, söka på lagernamn, metadata, andra beskrivningar. Man ska kunna välja alternativ att söka även i metadatabanken och få resultatet i en separat panel i hajk (kanske en som inforutan)

**Comment by jacobwod** [comment]
Somehow a duplicate of #195.
