### ISSUE TITLE
Exportera sökresultatet till Excell

### ISSUE THREAD

**Issue by FatemeHosseini** [hajkmap/Hajk#411]
**Att kunna exportera sökresultatets attributlista till en Excel-fil.**
Funktionen finns redan i Hajk2, Hajk3:s client ska utvecklas.

**Befintliga buggar i Hajk2**

1. om wms:ens attribut har empty eller NULL flyttas grannes cells värde i den cellen som är empty eller NULL
2. Problem med att exportera till excell även när det finns special tecken

**Comment by persoderstrom** [comment]
This will be solved in new search plugin.

**Comment by Hallbergs** [comment]
Closed by b3ebeca42464f4d81ecb16b41857979f88638897
