### ISSUE TITLE
Edit features symbology and text in draw-plugin

### ISSUE THREAD

**Issue by victoraxbom** [hajkmap/Hajk#412]
The draw plugin supports editing of already created features. It is though limited to editing the geometry of the features. The draw-plugin should also support editing the color, symbol and text of existing features.

**Comment by jacobwod** [comment]
Just to clarify: this is not related to the Edit plugin? Instead you think of the situation where a user imports geometries from KML, and wishes to edit them, right?

**Comment by victoraxbom** [comment]
Yes thats right, this is not related to the edit-plugin. We have had some users who wish to edit their already drawn features (or imported features) in the draw-plugin
