### ISSUE TITLE
Links to chapters in document don't show up in Layerswitcher or Breadcrums

### ISSUE THREAD

**Issue by ingvar-uddevalla** [hajkmap/Hajk#419]
Links to chapters in document (i.e ÖP) don't show up neither in Layerswitcher nor in Breadcrums (Hajk 3.1 and later). The opposite direction, which means links from chapters in a document to layers in a map, works fine. I have checked to create a new map and a new documents, but of no success. It would be greatful if anybody could check this in their own Hajk 3.1 environment. Everything worked perfect in our own old Hajk 3.0 environment  as shown in the pictures below.
![LayerSwitcher_Dokumentlänkar_3 0](https://user-images.githubusercontent.com/54808837/74230483-be67dc00-4cc4-11ea-8c84-8c595f1747a3.PNG)
![Breadcrumbs_3 0](https://user-images.githubusercontent.com/54808837/74230488-c32c9000-4cc4-11ea-8eac-d49ece3c01a2.PNG)

**Comment by jacobwod** [comment]
I tried to recreate this but couldn't get the problem you're referring to. Links in both Breadcrumbs and LayerSwitcher work correctly and open up the connected chapter in Document window. I'm sorry about the low image resolution, but please see my short video below:

![Kapture 2020-02-11 at 13 36 44](https://user-images.githubusercontent.com/110222/74237415-cc712900-4cd3-11ea-92e1-921ed768b07c.gif)

**Comment by ingvar-uddevalla** [comment]
Thanks @jacobwod . It seems that my problems are caused by failures from my environment, and not from the 3.1 release. So far so good. I've checked the few error-reports given in the DevTools, but they can't help me forward. I tried to change the configuration for Informative by adding the name of JSON file (as you had to do), but then I got new errors affecting the whole client-application. I will  continue to check and hopefully learn me more. Right now I have other problems with starting the Beta-version, because of lack of backend-code from github not being added to my environment.

**Comment by jacobwod** [comment]
I'll be releasing 3.2 soon, which will include a new, pre-compiled, backend. That'll hopefully solve your new problems. 

Regarding Informative errors, you can always paste the messages you get in DevTools here and I'll take a look.

**Comment by ingvar-uddevalla** [comment]
I've finally found the problem (I believe). We now have 3.2 installed and with trial and error I got some of the links to show up. The links shown up are only from the last chapter. It seems like the layerswitcher class Component BreadCrumb (in BreadCrumb.js) only stores the last layers-array (see the picture below) and not the previous ones. Or is this a result from the mapsettings in the Informative Admin Tool?
![BreadCrumb-json-fel](https://user-images.githubusercontent.com/54808837/77182720-7c089a80-6acd-11ea-84d3-761e5a1c5161.png)

**Comment by ingvar-uddevalla** [comment]
Hej Jacob,

Tack, jättebra att du öppnade den. Jag såg nu att den blivit stängd – jag måste ha gjort detta av misstag då jag var inne och skrev om den i fredags. Den ska förstås var öppen, eftersom den inte är löst ännu 😊

/Ingvar
Från: Jacob Wodzyński <notifications@github.com>
Skickat: den 23 mars 2020 12:51
Till: hajkmap/Hajk <Hajk@noreply.github.com>
Kopia: Ingvar Petersson <Ingvar.Petersson@uddevalla.se>; State change <state_change@noreply.github.com>
Ämne: Re: [hajkmap/Hajk] Links to chapters in document don't show up in Layerswitcher or Breadcrums (#419)


Reopened #419<https://github.com/hajkmap/Hajk/issues/419>.

**Comment by jacobwod** [comment]
I don't see any attempts to do something about this. Considering we'll soon migrate to `DocumentHandler`, I'm closing this `Informative`-specific issue.

**Comment by ingvar-uddevalla** [comment]
Hej Jacob

Helt okej.

Vi kommer att få hjälp av Sweco inom de närmaste med en total ominstallation av Hajk hos oss – och med den senaste masterkoden.
Då är säkert problemet eliminerat ändå. Vi använder heller inte Breadcrumbs i ÖP:n längre – det var ”kul” ett tag - men vi tyckte breadcrumbs tog för mycket plats i den mobila applikationen 😊

// Ingvar

Från: Jacob Wodzyński ***@***.***>
Skickat: den 18 mars 2021 08:19
Till: hajkmap/Hajk ***@***.***>
Kopia: Ingvar Petersson ***@***.***>; State change ***@***.***>
Ämne: Re: [hajkmap/Hajk] Links to chapters in document don't show up in Layerswitcher or Breadcrums (#419)


I don't see any attempts to do something about this. Considering we'll soon migrate to DocumentHandler, I'm closing this Informative-specific issue.
