### ISSUE TITLE
Checkbox disappears when checked in default map

### ISSUE THREAD

**Issue by FredrikEkstrom79** [hajkmap/Hajk#447]
When checking a checkbox it will disappear
![image](https://user-images.githubusercontent.com/50202826/75857378-6ff6ba80-5df6-11ea-9f97-7c2bd76c3990.png)
![image](https://user-images.githubusercontent.com/50202826/75857417-7d13a980-5df6-11ea-91f9-cbd7ff51b94f.png)

The secondary color "Komplementfärg" can not be white by default

**Comment by jacobwod** [comment]
This is pretty much fixed as of €448, right @FredrikEkstrom79?

**Comment by FredrikEkstrom79** [comment]
Yes it is
