### ISSUE TITLE
Client base print may result in unsharp/blured vector layers

### ISSUE THREAD

**Issue by FredrikEkstrom79** [hajkmap/Hajk#462]
Trying to print in high dpi settings (300) sometimes result in blured vector layers i pdf.
![image](https://user-images.githubusercontent.com/50202826/76413503-d602b500-6395-11ea-9a52-b2993b682f82.png)

**Comment by FredrikEkstrom79** [comment]
This might just be a problem with one of our geoservers not responding on request

**Comment by jacobwod** [comment]
We need to investigate. Seems like there's a limit on DPI output (I'm sure it's configurable), and at least our GeoServer doesn't return expected results when DPI is set to 300 in the tool. 72 and 150 seem to render fine.

**Comment by jacobwod** [comment]
[DPI 72.pdf](https://github.com/hajkmap/Hajk/files/4323306/DPI.72.pdf)
[DPI 150.pdf](https://github.com/hajkmap/Hajk/files/4323309/DPI.150.pdf)
[DPI 300.pdf](https://github.com/hajkmap/Hajk/files/4323308/DPI.300.pdf)

**Comment by jacobwod** [comment]
I belive I got it. 

However, I'm not sure there's much we can do inside the code to prevent this from happening.

**It seems that only _single tile layers_ are effected.** After some investigation I finally came so far that I got this message from our WMS (GeoServer):

```
 Rendering request would use 152997KB, whilst the maximum memory allowed is 131072KB 
```

It seems natural that rendering a, say, 6000x4000 px image needs more memory than rendering 50 256x256 px tiles. So what I think is happing is following:
1. Hajk loads a single tile layer in "normal" resolution when user clicks the map. Now the layer is visible.
2. User makes print settings and clicks on "Print"
3. Hajk calculates resolution etc and sets them accordingly in OpenLayers. 
4. OpenLayers re-renders size of canvas. **All existing layers are stretched out on the bigger canvas temporarily, until loading new layers is completed.**
5. Upon loading new layers, OpenLayers replaces the previous image of a layer with the new, hi res one. 

So what I happens is that **if loading the hi res single tile fails for some reason (such as out-of-memory on GeoServer), the older representation of layer that was stretched out, remains in place** which of course results in blurry image.

**Comment by jacobwod** [comment]
I changed the max render memory value to 0.5 GB (500000 KB) and now it seems to render pretty much everything.

**Comment by jacobwod** [comment]
@FredrikEkstrom79 I propose that we add a message (in `admin`) that clarifies this and reminded administrators to check their WMS settings. Can you add it to `admin` and close this issue?

**Comment by FredrikEkstrom79** [comment]
I can add it to admin
