### ISSUE TITLE
Error when loading map if the user is not allowed to due to AD-rights

### ISSUE THREAD

**Issue by maan002** [hajkmap/Hajk#463]
**Describe the bug**
1. The default map is set up to only be available to users with specific AD-Groups
2. A user that does not have that AD-Group tries to start Hajk3.
3. The user will get an error message saying that "TypeError: data.wfslayers is undefined"

**Solution**
Display a message that informs the user of the cause. The message should be configurable.

**Comment by jacobwod** [comment]
I'll take a look into this and the PR #464 today.
