### ISSUE TITLE
Possibility to restrict zoom only to set resolutions

### ISSUE THREAD

**Issue by victoraxbom** [hajkmap/Hajk#476]
When zooming in the map, it is sometimes possible to end up on a scale or zoom level in between the set resolutions in config. This can lead to cached maps look a bit blurred when the map has to scale up tiles. 

The constrainResolutions option on ol.View solves this by restricting zooming only to the resolutions set on the map. This option should be possible to set in admin

**Comment by jacobwod** [comment]
Closed by #477.
