### ISSUE TITLE
Improve Coordinates plugin - allow users to enter coordinate

### ISSUE THREAD

**Issue by jacobwod** [hajkmap/Hajk#482]
Currently the Coordinate plugin allows user to click anywhere on the map and displays coordinates for the click point in different (admin-defined) projections:
<img width="408" alt="Skärmavbild 2020-03-27 kl  08 41 44" src="https://user-images.githubusercontent.com/110222/77733432-2a00d100-7007-11ea-803f-2dff5b6c1b5e.png">

There are cases where user needs to enter coordinates by hand into the input boxes and transform between different projections. **Therefore it would be a great enhancement if the input boxes, that currently are read-only, allowed (well…) input too.**

Part 2: We've also had requests about showing the coordinate `onMouseMove` and not just `onMouseClick`.

**Comment by jacobwod** [comment]
@sbk-linus Can you estimate how much work would be needed for this?

**Comment by hitomin21** [comment]
I will update the coordinates tool to have the same functionality as in Hajk2 so I will add so the user can input values.

I have added so it is possible to modify the input fields and marker as well as other fields are updated accordingly.

I would also like to add buttons at the bottom:
Zooma -> Centers on written coordinate and zooms in
Panorera -> Centers on written coordinate
Clear -> Removes the marker

Please let me know if anyone has feedback regarding this.

**Comment by jacobwod** [comment]
@hitomin21 Sounds good, please remember to develop this feature in a separate branch, and send a PR when you're done about merging it into `master`.

**Comment by hitomin21** [comment]
I am working with this in the branch https://github.com/hajkmap/Hajk/tree/updatecoord/vbg

**Comment by hitomin21** [comment]
I will add some more improvements for this tool and corresponding configurations.

Users have reported that sometimes several digits are being deleted although only one should have been deleted.

Add a my location button to allow users to see the coordinates of their current position

Buggfix on number of decimals

Number formatting 1000 -> 1 000

The default view shows all the input fields directly so the user does not have to click somewhere in order to specify a coordinate

A button for reseting the fields

**Comment by jacobwod** [comment]
Go on @hitomin21. Make sure to keep your feature branch up-to-date with latest development in `develop`. When you're done, make a PR to `develop`.

**Comment by hitomin21** [comment]
Working on branch 
https://github.com/hajkmap/Hajk/compare/feature/482-improved-coordinates

**Comment by hitomin21** [comment]
Merged into develop

**Comment by jacobwod** [comment]
@hitomin21 We usually close the issue once the corresponding code has been merged into `master`, so there's no need to manually close after merge to `develop`. I'll leave it for now though, but it's good to know the next time. Thanks!
