### ISSUE TITLE
Add one more way to render plugin buttons: Control

### ISSUE THREAD

**Issue by jacobwod** [hajkmap/Hajk#521]
Currently Hajk's plugins can be rendered either as toolbar buttons:
![Skärmavbild 2020-06-01 kl  11 30 29](https://user-images.githubusercontent.com/110222/83395863-4ea86900-a3fb-11ea-952d-3b59f8ee8671.png)

Or widget buttons:
![Skärmavbild 2020-06-01 kl  11 29 12](https://user-images.githubusercontent.com/110222/83395824-418b7a00-a3fb-11ea-80a4-60e07c36303d.png)

The first option is the default, while the other (widget) is mainly intended for simple maps with a few active tools. The Widget contains an icon, a title and a short description of functionality and is thus ideal for maps where we expect a lot of new users or user that rarely use web mapping applications.

**What we currently miss is however a way to allow frequent users to access certain plugins with easy, without taking up a lot of screen estate.** This can be solved by allowing another `target` for plugins, `control`, and placing the button that activates the plugin together with other map controls (perhaps below Zoom buttons).

**Comment by jacobwod** [comment]
Here's a proposed solution:
![Skärmavbild 2020-06-01 kl  11 40 56](https://user-images.githubusercontent.com/110222/83396794-d04cc680-a3fc-11ea-9e82-b285e9a4ef16.png)

And bigger view of the same:
![Skärmavbild 2020-06-01 kl  11 41 41](https://user-images.githubusercontent.com/110222/83396835-de9ae280-a3fc-11ea-9f2c-73bc164c8c17.png)

**Comment by FredrikEkstrom79** [comment]
Or you can make the toolbar have two stage for hiding, one where the labels hides and one where all i hidden. I think a mockup hade this
![image](https://user-images.githubusercontent.com/50202826/83398507-beb8ee00-a3ff-11ea-88b6-81ce884f4346.png)

Save the state for what the user have in the cookiey

**Comment by jacobwod** [comment]
Yeah, we had this functionality for a while during early stages of Hajk 3's development. Can't recall why we opted out of this eventually. 

But sure, perhaps it's better to keep the tools in the same place, only hiding the labels.
