### ISSUE TITLE
Collector plugin: allow user to add another suggestion upon completing the questionary

### ISSUE THREAD

**Issue by hitomin21** [hajkmap/Hajk#527]
The button "stäng" finishes the questionnaire but you return to the first page of the same questionnaire. 
I think "stäng" should close the tool-window itself (so it will work like the "cross" button on the top right side). I will add a button called "Tyck till igen" so you will return to the start page of the questionnaire.

**Comment by jacobwod** [comment]
@hitomin21: Can you provide a screenshot of the change, please?

**Comment by hitomin21** [comment]
![bild](https://user-images.githubusercontent.com/22234673/98458978-53d1c700-2196-11eb-81d6-922f24057ed6.png)
Sorry that it took so long time, here is the screenshot.

**Comment by hitomin21** [comment]
The text on the button (Tyck till igen) are hardcoded into the code, There are multiple values already hardcoded so if we want to remove this we need to put more effort into that. I will be pushing more code into this tool but from other branches so if we want to create an issue for moving from hardcoding I think we should do that after I got everything merged.
