### ISSUE TITLE
Edit plugin: possibility of locking WFS layers with AD groups is missing in Hajk 3

### ISSUE THREAD

**Issue by FatemeHosseini** [hajkmap/Hajk#535]
**Describe the function that is missing in Hajk3**
In Hajk2, the administrator can allow that a user (with AD) have access to the edit plugin and **to have access to a wfs layer (edit layer) in the plugin** but in Hajk3 can only allow user to have access to the plugin or not. 

![image](https://user-images.githubusercontent.com/36195301/84009964-4ceb2200-a974-11ea-9d79-0121186f99d6.png)

**Comment by perosoderstrom** [comment]
Hi @jacobwod. I have made a test and implemented locking of edit layers with AD, in new-admin and new-backend. You can see the first test in branch ad-edit. Please notice this is just a first test, not ready for review yet. Now I saw that there is a new config.service.**v2**.js. I assume I shall implement the code there too? Comments?

**Comment by jacobwod** [comment]
That's right. In case you wonder why it's separated and seemingly duplicated: I'm preparing a new version of the API that _will break backwards compatibility_ with the current backend API. As you see, the request to /config/:map in v2 will give you not only the map config but also layer definitions (of used layers) and some more objects. I guess that we want to keep both options alive for the time being, hence two files. 

I was thinking about inheritance, (so v2 would `extend` the v1 class), I'll see if I'll refactor. For now, it's two files. I highly recommend that you try out the new API, just set the `experimentalNewApi: true` in client's `appConfig.json`.

**Comment by jacobwod** [comment]
Closed as of #762
