### ISSUE TITLE
Window remake

### ISSUE THREAD

**Issue by jacobwod** [hajkmap/Hajk#600]
The idea has been floating for a while, with mockups provided and all, but it seems nobody created an issue on it. So here it is.

Basically, remake the Windows in Hajk so their more similar to [this](https://xd.adobe.com/view/d42dafa7-f5cc-405a-5247-3c56447f7738-a21c/screen/294ee00d-e11c-4a97-89c9-4913a591ef74), though keep in mind that Material UI has default border radius of 4px. 

![Skärmavbild 2020-10-16 kl  08 44 31](https://user-images.githubusercontent.com/110222/96222023-d26a8880-0f8b-11eb-828c-0a12d04ac326.png)

**Comment by jacobwod** [comment]
Current progress:
![Skärmavbild 2020-10-16 kl  15 42 16](https://user-images.githubusercontent.com/110222/96265856-42960000-0fc6-11eb-805e-9e41ec5d77f9.png)

**Comment by jacobwod** [comment]
Soon ready for merge, @sweco-seqtob!

**Comment by sweco-seqtob** [comment]
Looks good! Can't wait to see what it looks like together with documenthandler when i merge it into our fork-branch @jacobwod
