### ISSUE TITLE
No entry is selected in Print's scales dropdown if 1:10 000 isn't available

### ISSUE THREAD

**Issue by jacobwod** [hajkmap/Hajk#620]
Scales available for the Print dialog are settable in admin and sent to the View as the `scales` prop. Those are mapped and rendered as one entry in dropdown each. 

The default value of that dropdown, however, is hard-coded:
```javascript
//PrintView.js
    scale: 10000, // Row 52
```

This will lead to problems if admin configured print in a way that doesn't include the 1:10 000 scale as an option. 

Preferably, the default scale should be also an option. Alternatively, we could just go for `scales[0]` as the default too.

**Comment by perosoderstrom** [comment]
It would be better to set scale closest to the active map scale, as in Hajk2. That would be more like WYSIWYG for the user.

**Comment by sweco-sesqqq** [comment]
My bad! Here's a suggestion with automatic scales.

**Comment by jacobwod** [comment]
Thank you! But it's your mistake - the hard-coded default of 1:10 000 was there already. Great fix anyway!
