### ISSUE TITLE
Add the possibility in print plugin to insert a text comment

### ISSUE THREAD

**Issue by persoderstrom** [hajkmap/Hajk#624]
Today you can insert a Title when printing. There is also a need for an additional text comment.
This feature exists in Hajk2 and should be added to Hajk3.

**Comment by jacobwod** [comment]
It's closed as off #625, isn't it? 😄 @perosoderstrom @sweco-sesqqq

**Comment by sweco-sesqqq** [comment]
It is!

**Comment by persoderstrom** [comment]
Yes!
