### ISSUE TITLE
Error loading WFS Vector layer

### ISSUE THREAD

**Issue by persoderstrom** [hajkmap/Hajk#628]
**Error message when loading WFS Vector layer**

_Cannot read property 'getAxisOrientation' of null_

Vector/WFS has worked before. 

**To Reproduce**
1. Add a Vector layer (Point) with WFS format in admin
2. Add the layer to a map
3. Open the map and select the layer
4. No features displays. See error in Console

**Screenshot**
Error in Console

![Skärmbild 2020-12-07 165521](https://user-images.githubusercontent.com/1893510/101373497-4bf86600-38ad-11eb-9190-ea6b4e016ee8.png)

**Comment by persoderstrom** [comment]
This might be caused by changes in "Feature/592 snap interaction"

**Comment by jacobwod** [comment]
I haven't tried this with a pure Points layer (my tables hold various types of geometries), but I can understand that it would be impossible to get an orientation out of a point. 

However, the error indicates that you don't even have a geometry, but rather a null object, which naturally lacks any properties, including getAxisOrientation. 

A quick search tells me that you might be missing the "duplicate" projections definitions in your map config. It seems that the GML parser reads "the other" format, [see this thread](https://stackoverflow.com/questions/36087622/ol3-polygon-wfs-feature-search-axis-orientation-undefined). E.g. for 3006 you should have these two:
```
    {
      "code": "EPSG:3006",
      "definition": "+proj=utm +zone=33 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs",
      "extent": [
        181896.33,
        6101648.07,
        864416,
        7689478.3
      ],
      "units": null
    },
    {
      "code": "http://www.opengis.net/gml/srs/epsg.xml#3006",
      "definition": "+proj=utm +zone=33 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs",
      "extent": [
        181896.33,
        6101648.07,
        864416,
        7689478.3
      ],
      "units": null
    },
```

**Comment by perosoderstrom** [comment]
Problem solved. Duplicate projections was missing. 
Thanks, @jacobwod !

**Comment by persoderstrom** [comment]
In default map_1 the only projection that is duplicated is EPSG:3006.

**Comment by jacobwod** [comment]
Feel free to fix and send PR.
