### ISSUE TITLE
Lock editing of map-config

### ISSUE THREAD

**Issue by sweco-sesqqq** [hajkmap/Hajk#648]
Add a posibility to lock a mapConfig so that we don't change something by accident. Maybey a key is enough?

**Comment by jacobwod** [comment]
We have this covered on the list in #650. Close this or do you want to keep it separate?

**Comment by sweco-sesqqq** [comment]
Let's close this one!

**Comment by jacobwod** [comment]
What a mistake, twice! My commits above did close #684 indeed.
