### ISSUE TITLE
Add simple config so we don't need to rely on having MapService set up

### ISSUE THREAD

**Issue by sweco-sesqqq** [hajkmap/Hajk#649]
It would be great if users could simply clone our repository, do 'npm install && npm start' and be up and running.

For now, we need to setup backend to deliver layers and map_1. Those could be replaced by static files in public. The app could then check for those files' existence and if they are found just render the simple demo map from static setup (let it be something from OpenStreetMap for example). 

If the files are not available, we should proceed to fetch MapService, as usual.

**Comment by sweco-sesqqq** [comment]
Implemented a possible solution, see https://github.com/hajkmap/Hajk/commit/7aa18088b16e6bf5096920037fade816d47c0a83

Instead of checking if static files exist, i chose to add two static json-files to /public (simpleMapConfig and simpleLayersConfig) which we fetch if mapserviceBase (the key for url to the backend in appConfig) is empty.

So, if someone wants to get the client up and running without setting up a backend, they can simply leave mapserviceBase empty in appConfig. This solution allowed me to create a netlify-app (which automatically builds from the netlify-demo-branch), see https://hajk-demo.netlify.app 

Will close this issue when tested and merged to master.

**Comment by jacobwod** [comment]
> Will close this issue when tested and merged to master.

I think it's time. @sweco-sesqqq 😉
