### ISSUE TITLE
Plugin: Bookmarks

### ISSUE THREAD

**Issue by jesade-vbg** [hajkmap/Hajk#655]
Add simple Bookmark functionality similar to Bookmarks in Hajk2.
Using localStorage to store bookmarks with m,x,y,z,l etc as a start.
Varberg has started development.

![bookmarks](https://user-images.githubusercontent.com/73874338/106735399-7730d480-6614-11eb-93d0-419ccdf8ab57.png)

**Comment by jacobwod** [comment]
Excellent. A small suggestion is that the work you're doing should be made in a feature branch that will be merged into `origin/develop`. Feel free to checkout `origin/develop` to ensure you don't get conflicts upon upcoming merge.

**Comment by jesade-vbg** [comment]
Sure, thanx. I'll do that.
