### ISSUE TITLE
Fetch options merge

### ISSUE THREAD

**Issue by jesade-vbg** [hajkmap/Hajk#657]
### Why?
In some cases Varbergs kommun needs to include credentials in requests.

### Optional in config:
Wrap fetch to add middleware, allowing to override fetch options.
Override could be made using url with wildcard.

### Example case (CORS):
We need Url https://map.domain.com* to use credentials: 'include' (withCredentials=true with XHR).

**We would specify this in config:**

```
"https://map.domain.com*": {
    credentials: "include"
}
```

**These options:**
```
fetch("https://map.domain.com/example", { credentials: "same-domain" });
```

would be merged and replaced with settings from config.

**Resulting in a request with these options:**
```
fetch("https://map.domain.com/example", { credentials: "include" });
```

**Other ideas are welcome!**

_**This is what I came up with that does not affect core-functionality for everyone and everywhere as fetch is used throughout the project.**_

**Comment by jacobwod** [comment]
This makes me think of https://github.com/hajkmap/Hajk/issues/204 that I've been working on some 2 years ago. It never materialised, although I tracked down and consolidated some of the fetching. 

Anyway, the idea was to create a utility for fetching that would be used throughout Hajk. Please take a look and see if there's anything useful there and if some concepts can be moved to this issue.

**Comment by jesade-vbg** [comment]
Ok, good, thanks. I just noticed the ~35 $.ajax calls in new-admin, would take some time to fix.

**Comment by jacobwod** [comment]
Sure, but don't bother with stuff in `new-admin`.

(We're about to do a complete rewrite of it, and no, it won't be called `an-even-newer-new-admin`. 🤣 )

**Comment by jesade-vbg** [comment]
Haha Ok, great, I would like to be in the loop. Regarding "don't bother with new-admin", not sure I can. Varberg might need the credentials fix before launch. In Hajk2 I recently made a quick fix for this.

**Comment by jacobwod** [comment]
OK I see, do whatever needs to be done. But keep in mind that quick-and-dirty fixes are absolutely fine in the obsolete `new-admin` - we'll put our effort into the new solution.

Regarding the upcoming `admin`, it's just a placeholder for now (we're settling down on the libraries to use etc), but you can see the idea in the `development` branch (https://github.com/hajkmap/Hajk/tree/develop/admin).

**Comment by jesade-vbg** [comment]
### A mix of my own code and thoughts and Jacobs closed issue #204.

Suggestion 1
----------------------------------------------------------

I'm thinking this could be a sollution.

_PSUEDO CODE:_

```
Singleton class FetchWrapper {

  exposing hfetchInit(config) {
    this.config = config
  }
  exposing hfetch(....)

  proxification()
  OverrideOptions()

}
```

In index.js

`import { hfetchInit, hfetch } from "FetchWrapper"`

and as soon as we get the appConfig we call.

```
hfetchInit(appConfigObject);
this.appModel.hfetch = hfetch; 
```


When we have appModel availiable we can easily call:
`this.appModel.hfetch(....)`


In code where appModel isn't availiable we can:

```
import { hfetch } from "FetchWrapper"
hfetch(....);
```
 

Suggestion 2
----------------------------------------------------------
This is not best practice, but we could override original fetch.
Making it availiable and used everywhere with 3 lines of code and 1 comment in index.js

```
import { hfetchInit, hfetch } from "FetchWrapper"
hfetchInit(appConfigObject);
// eslint-disable-next-line
fetch = hfetch;
```


Regarding $.ajax calls in new-admin
-----------------------------------------------------------
Not best practice.... but this will dissappear in new-new-admin.

This is the safest way to make everything keep working.

`$.ajax = function () { ovverriding original $.ajax }`



Configuration
-----------------------------------------------------------
In appConfig.
Not specified yet.

**Comment by jacobwod** [comment]
Good writeup! Suggestion 2 is clever, but personally **I'd prefer something like suggestion 1**. 👍 

Regarding new-admin, let's leave it as-is for now, it will be fixed once #650 is done.

**Comment by jesade-vbg** [comment]
I started an attempt here: [feature/657-fetch-options](https://github.com/hajkmap/Hajk/tree/feature/657-fetch-options) .

**Comment by jacobwod** [comment]
For the record, this is now in `develop` and if everything works out will find its way into `master` soon. 👍
