### ISSUE TITLE
Please provide compiled installation packages

### ISSUE THREAD

**Issue by matself** [hajkmap/Hajk#671]
**Background**
In the past, HAJK has been released as compiled packages.
However, the last release is soon a year old.
And there has been significant changes in the code since then.
Installing and configuring HAJK is not an easy task, and it would be nice if the user was spared the additional burden of handling and compiling the code. Especially since the compiling and installing instructions are rather sketchy.
Also, there is no way of knowing if the code is stable at a certain time. A random code fetch may occur just before a major change, or just after an unfortunate bug has been discovered.
**Proposal**
My proposal is to provide users with compiled components, at regular but not fixed intervals.
Say every second month or so, at a point where the developers feel that there is a stable code base.

**Comment by jacobwod** [comment]
Absolutely, contributions are always welcome. ATM we don't have any volonteers for preparing the releases. Would you like to be responsible?

**Comment by matself** [comment]
Absolutely. As soon as I have figured out a reliable process to do so. Which may take a while, as it seems at the moment. And I would of course need to know times when it would be suitable to package releases.

**Comment by jacobwod** [comment]
Great. 

We leave the release frequency up to the user and support group ("Förvaltargruppen") to decide. Contact @ingvar-uddevalla regarding their meetings and ask the question there.
