### ISSUE TITLE
Add more transparency on default selected search feature

### ISSUE THREAD

**Issue by jacobwod** [hajkmap/Hajk#675]
Users are reporting difficulties seeing what's beneath the blue result and orange selected result features. Adding more transparency by default should make it easier.

![Skärmavbild 2021-02-18 kl  08 25 24](https://user-images.githubusercontent.com/110222/108320273-dc62f900-71c2-11eb-812d-72483e740ff6.png)

**Comment by jacobwod** [comment]
What would you say about these as the new defaults?

![Skärmavbild 2021-02-18 kl  15 55 10](https://user-images.githubusercontent.com/110222/108374852-b14bca00-7201-11eb-844f-e5a267b6470c.png)

**Comment by sweco-sesqqq** [comment]
Sounds good! The proposed defaults above looks great!

**Comment by persoderstrom** [comment]
What about having the same color for both the search result and the selected result, but emphasizing the selcted?

**Comment by jacobwod** [comment]
@perosoderstrom It could work I guess - please provide some screenshots, that'd make it easier to compare.
