### ISSUE TITLE
BackgroundSwitcher bahaving badly

### ISSUE THREAD

**Issue by jesade-vbg** [hajkmap/Hajk#676]
**BackgroundSwitcher**

The backgrounds are not turning on/off as they should. Possibly something wrong with the switching logic.

Also this commit:
[https://github.com/hajkmap/Hajk/commit/de48dd014a6e8955c34f30443375e9db996d476c#diff-13567a7b74ba0207d476938e142a7d4dedd2164d70020d7bfc0f82cc1c7f7af4](https://github.com/hajkmap/Hajk/commit/de48dd014a6e8955c34f30443375e9db996d476c#diff-13567a7b74ba0207d476938e142a7d4dedd2164d70020d7bfc0f82cc1c7f7af4)
contains the code below, and it gets lots of events every time the map is moved or zoomed, causing the function to run over and over in ~60fps. 
I doubt this is necessary.
It also makes focus jump between the radiobuttons.
Flickering.

```javascript
// Update selected background layer if it is changed outside layerswitcher
    this.props.app.globalObserver.subscribe(
      "layerswitcher.wmsLayerLoadStatus",
      (d) => {
        const backgroundUpdated = this.props.layers.find(
          (layer) => d.id === layer.name
        );
        backgroundUpdated &&
          this.setState({
            selectedLayer: backgroundUpdated.name,
          });
      }
    );
```

Note:
We currently have 5 backgrounds.
Vit
Topografisk Karta
Topografisk karta, gråskala
Flygfoto 2019
Flygfoto 2017

**Comment by jacobwod** [comment]
Great find. The commit you refer to, however, is only a merge. **The actual change was made in 8d074de by @linusfj**.

**Comment by jacobwod** [comment]
I can confirm the behaviour, added a simple 
```js
this.props.app.globalObserver.subscribe(
      "layerswitcher.wmsLayerLoadStatus",
      (d) => {
        console.log("Hit!");
       // ... omitted the rest
```

Here it is:
![Skärmavbild 2021-02-18 kl  14 23 23](https://user-images.githubusercontent.com/110222/108363277-07664080-71f5-11eb-8a2f-72796c08229a.png)
