### ISSUE TITLE
FME Server Datadownload plugin

### ISSUE THREAD

**Issue by maan002** [hajkmap/Hajk#680]
A new plugin where the user can specify parameters and an area and submit them to a FME Server datadownload workspace.

Suggested functionality:
- The user should be able to draw a polygon or rectangle specifying the area to download.
- All FME workspace parameters should be fetched from FME Server and displayed to the user. 
- The most common FME workspace parameter types should be supported.
- The result should be sent to one or more mail addresses.

User Interface:

![image](https://user-images.githubusercontent.com/22821937/108599433-61037200-7391-11eb-905e-ea22f9dc9805.png)

**Comment by maan002** [comment]
A first implementation is found in branch feature/680-fme-server.

To add/improve:
- Both "YTA" and "REKTANGEL" draws a rectangle.
- Workspace parameters must be specified in map_1.json (see readme.txt for instructions).
- The following workspace parameters are supported: TEXT, LOOKUP_LISTBOX, LOOKUP_CHOICE. Add support for more.
- The mail address is specified in map_1.json. Add support in backend to retrieve the current user's mail address.
- When you order ("BESTÄLL" button) the request goes directly to FME Server. Add support in backend to eliminate CORS problem.
- The FME token must be updated manually in map_1.json. Add support in backend to retrieve an new FME token.

**Comment by jesade-vbg** [comment]
This will be great! Good work Mattias!

**Comment by jacobwod** [comment]
Hi @maan002 , any plans on PRing this into `develop` soon? We agreed to help you out testing this and it'd be easier if it could be found there, together with the latest code.

**Comment by maan002** [comment]
Branch feature/680-fme-server has been added to _develop_.

I have openend a new issue to enhance this plugin (#750).

**Comment by jacobwod** [comment]
Normally we don't close the issue until the code has made it to `master`. I'll leave it for know but please keep in mind for the next PR that linked issues will get closed automatically once we merge `develop` into `master`.
