### ISSUE TITLE
Make it possible to search for exakt phrases

### ISSUE THREAD

**Issue by jacobwod** [hajkmap/Hajk#702]
Currently the search on load (and all search in fact) will by default append a wildcard to the search phrase. This can be disabled by user, but not by passing a query param. Hence, embedding certain search results and zooming to them is not possible, because we get multiple results (while search on start will only zoom if one sole result is returned).

E.g. [this search phrase](https://karta.halmstad.se/?q=CARL%20KUYLENSTJERNAS%20VÄG%201) should return one adress, but it has multiple matches. 

**Proposal: if the search phrase is surrounded by quotation marks, the `searchOptions.wildCard{Start|End}` are automatically disabled.**

**Comment by sweco-sesqqq** [comment]
Potential fix pushed to develop. See b75ca15089ba248e6a00dfde24c8d2cddd183e70

**Comment by jacobwod** [comment]
Closed by @sweco-sesqqq commit https://github.com/hajkmap/Hajk/commit/03fb28c7cae781c48ef86fb8b9d40b4c2f7c3140.
