### ISSUE TITLE
CSS Bug in SketchPicker (Color picker)

### ISSUE THREAD

**Issue by jesade-vbg** [hajkmap/Hajk#708]
**Describe the bug**
CSS for SketchPicker (the color picker) is broken.
import { SketchPicker } from "react-color";
The bug can be seen anywhere in admin where SketchPicker is used.
I don't now when bug appeared but it's noticable in develop branch 2021-03-16

This bug makes it kind of hard to edit colors....

**To Reproduce**
1. /Admin
2. Kartor > Inställningar
3. Scroll down to to bottom where colorpicker is located
4. See CSS bug

**Screenshots**
Bug:
![aa](https://user-images.githubusercontent.com/73874338/111426258-ae56d300-86f4-11eb-934b-bfee2e06dbb3.png)
![bb](https://user-images.githubusercontent.com/73874338/111426264-aeef6980-86f4-11eb-9b3f-bb7458e098dc.png)

**This is what it's supposed to look like.**
![correct](https://user-images.githubusercontent.com/73874338/111426283-b6af0e00-86f4-11eb-88f6-a344df4cbada.png)

**Desktop:**
Chrome/Edge 89+

**Comment by sweco-sesqqq** [comment]
I've got a fix for this almost ready. Just gonna make sure it doesn't mess with the other sketchpickers in admin.

**Comment by sweco-sesqqq** [comment]
It seems like the sketchpickers are messed up everywhere in admin. Maybey just for me? Look at the sketchpicker at the bottom of the mapsettings for example. My fix seems to take care of these aswell

**Comment by jesade-vbg** [comment]
Yes, in mapsettings aswell. The second screenshot was from there.
Great if you've found a fix!

**Comment by sweco-sesqqq** [comment]
Ah my bad. Read to fast. It seems the pickers broke after we updated the react-color version. I think they changed a span-component to a label-component, and then our article-label-css was applied, breaking the component. Pushing the fix in a minute!

**Comment by sweco-sesqqq** [comment]
Fix pushed to master. Closing.
