### ISSUE TITLE
InfoClick, Sort layer info items by attribute

### ISSUE THREAD

**Issue by jesade-vbg** [hajkmap/Hajk#709]
Make it possible to sort layer info items by specified attribute.
Possibility to decide asc or desc sort order.

New settings for layers (naming not decided):
`infoClickSortProperty string`, empty = nothing will be sorted in client, as of today.
`infoClickSortType string`, "string" or "number" (in v1)
`infoClickSortDesc bool`, false

**Comment by jacobwod** [comment]
I'm not sure I follow, can you clarify?

**Comment by jesade-vbg** [comment]
Sure.
If the infoclick pops up and there are multiple hits, for example "1 of 4". In the attached case there are 4 hits for Detaljplan but there is no possibility to decide what is visible first (as #1). In this case maybe I would like to sort on "Namn" or "Laga kraft".
![infoclick](https://user-images.githubusercontent.com/73874338/111475592-89328680-872d-11eb-913e-20df25407666.png)
