### ISSUE TITLE
Wrong scale depending on selected resolution in Print-plugin

### ISSUE THREAD

**Issue by maan002** [hajkmap/Hajk#710]
**Describe the bug**
When you change resolution from 150dpi to 300 dpi you get a map that has a different scale instead of a higher/lower resolution. 

**To Reproduce**
1. Go to: https://hajk-demo.netlify.app/
2. Zoom to approx 1:55000 (see picture below).
3. Start "Skriv ut".
4. Change scale to 1:50000.
5. Switch to Settings and verify that "Upplösning (DPI)" is 150.
6. Align the print preview with something on the map.
7. Click "SKRIV UT" and open the PDF in a new TAB.
8. Change "Upplösning (DPI)" to 300.
9. Click "SKRIV UT" and open the PDF in a new TAB.
10. Wrong: The two PDF:s displays different areas. (see Results below)

**Expected behavior**
The two PDF:s should display the same area in scale 1:50000, but with different resolution.

**Desktop (please complete the following information):**
 - Windows 10
 - Edge
 - Version 89.0.774.45 

**Screenshots**

![Preprint_01](https://user-images.githubusercontent.com/22821937/111605533-abccaa00-87d6-11eb-9ace-96fb04dc24fb.PNG)
Setting scale to 1:50000.

![Preprint_02](https://user-images.githubusercontent.com/22821937/111605689-cbfc6900-87d6-11eb-923e-7e47f8db0b80.PNG)
Verify that DPI is 150 and aligning the print preview with something on the map.

![Result_150dpi](https://user-images.githubusercontent.com/22821937/111605886-f77f5380-87d6-11eb-9790-29c123c8b787.PNG)
Result of printing in 150dpi.

![Result_300dpi](https://user-images.githubusercontent.com/22821937/111605928-0239e880-87d7-11eb-8240-0ed4ec85a9d1.PNG)
Result of printing in 300dpi.

**Comment by sweco-sesqqq** [comment]
I've investigated this a bit further, and as you say, we seem to have some issues in some scale-intervals. 

I found that when we are requesting images from geoServer, we are not asking for a certain DPI and thereby it defaults to 90, (i think, it might be configurable). I also found that when requesting a higher (and i guess lower as well) DPI than 90 we must take the change in DPI in to consideration when calculating the map-canvas size.  (Which we don't do currently). See image below for details: 
![image](https://user-images.githubusercontent.com/43059093/111628682-c6138180-87f0-11eb-9e72-1ee6dcb9b50c.png)

Read more here: _https://docs.geoserver.org/latest/en/user/services/wms/vendor.html_

My guess on how to fix this:

- Make sure we send the requested dpi as a vendor parameter in the GetMap-requests
- Make sure we calculate the map-canvas size used for printing correctly by scaling according to requested_dpi / 90

**Comment by jacobwod** [comment]
I agree with everything you say @sweco-secoma, but re-reading this today got me thinking:
> Make sure we calculate the map-canvas size used for printing correctly by scaling according to requested_dpi / 90

In yesterday's attempt we changed the requested width/height, but **we might have forgotten to change the size of the orange overlay**.

**Comment by maan002** [comment]
Please note that the format_options=dpi:300 is a vendor specific parameter for GeoServer.
If we use that, we will get problems printing maps with other sources than GeoServer.

**Comment by jacobwod** [comment]
See [this example](https://openlayers.org/en/latest/examples/export-pdf.html).

**Comment by maan002** [comment]
Just a thought, could it be the hiDPI setting in OpenLayers that kicks in at higher resolutions (i.e. 300DPI)?

**Comment by sweco-sesqqq** [comment]
I think i've found the issue.

1. ConstrainResolution must be set to false while printing. (Simple to fix, im quite surprised we've missed this)
2. It seems the problem with the different zoom-levels depending on resolution originates from hitting the maxZoom-level. (When we request a print with higher resolution we create a bigger canvas, which in turn means that the map must be able to zoom further to fit the correct content in the viewport. If this zoom-level is bigger than the maxZoom, the resulting images will not look the same (If we try to zoom to let's say 15, when the maxZoom is set to 13, it will simply stop zooming at 13).

Some possible fixes:
1. Warn the user if they have chosen a scale, format, and resolution which will fall outside the maxZoom-level
2. Disable options that will fall outside the maxZoom-level (If the user wants 300 dpi and 1:10 000 falls outside the maxZoom, 1:10 000 would be disabled).
3. Change the maxZoom-level while printing (not sure if this is possible considering the mapConfig only contains a finite set of resolutions), this would probably be the cleanest solutinon.

**Comment by jesade-vbg** [comment]
@sweco-sesqqq yes 1:1 I've done this fix but it only fixed some  issues if you hade this to yes in config. The reported issue was still an issue.

**Comment by sweco-sesqqq** [comment]
Here's a branch with a potential fix: https://github.com/hajkmap/Hajk/tree/fix/710-wrong-scale-in-print

Please try it out and tell me what you think. Im sure we can do something better, but at least this fix tells the user if the selected values will produce an incorrect print-image.

**Comment by jacobwod** [comment]
I'm testing `develop` now and fix in 3fbf2b7 works like a charm, @sweco-sesqqq! 👍

**Comment by jacobwod** [comment]
Just a reminder that #722 closes #710
