### ISSUE TITLE
Need for documentation revision

### ISSUE THREAD

**Issue by matself** [hajkmap/Hajk#713]
**Describe the bug**
I think the instructions (chapter 4) in this file needs to be revised.
https://github.com/hajkmap/Hajk/blob/master/dokumentation/Systemdokumentation.docx
The result from running build.sh does not match the instructions givrn.

**To Reproduce**
Compare the image on page 27 with the actual build result.

**Expected behavior**
Instructions that relate to the current architecture

**Desktop (please complete the following information):**
N/A

**Comment by persoderstrom** [comment]
Can you supply the actual build result? (I'm not able to reproduce it this week)

**Comment by matself** [comment]
Absolutely. Here it is.
https://www.dropbox.com/s/dcwjypik8b0bxm6/hajk_build_210323.zip?dl=0
(Too big to attach)
However, I am unable to run the package with this instruction:
```
# You will be able to run the whole package (backend, as well as
# it serving the static client and admin apps) via one command:
# node index.js
```

**Comment by matself** [comment]
This request was prompted by an attempt to produce a distributable installation package for HAJK 3. But with the scarce and fragmented build and packagaing instructions that are available, I have concluded that this is not possible for me. It would involve far too much guess work and time to be efficient, and certainly not give a result that I can stand for, or let other users rely on. I am closing this issue, hoping that the HAJK project at some time will find the time and resources to issue executable releases.
