### ISSUE TITLE
Can't input text on Mobile

### ISSUE THREAD

**Issue by jesade-vbg** [hajkmap/Hajk#715]
When I try to input text in a textfield the keyboard pops up then it closes directly after, the input loses focus.

The only text-input that I can find that works is the search-input.

Bug found in:
* Print > input title
* Bookmark > input name
* Draw Circle > input radius.
* Color picker > input hex-color or RBGA
* etc etc etc.

Bug can be found in:
https://karta.halmstad.se
and
https://hajk-demo.netlify.app/

Thoughts:
Maybe globally registered document.focus or input.blur somewhere in code where it should be locally handled.
I think this points to the search input as it's the only input I can get working. But I havn't investigated any further.

Browser:
Chrome (Latest) on Android.

**Comment by jesade-vbg** [comment]
The issue seems to be isolated to Android. Tested with Safari and Chrome on iOS with no related issues.

**Comment by jesade-vbg** [comment]
https://user-images.githubusercontent.com/73874338/112308390-5e52b000-8ca2-11eb-8942-8c4d73c9fb29.mov

**Comment by sweco-sesqqq** [comment]
I have to get an android phone... Could you look into this since you've got an android?

**Comment by jesade-vbg** [comment]
I've been investigating the better part of the day.
I think I've found the bad guy, but I'm not sure yet how to solve it and what consequence it has.

When I remove setTimeout and the focus() function (link below) it executes, the problem goes away on my Android phone.

https://github.com/hajkmap/Hajk/blob/dd22c06f0877890b543d1bf4c0b3b385f94d33e9/new-client/src/components/Window.js#L184

**Comment by sweco-sesqqq** [comment]
Nice work! @sweco-seqtob could you explain what would happen if we removed that snippet? Was the focus added so that screen readers would read in correct order?

**Comment by jacobwod** [comment]
Good find @jesade-vbg! 

We still need to find another way of focusing to make @sweco-seqtob happy, though. ;) Again, what was the reason that this focusing was added?

**Comment by jacobwod** [comment]
Well done, it's in `develop` now and ready for tests!
