### ISSUE TITLE
Enhance Print plugin

### ISSUE THREAD

**Issue by maan002** [hajkmap/Hajk#724]
We have the following user requirements on the Print plugin:

1. There should be white areas around the map (margins). Must have.
2. There should be a disclaimer text 'Observera att gränserna i kartan ...'. Must have.
3. There should be a copyright text. Must have.
4. The scale bar should be clearer and easier to use. Must have.
5. Default text and scale bar color should be configurable. Must have.
6. Resolutions should be configurable. Good to have.
7. Paper sizes should be configurable. Good to have.
8. The possibility for the user to change placement of logo, scale bar and north arrow should be configurable. Good to have.

To solve the requirements above without altering the current print layout all requirements should be configurable.

**Comment by sweco-sesqqq** [comment]
I like all these suggestions. Are you planning to implement? I can probably be helpful since i rewrote the print-plugin some months ago - just message me if something is unclear.

**Comment by Hallbergs** [comment]
I just pushed a suggestion for a fix, see branch feature/724-enhance-print-plugin. 

- There should be white areas around the map (margins). - Done
- There should be a disclaimer text 'Observera att gränserna i kartan ...'. Must have. - Done
- There should be a copyright text. Must have. - Done
- The scale bar should be clearer and easier to use. Must have. - Not sure how we want to make it more clear and "easier to use"?
- Default text and scale bar color should be configurable. Must have. - Done
- Resolutions should be configurable. Good to have. - Not implemented yet
- Paper sizes should be configurable. Good to have. - Not implemented yet
- The possibility for the user to change placement of logo, scale bar and north arrow should be configurable. Good to have. - Not implemented yet

Before we can merge this, someone must fix the admin-parts, test the solution to make sure that what the preview shows and what the resulting print looks like matches, (and maybey move the disclaimer and copyright texts, im not sure they look good where they are currently).

**Comment by Hallbergs** [comment]
Just pushed (same branch) an update for how the margin around the image is added. The "old way" messed with the scale of the resulting map-image.

**Comment by maan002** [comment]
Looks really good!!

I found a little bug regarding calculating the width and height of the print preview.
This will be pushed to the 724 branch above shortly.

**Comment by maan002** [comment]
1. There should be white areas around the map (margins). _Done_
2. There should be a disclaimer text 'Observera att gränserna i kartan ...'. _Done_
3. There should be a copyright text. _Done_
4. The scale bar should be clearer and easier to use. _Not implemented yet_
5. Default text and scale bar color should be configurable. _Done_
6. Resolutions should be configurable. _Done_
7. Paper sizes should be configurable. _Done_
8. The possibility for the user to change placement of logo, scale bar and north arrow should be configurable. _Not implemented yet_

Closing this issue.

**Comment by Hallbergs** [comment]
Let's close it when we merge to master! :)
