### ISSUE TITLE
Containerization

### ISSUE THREAD

**Issue by Hallbergs** [hajkmap/Hajk#725]
To simplify installation of Hajk we should containerize the whole solution. I have started in branch feature/docker-setup (https://github.com/hajkmap/Hajk/tree/feature/docker-setup).

This branch is WIP, building client, admin, and backend is "done" (can probably be solved in a better way), but i think we should keep developing the docker-compose-file so that we can include an nginx-proxy, a Postgres-database and a geoserver aswell.

Setup a working backend, client, and admin:

## Build the container
docker build -t hajk-backend-with-client-and-admin .

## And run it. Check out the result at localhost:1337
docker run -p 1337:3002 hajk-backend-with-client-and-admin

To clarify, the Dockerfile in the project root is working. The docker-compose.yml in the project root is wip. (The scripts above should be run in the project root dir).

**Comment by matself** [comment]
In principle a good idea, but restricted to those using Docker. But leave it to the users to set up PostgreSQL/PostGIS and Geoserver. These have good distributions and are perhaps already running in an environment where HAJK could be considered as the web map solution.

**Comment by sweco-sesqqq** [comment]
My idea is that we give the users the possibility to build a solution with a database, geoserver, and hajk. It will be configurable, of course (letting the users create a container with only hajk).

**Comment by jacobwod** [comment]
Fantastic work, @sweco-sesqqq!

**Comment by Hallbergs** [comment]
Dockerfiles merged to develop. Also published an image to docker hub, see: https://hub.docker.com/r/hallbergs/hajk

**Comment by Hallbergs** [comment]
Hm. b7a84df85e9d78dbc1419ffaff62c9f6ff64b0d9 maybey?

**Comment by jacobwod** [comment]
Ah, it's in 3.6 RC then!
