### ISSUE TITLE
Icon change suggestion (Location)

### ISSUE THREAD

**Issue by jesade-vbg** [hajkmap/Hajk#735]
The tool "Positionera" or "Location" uses the icon CenterFocusWeakIcon which symbolizes a type of center focusing method on cameras. I've seen it myself on my DSLR camera.

My suggestion is to use the **MyLocation** icon which I think is commonly used in map applications.

What do you think?

**Before > After:**
![MyLocation](https://user-images.githubusercontent.com/73874338/113298312-f92f3800-92fb-11eb-8310-025e38639cb7.png)

**Comment by matself** [comment]
Absolutely. I was thinking that myself.

**Comment by Hallbergs** [comment]
I agree, let's change it!

**Comment by jacobwod** [comment]
In the future, please select Project ("Hajk") and a milestone ("3.x") when creating issues. It will make it easier to track changes when we release the next version.
