### ISSUE TITLE
Colored buttons in admin are defined multiple times

### ISSUE THREAD

**Issue by sweco-seqtob** [hajkmap/Hajk#738]
**Describe the bug**
ColorButtonGreen, ColorButtonRed and ColorButtonBlue are defined as components multiple times
in admin. 

**To Reproduce**
1. Search for ColorButtonGreen, ColorButtonRed or ColorButtonBlue in the source code for new-admin

**Expected behavior**
Code should be kept DRY but now the same Buttons are defined multiple times in severals files.
They should be defined one time and then imported instead

**Screenshots**
![image](https://user-images.githubusercontent.com/22886522/113830025-776d5d80-9786-11eb-9729-3e43adc40006.png)

**Additional context**

**Comment by Hallbergs** [comment]
The code in admin is messy in _several_ places. Im not sure if there is much winning in starting to clean the code up, it will be an humongous job... I rather see that we re-write the entire application.  When admin is re-written we will follow the dry principle. @jacobwod what do you think?

**Comment by jacobwod** [comment]
Absolutely something we'll look into in when working on #650. Good find @sweco-seqtob but I'd say it's a `WONTFIX`.
