### ISSUE TITLE
Accomodate long titles in Drawer

### ISSUE THREAD

**Issue by jacobwod** [hajkmap/Hajk#740]
**Describe the bug**
If a long text is displayed it causes this problem:
![Skärmavbild 2021-04-07 kl  10 23 05](https://user-images.githubusercontent.com/110222/113834644-5bb88600-978b-11eb-8b35-c5ce879f2d33.png)

**Proposed solution**
- Remove wrap in Grid container
- Add some top and bottom padding to the Typography component, and eliminate the default line height
- Add negative margin to the locker IconButton component, to compensate for the added padding (Typography element will "push" the container's size now, so we don't want the IconButton to add additional space).

That would result in something like this:
![Skärmavbild 2021-04-07 kl  10 26 02](https://user-images.githubusercontent.com/110222/113835105-ebf6cb00-978b-11eb-97a9-d19bd3eddc67.png)

And it should work for both long and short titles:
![Skärmavbild 2021-04-07 kl  10 26 26](https://user-images.githubusercontent.com/110222/113835109-ec8f6180-978b-11eb-9db5-7048e4f0b99d.png)

**RFC**
Opinions @sweco-seqtob, @Hallbergs? I'm thinking of pushing this into `master` directly as it's a cosmetic change that fixes existing edge case issue.

**Comment by jacobwod** [comment]
Hmm nevermind, there were changes in App.js already and I don't want to cherry pick lines. I'm pushing this into `develop` for now.

**Comment by Hallbergs** [comment]
Looks good!
