### ISSUE TITLE
Add missing settings for print plugin

### ISSUE THREAD

**Issue by hitomin21** [hajkmap/Hajk#755]
Several options from the print tool in Hajk2 are missing in Hajk3 (the client side print).

The following options should be added:

dpis
paperFormats
logoMaxWidth
copyright
disclaimer
useMargin
mapTextColor

**Comment by jacobwod** [comment]
I'm not sure if all of that is intended to be exposed to the end user. For example, we don't want users to put their own copyright text.

Also, some of these (DPI, orientation, size [i.e. "paperFormat"] exist already.

**Comment by hitomin21** [comment]
Some of these settings are not exposed to the users, it just available to be configured in the admin tool.

So the user cannot add custom DPI settings but the admins can do that (same with paperFormat, logoMaxWidth copyright, disclaimer).

For the others (useMargin, mapTextColor), the admin tool just sets a default value.

**Comment by jesade-vbg** [comment]
These changes are for new-admin. Only minor changes in Client.
