### ISSUE TITLE
Background Layer - Add info button

### ISSUE THREAD

**Issue by hitomin21** [hajkmap/Hajk#764]
We do not support adding descriptions or information for the background layers. I think we should so it is the same as normal layers, see below.

![bild](https://user-images.githubusercontent.com/22234673/115566682-c1902c00-a2ba-11eb-8f8c-84c82b122085.png)

Stödet verkar finnas i admin men inte i klienten.

**Comment by Hallbergs** [comment]
Closed as of #808
