### ISSUE TITLE
Area/polygon not marked when infoclicked

### ISSUE THREAD

**Issue by FredrikEkstrom79** [hajkmap/Hajk#771]
When infoclick on a feature it will be marked, if you click on it again the marking will go away but you now can't select it again until you close the information dialog or switching to another feature. 

_Maybe it's not an issue but it's confusing. Is there a point to way you can deselect a marked feature when infoclick is opened?
The meaning of the marking is to see which feature the information is from._

**Steps to reproduce the behavior:**
1. Infoclick on a feature, the information dialog will open
2. Click on it again, with out closing the information dialog

**Expected behavior**
Clicking on a marked feature should not deselect it, rather perform infoclick and mark it again (default behavior)

**Screenshots**
The red circle marks where infoclick is performed
![image](https://user-images.githubusercontent.com/50202826/115840948-8c9bea80-a41c-11eb-9976-08cf5f78bddc.png)
![image](https://user-images.githubusercontent.com/50202826/115840820-637b5a00-a41c-11eb-9480-fcf482a6f821.png)

**Comment by jacobwod** [comment]
Seems to occur for points too. One click selects, the next one (on selected item) deselects, a third click in a sequence does nothing (where a selection would be expected).

**We should either allow select->deselect->select _or_ make sure that click always selects, even if already selected.**

**Comment by jacobwod** [comment]
Fix is in `develop`, leaving issue open for now.
