### ISSUE TITLE
Provide a simple and reliable way to run the node backend on windows

### ISSUE THREAD

**Issue by Hallbergs** [hajkmap/Hajk#776]
Running nodeJS-applications in a windows production environment is a bit of a hassle. (Mostly regarding handling server reboots). We should provide a simple way for the system administrators to deploy the NodeJS-backend in a windows environment.

## My suggestion is that we use node-windows, see: https://github.com/coreybutler/node-windows
This solution allows us to install node-windows as a dependency in the backend - which makes it simple for system administrators to deploy the backend in a Windows environment. (Since the only thing they must install on the server will be the NodeJS-runtime). 

## There are several other solutions we might want to consider, some examples:
- IISNODE, see: https://github.com/Azure/iisnode - The downside with this solution is that Azure have not confirmed that this solution is maintained anymore,
- Batch-script - The upside here is that we don't need any extra dependencies, but it is not as simple to set up as my proposed solution.
- PM2 - Cant handle reboots on windows out-of-the-box

## So what does my solution do?
We provide two scripts: `installWindowsService.js` and `uninstallWindowsService.js`, and when the user runs `node installWindowsService.js` the node-windows dependency will automatically create a windows service on the server. The service will automatically restart on server reboot, it will log fatal errors to the event viewer, and it will make sure not to pummel the server (node-windows provides smart restarts etc.)

## Tests
The solution is tested on Windows 10 and Windows server 2016. Haven't seen any problems yes, and server reboots are handled without any problems (no need for administrator to log in etc).

## Screenshots
The first draft install-script. It will be provided in the root of the nodeJS-backend
![image](https://user-images.githubusercontent.com/43059093/116188656-194ded80-a728-11eb-98ec-9dbc90602c07.png)

The first draft uninstall-script. It will be provided in the root of the nodeJS-backend
![image](https://user-images.githubusercontent.com/43059093/116188711-2cf95400-a728-11eb-90a9-4c7c11ee762f.png)

The resulting service
![image](https://user-images.githubusercontent.com/43059093/116188792-46020500-a728-11eb-9c12-1fd3b84398e1.png)

**Comment by Hallbergs** [comment]
Woops, the commit above was not supposed to close this.

**Comment by Hallbergs** [comment]
Would love some feedback from @jesade-vbg and @sweco-seqtob. What do you guys think, could this be a solution for windows-users?

**Comment by matself** [comment]
I installed Pm2 as a service. Seems to work ok. And you can run Hajk in Cluster mode to scale over several processors. 
Then I had it all running under IIS. However, the Windows authorization fails because /admin is rewritten to /static/admin.

**Comment by Hallbergs** [comment]
Yes, i've had that setup aswell. The idea behind this issue is to provide a simple way for administrators to install a service, without having to do much on their own. (I was thinking that we possibly could provide scripts to automate installing pm2 as a service, that would be a nice solution, maybe you could help?)

**Comment by Hallbergs** [comment]
Keep in mind, the solution above is just a proposal - everyone can install the backend as they see fitting :)

**Comment by jacobwod** [comment]
I think this is a perfect out-of-the-box solution for Windows setups where you come achieve the same seamless binding to system startup (as you would do with PM2 on UNIX-like systems). (If only `pm2 startup` was an option on Windows…) 

I like the way you mention other solutions in this issue. As you said: this is a proposal and nobody is forced to use this. Personally, I can see a lot of happy Windows admins though.

**Comment by matself** [comment]
Like I said, I was happy until I relized that /admin was wide open in this setup. I have no AD on my standalone machine.

**Comment by jacobwod** [comment]
Disable the exposure of admin in `.env`, or (even better on a production machine) remove the entire directory from /static. Next, setup admin (which really is just a static application) on another "safe" computer that's not accessible from the outside, and point it to your backend on the production server (you'll have to deal with CORS too).

**Comment by Hallbergs** [comment]
No, node-windows does not change this... Another solution for you would be to host the admin-application in iis and only use node for the api-calls (using iis as a reverse proxy)

**Comment by matself** [comment]
That is good thinking. I will try that. But I am afraid that it will ruin my url rewrite in IIS. We shall see.

**Comment by jesade-vbg** [comment]
Great work!
node-windows seems promising as it becomes a service and can (probably) be monitored/restarted etc with the usual tools the IT administrators use in windows. Maybe someone could verify this (as I'm only speculating at this point)?

**Comment by jacobwod** [comment]
I like the discussion here, but maybe it should be archived? It looks like the issue can be closed, as @Hallbergs's commits are in `master` by now.
