### ISSUE TITLE
Make it possible to let autocomplete in search use wildcard at start

### ISSUE THREAD

**Issue by sweco-seqtob** [hajkmap/Hajk#777]
**Is your feature request related to a problem? Please describe.**

- Make it possible to let autocomplete in search use wildcard at start.

**Describe the solution you'd like**

- The autocomplete should have an option to enable wildcard before the actual lookup value.
- Add configuration for the search tool to enable wildcard at start for the autocomplete lookup.
- Default should still be to do the lookup for autocomplete without wildcard, to not break current functionality.

**Current state  for autocomplete**

**SearchString** : _Liseberg_
**Hits** : _Liseberg parking_
**No hit**: _Parking Liseberg_

**Propsed result**

**SearchString**: _Liseberg_
**Hits**: _Liseberg parking_
**Hits**: _Parking Liseberg_

**Propsed configuration**

![image](https://user-images.githubusercontent.com/22886522/116255406-7f5f6280-a772-11eb-8144-3132b4e0ed49.png)

**Comment by sweco-seqtob** [comment]
This is functionality requested and i can implement it as long as no one is opposed the idea.
Default is still the same as today and this is only optional

**Comment by Hallbergs** [comment]
I like it
