### ISSUE TITLE
Handle InfoClick for group layers in Geoserver

### ISSUE THREAD

**Issue by jesade-vbg** [hajkmap/Hajk#786]
_Hajk can show group layers from geoserver today but it's not possible to use InfoClick with correct behaviour._

**Expectations**
Each layer in a group should be able to have a specific html/markdown.
If no html/markdown is specified, it should fallback and use the parents html/markdown.

**Why make this possible?**
If we were able to group layers in geoserver and still get all needed feature information,
and format the information correctly it could drastically improve performance by minimizing requests.
In some scenarios this would be great.

_Hajk has the ability to group layers but the request count are still unaffected._

Do you have any other suggestions/ideas? let me know.

**Comment by maan002** [comment]
You should also be able to specify that a specific layer is not queryable in a GeoServer group layer. 
You can specify that in GeoServer, but it would be better if you can also use Hajk Admin.

**Comment by jacobwod** [comment]
This has to be related to #202 somehow?

**Comment by jesade-vbg** [comment]
Here is a proposal for this functionality. Please have a look when you got time @jacobwod & @Hallbergs.

Admin:
![GeoServer-group-layer-admin](https://user-images.githubusercontent.com/73874338/194019277-52992fa0-a770-4243-811c-a103e76ebf70.png)

Json:
![GeoServer-group-layer-json](https://user-images.githubusercontent.com/73874338/194019281-6095c693-f028-41ae-95da-4c79cfd4c46f.png)

_Note that is this version a sublayers html/markdown will NOT fallback and use the parents html/markdown as described in original issue._

**Comment by jacobwod** [comment]
Looks good. Two question:
1. Does the WMS group type setting (e.g. "single" or "opaque" or "named tree") affect this functionality? 
2. Related to 1 above: how does the layer show in LayerSwitcher? With its sublayers visible or hidden?

I think that the group type setting should determine 1 and 2. `single` should not show the children in LS, while `named tree` should. The `opaque` and other modes should be discussed too. What's your opinion, @jesade-vbg & @Hallbergs?

**Comment by jacobwod** [comment]
1. That's fine!
2. Wouldn't it be possible for the new function to produce a layer config similar to the one that is made currently when creating a "Hajk group layer" in Admin? This would be a big win for us because LayerSwitcher currently handles this syntax and we have full control over things like if we want to show it as a group or hide children (it's an option in Admin as you might now). See screenshot below or head to https://framtidsplan2050antagande.halmstad.se for examples of what I mean:
![image](https://user-images.githubusercontent.com/110222/195079173-c7d73d0f-75ec-4e9d-8c5f-075bc8ad340a.png)

**Comment by jesade-vbg** [comment]
@jacobwod I Added the possibility to add all sublayers. Its not pretty in UI, but it works until the new admin is ready and designed.

![image](https://user-images.githubusercontent.com/73874338/201073069-eb2f489e-eba7-4f16-b7a6-51c16b624df0.png)

**Comment by jacobwod** [comment]
That's good! But does that mean that the individual sublayers disappear? Because I think that it would be good to still have an option to select only a subset of them. 😄

**Comment by jesade-vbg** [comment]
The sublayers are added automatically and its possible to remove them as usual.
![image](https://user-images.githubusercontent.com/73874338/201318055-9f4f4745-cf2b-4f32-880d-c45bc8d065fc.png)

It just does what is described missing here:
![image](https://user-images.githubusercontent.com/73874338/201318383-308526ef-08fa-49fd-bead-77abdabe5178.png)
