### ISSUE TITLE
Infoclick does not update value

### ISSUE THREAD

**Issue by hitomin21** [hajkmap/Hajk#797]
The infoclick box does not update the values in the latest version of develop. You have to close the info window and click again to get a refreshed value.

It can be reproduced using the default layers.json and map_1.json with the layer Riksintresse Kulturmiljövård.

**Comment by Hallbergs** [comment]
Got a potential fix ready. See #798

**Comment by jesade-vbg** [comment]
Thanx for finding and fixing this Henrik! Works for us too.
