### ISSUE TITLE
Demo site is not working

### ISSUE THREAD

**Issue by jesade-vbg** [hajkmap/Hajk#799]
**Describe the bug**
The demo site using simpleconfig does not work when making layers visible

Getting "Uncaught AssertionError: Assertion failed. See https://openlayers.org/en/v6.5.0/doc/errors/#52 for details."
when running both at netlify
https://hajk-demo.netlify.app/
and when running locally.

**To Reproduce**
Toggle layer visibility to ON.

**Comment by Hallbergs** [comment]
Cant't reproduce either locally or on netlify... Weird. Do you mean that we get a crasch if you simply toggle a layer in the layer switcher? 

![image](https://user-images.githubusercontent.com/43059093/118432061-fc2d8e80-b6d7-11eb-8951-a088e19399c2.png)

**Comment by jesade-vbg** [comment]
Yes exactly. Can't get it to work. It crashes on all devices I've tested on both fiber and 4g.

**Comment by Hallbergs** [comment]
Alright. Just got the same problem on my Iphone 11, and can't seem to reproduce on my desktop unfortunately. 

The "serverType" for these layers is set to "arcgis", which isn't supported by openLayers. See following image:
![image](https://user-images.githubusercontent.com/43059093/118435112-8d076880-b6de-11eb-91a3-0c78430839a7.png)

The serverType prop is only used when hiDpi is set to true, which might explain why i can only reproduce on my phone. The weird thing is that the demo-site worked on my phone just a couple of days ago...

**Comment by Hallbergs** [comment]
My guess is that "serverType" should be set to "mapserver" for these "arcgis-layers". Maybey you could do some quick tests since you've got the error locally?

**Comment by jesade-vbg** [comment]
Ok, the error has suddenly disappeared on desktop... (server changes?) But still a problem on mobile. I made a quick test locally in chrome device emulator, setting pixelratio to 3, and the error appeared again. In configmapper I tested:
```
if (config.options.serverType === "arcgis") {
  config.options.serverType = "mapserver";
}
```
and it started working again in device emulator.
