### ISSUE TITLE
Kartan blir vit när man panorerar/zoomar med musen

### ISSUE THREAD

**Issue by jacobwod** [hajkmap/Hajk#80]
_Update 2017-11-24_ 
Kartan fungerar korrekt när man kommenterar bort rad 79 i mapmodel.js.
`//extent: this.get('extent').length != 0 ? this.get('extent') : undefined`

**Vid ytterligare undersökning har jag konstaterat att det har med konfigurationen av extent (i map_x.json) att göra.** Om värdet för `extent` sätts till exakt samma värden som för någon av `projections` så fungerar kartan korrekt. (Jag har testat med EPSG:3008 och värden `extent = [60857.4994, 6120098.8505, 223225.0217, 6906693.7888]`.)

_Ursprunligt inlägg_
Testade a94ef3f och där var allt OK.
I commit df87325 uppstår buggen.

![image](https://user-images.githubusercontent.com/110222/32951983-0cebc6e4-cbac-11e7-80ed-05aa94fc6627.png)

**Kortfattad beskrivning av buggen**
Bakgrundskarta och lager laddas när användaren laddar sidan och allting visas. Så fort användaren gör något med musen som kräver att kartan ritas om så uppstår buggen och kartområdet blir vitt. Det räcker alltså att användaren trycker, håller och flyttar kartan med musen (dvs panorerar) eller zoomar med scroll-hjulet. 

Om användaren däremot använder + och - knapparna för att zooma så ritas allting korrekt. 

När buggen har uppstått och kartan är vit så kan användaren återfå kartan genom att trycka på GPS-knappen. Då ritas kartan om korrekt, med den nya zoominställningen och panoreringen. 

**Steg för att återskapa**
_Förhandkrav: Ha en lokal version igång på IIS (för att nyttja mapservice och admin därifrån). Du ska kunna nå localhost:80 och se en karta._

1. Checka ut pre-release
2. Kör följande:
```
cd client
npm install
grunt dependencies
grunt build
grunt debug
```
3. Surfa in på localhost:9000. Kartan ska se ut precis som på localhost:80, men nu använder du /client-delen som byggdes nyligen från pre-release.
4. Flytta kartan lite eller används musens scrollhjul för att zooma. Kartan blir vit.
5. Se till att du har GPS-verktyget tillgänligt (om inte, aktivera det i /admin).
6. Tryck på GPS-verktyget för att positionera. 
7. Kartan ritas nu fint igen.
8. Testa nu att zomma med knapparna + och -. Det fungerar utmärkt, kartan ritas fint.
9. Testa att zooma med musen. Kartan blir vit igen.
10. Tryck på GPS-knappen igen för att kartan ska synas.

Jag felsökte vidare och ser att anropen går ut till WMS-en. Felet fanns inte i version a94ef3f som fungerade bra. Du kan testa det genom att checka ut specifikt den versionen. 

1. Ange följande:
`git checkout a94ef3f `
2. Se till att du står i /client-mappen och gör om stegen i steg 2 (npm install och alla grunt-kommandon).
3. Testa kartan igen. Allt fungerar bra.

**Comment by jacobwod** [comment]
Min fix för att grunt debug ska fungera på localhost:9000 kom först i en senare commit, så för att ni ska kunna testa behövs följande i filen Gruntfile.js på rad cirka 300:
```
proxy: {
        proxy1: {
          options: {
            port: 9000, // We will access debug environment through localhost:9000
            router: {
              'localhost/mapservice': 'http://localhost:80/mapservice/', // Create a virtual route on 9000 that redirects to IIS' /mapservice. NB: Make sure to have IIS running! //localhost/mapservice must be available.
              'localhost/postProxy.aspx': 'http://localhost:80/postProxy.aspx', // proxy runs on IIS too, so it isn't available on port 9000. Since it isn't in /mapservice subdir, we need to be explicit about it
              'localhost': 'http://localhost:3000' // Redirect all request from 9000 to 3000, since /mapservice is not available on 3000 but only via the virtual route on 9000.
            },
            changeOrigin: true
          }
        }
      },
```

**Comment by persoderstrom** [comment]
Hej Jacob,

Ledig idag men råkade kolla min mail. Jag gjorde en ändring den 16 oktober i hanteringen av bakgrundskartor, men om anropet sker till rätt wms så bör det inte vara den som är boven. Vi har kört med den fixen sedan dess utan problem, men det kan ju vara beroende av olika inställningar i layers eller Map json. Får kolla vidare på måndag...

Trevlig helg!

Med vänlig hälsning
Per Söderström
Kungsbacka kommun

17 nov. 2017 kl. 15:31 skrev Jacob Wodzyński <notifications@github.com<mailto:notifications@github.com>>:


Testade a94ef3f<https://github.com/hajkmap/Hajk/commit/a94ef3f4719638b30df609f68a8cf9693c6f8744> och där var allt OK.
I commit df87325<https://github.com/hajkmap/Hajk/commit/df87325ae6e9163716ea0fc33fc2cbbd44045d89> uppstår buggen.

[image]<https://user-images.githubusercontent.com/110222/32951983-0cebc6e4-cbac-11e7-80ed-05aa94fc6627.png>

Kortfattad beskrivning av buggen
Bakgrundskarta och lager laddas när användaren laddar sidan och allting visas. Så fort användaren gör något med musen som kräver att kartan ritas om så uppstår buggen och kartområdet blir vitt. Det räcker alltså att användaren trycker, håller och flyttar kartan med musen (dvs panorerar) eller zoomar med scroll-hjulet.

Om användaren däremot använder + och - knapparna för att zooma så ritas allting korrekt.

När buggen har uppstått och kartan är vit så kan användaren återfå kartan genom att trycka på GPS-knappen. Då ritas kartan om korrekt, med den nya zoominställningen och panoreringen.

Steg för att återskapa
Förhandkrav: Ha en lokal version igång på IIS (för att nyttja mapservice och admin därifrån). Du ska kunna nå localhost:80 och se en karta.

  1.  Checka ut pre-release
  2.  Kör följande:

cd client
npm install
grunt dependencies
grunt build
grunt debug


  1.  Surfa in på localhost:9000. Kartan ska se ut precis som på localhost:80, men nu använder du /client-delen som byggdes nyligen från pre-release.
  2.  Flytta kartan lite eller används musens scrollhjul för att zooma. Kartan blir vit.
  3.  Se till att du har GPS-verktyget tillgänligt (om inte, aktivera det i /admin).
  4.  Tryck på GPS-verktyget för att positionera.
  5.  Kartan ritas nu fint igen.
  6.  Testa nu att zomma med knapparna + och -. Det fungerar utmärkt, kartan ritas fint.
  7.  Testa att zooma med musen. Kartan blir vit igen.
  8.  Tryck på GPS-knappen igen för att kartan ska synas.

Jag felsökte vidare och ser att anropen går ut till WMS-en. Felet fanns inte i version a94ef3f<https://github.com/hajkmap/Hajk/commit/a94ef3f4719638b30df609f68a8cf9693c6f8744> som fungerade bra. Du kan testa det genom att checka ut specifikt den versionen.

  1.  Ange följande:
git checkout a94ef3f
  2.  Se till att du står i /client-mappen och gör om stegen i steg 2 (npm install och alla grunt-kommandon).
  3.  Testa kartan igen. Allt fungerar bra.

**Comment by jacobwod** [comment]
@persoderstrom, jag tror inte att din kod har påverkat såvida du inte checkade in i Göteborgs branch tidigare. Av allt att döma så uppstår detta i version df87325, men fler får gärna testa och verifiera.

**Comment by jacobwod** [comment]
# Uppdaterad problembeskrivning
Jag har undersökt vidare och konstaterat att buggen som uppstår i df87325 endast uppkommer när man kör sin utvecklingsversion (alltså med 'grunt debug'). Om man istället tar och kopierar över filerna och sätter upp det i en IIS-lösning så fungerar kartan som vanligt.

Bugggen är alltså inte en deal breaker kanske, men är fortfarande problematiskt eftersom det kommer att avsevärt försvåra utvecklingen framöver, om man efter varje förändring ska behöva kopiera filerna till mappen där IIS-delen är uppsatt. Dessutom omöjliggörs debug så vitt jag vet. 

En möjlighet (som är otestad av mig) är att det har med Node 8 att göra. (Jag har inte kunnat testa med Node 6.) Men även om buggen endast uppkommer i nya Node så är det ett problem som vi måste hantera nu om vi ska kunna uppgradera våra paket till nya versioner - många kräver aktuell Nodeversion.

Jag anser att vi bör fortfarande se vad det är som har hänt, om det är endast i nya Node som det uppkommer, och försöka lösa problemet för att kunna köra Hajk i en aktuell miljö även fortsättningsvis.

# Förslag på tillvägagångsätt vid test
Det vore bra om någon mer kunde se om ni får samma problem. Förutsättningen att ni har en fungerande Hajk på localhost redan, uppsatt i IIS och igång. Testa genom att försöka nå http://localhost. När det finns så gjorde jag såhär för att checka ut och versionen som där buggen uppstår:

> git clone -b pre-release https://github.com/hajkmap/Hajk.git
cd Hajk/client/
npm install
grunt dependencies
grunt build
grunt debug

När jag nu går in på http://localhost:9000 och zoomar med musen eller panorerar så uppstår buggen. 

För att verifiera att det fungerade i tidigare versioner gör vi såhär:
> Ctrl+C // stoppa 'grunt debug'
cd .. // gå upp till huvudmappen
git checkout -f a94ef3f4719638b30df609f68a8cf9693c6f8744 // den sista versionen som fungerar bra i 'grunt debug'
cd Hajk/client/
npm install
grunt dependencies
grunt build
grunt debug

Gå återigen på http://localhost:9000 och testa kartan. Zoom och panorering fungerar bra. 

Får ni samma resultat?

**Comment by jacobwod** [comment]
Jag gick igenom ändringarna som tillkom i version df87325 _rad för rad_.

**Kartan fungerar korrekt igenom när man kommenterar bort rad 79 i mapmodel.js.**
`//extent: this.get('extent').length != 0 ? this.get('extent') : undefined`

Ska tittade vidare på vad det egentligen gör och hur man kan ha med funktionaliteten utan att buggen uppstår när man testar i Node.

**Comment by jacobwod** [comment]
Vid ytterligare undersökning har jag konstaterat att det har med konfigurationen av extent (i map_x.json) att göra. Om värdet för extent sätts till exakt samma värden som för någon av projections så fungerar kartan korrekt. 

Jag har testat med EPSG:3008 och värden extent = [60857.4994, 6120098.8505, 223225.0217, 6906693.7888].
