### ISSUE TITLE
Invertera not working in coordinate tool

### ISSUE THREAD

**Issue by hitomin21** [hajkmap/Hajk#807]
It seems like the invertera setting for a transform is ignored in the coordinate tool. The order of the coordinates are not swapped regardless of the value specified in admin.

**Comment by FredrikEkstrom79** [comment]
Is this realy inverted? seems to be only the order the values are presented to the user that is changing.
![image](https://user-images.githubusercontent.com/50202826/124099097-771af080-da5d-11eb-8529-9ac30747b6d9.png)
![image](https://user-images.githubusercontent.com/50202826/124099165-869a3980-da5d-11eb-8a23-bc144b9e2925.png)

**Comment by jacobwod** [comment]
Good find! I agree: just shifting the display order is not the same as inverting axis.
