### ISSUE TITLE
Feature props output filters/formatting

### ISSUE THREAD

**Issue by varberg** [hajkmap/Hajk#820]
The idea is to make it possible to format the data before rendering in infoClick.
Alot of data is already formatted from database but we think the presentation-layer (Hajk) should also have basic possibilities.

As a start, a basic set of filters will be availiable.
But it will be pretty easy to create new.

Varberg has already developed the base functionality and a set of filters.

**A simple example would be pipe into filter "left":**
`{'property value' | left(' ')}`
Outputs: "property"

**You can also chain pipes:**
`{'property value' | left(' ') | capitalize}`
Outputs: "Property" (Uppercase on first char)

**Are you getting unwanted chars in date?:**
`{'2021-06-03T13:04:12Z' | datetime}`
Outputs: "2021-06-03 13:04:12"

**But we should not output time....**
`{'2021-06-03T13:04:12Z' | date}`
Outputs: "2021-06-03"

**Getting too many decimals? Use roundToDecimals.**
`{'45.32465456'|roundToDecimals(2)}`
outputs: 45,32

**Maybe you need to output a default value if data is empty?**
`{''|default('0')}`
outputs: '0'

**Getting true/false values? Lets show the user better values by using "replace"**
Example:
`{'true'|replace('true','Yes','No')}`
outputs: "Yes"

Availiable filters when this issue is written:
- roundToDecimals
- replace
- default
- equals
- notEquals
- datetime
- date
- time
- formatNumber
- toUpper
- toLower
- capitalize
- substr
- substring
- left
- right
- trim

See FeaturePropsFilters.js for more examples.

Branch: https://github.com/hajkmap/Hajk/tree/feature/820-FeaturePropsFilters

**Comment by jacobwod** [comment]
Definitievly a nice addition!

A couple of things to keep in mind:

1. I ran into an issue that I'm sure you will see too: the character you pick as your magic character (the pipe, `|`), can occur inside the string we get from DB. In my case, I have equal sign as a special character in the if-syntax, and I solved it this way, see fb0240cdf2ba94f261cb8fefb96078885e694a67. I'm sure you must do something similar: ensure that whatever is printed inside your `{}` doesn't contain any other pipe characters, but in the same time you must allow them, so a encode+decode is needed.
2. I understand your examples show the parsed strings. But what is the syntax in real life? E.g. what do admins write in infoclick settings to get `{'2021-06-03T13:04:12Z' | datetime}`, is it `{valueFromDBTable | datetime}`, or `{{valueFromDBTable} | datetime}`, or something else?
3. I'm not sure I see the point of append and prepend. I mean, you can do `this will be prepended to {someValue} while this will get appended` already with the current solution. 😄

**Comment by jesade-vbg** [comment]
1. split('|') occures first, before the value is fetched from properties[key]. I dont't think this will be an issue, but I could be wrong.
2. use {propertyKey | datetime}, just as in {propertyKey}. 
3. Correct 😄 I had an idea at first but it dissappeared on the way. Maybe prependIfValue and appendIfValue. But I'll remove it for not.

**Comment by jacobwod** [comment]
1. OK that should work. The reason I ran into this is that I want to "take whatever the value of foo is and compare it against bar". If foo contained a `=` character, it could be misinterpreted by the regex as my actual comparison and mess things up.
2. That's great.
3. I think this aims to solve the same problem as "my" if-statement. `"Print 'hello foo' if foo exists".` The way I've solved it is with <if foo>Hello {foo}</if>, because that gives the ability to print not only the value of `foo` but also surround it by any or none text before/after. If you can find a simpler syntax, it'd be great. But if not, we can go with the if-statement as it's implemented now.

**Comment by jesade-vbg** [comment]
Ok great! I have no better idea regarding #3, your "if" is working great.

**Comment by jacobwod** [comment]
I'll look into the PR, please see comments in that thread! 😄

**Comment by jacobwod** [comment]
Once it's merge, please don't forget to add some user docs. The examples from this issue description would be fit perfectly [somewhere here](https://github.com/hajkmap/Hajk/wiki/Infoklick#administration).

**Comment by jesade-vbg** [comment]
Great! Thanx! Yes I'll write some documentation.

**Comment by jacobwod** [comment]
Hi @jesade-vbg, what's the status on the docs? I get repetitive requests from the admins about the syntax for the filters, it would be really nice to have some description/examples. Probably the best place to go is here, https://github.com/hajkmap/Hajk/wiki/Infoklick, but feel free to disagree. :)

**Comment by jesade-vbg** [comment]
Sorry for the delay. It was missing on my todo-list. Now added.

**Comment by jesade-vbg** [comment]
@jacobwod 
Added some docs here:
https://github.com/hajkmap/Hajk/wiki/Infoklick#hajk-specifika-markdown-filter-och-formateringsfunktioner

**Comment by jacobwod** [comment]
It's in 3.7 RC 1, closing this issue.
