### ISSUE TITLE
Add a generic proxy to the backend

### ISSUE THREAD

**Issue by jacobwod** [hajkmap/Hajk#824]
# Introduction
There are many cases where admins need to reach internal systems that backend has access to, but we don't want to expose them to the public externally. Usually organizations would setup a robust proxy solution to handle this. But there are use cases where it'd be handy to have a basic, built-in proxy available from start. This issue attempts to do just that.

# Proposed solution
In `.env` we specify what _context_ should be used to rewrite URLs to specific _target_. The terminology is exactly the same as in https://github.com/chimurai/http-proxy-middleware.

The proxy key in `.env` must start with `PROXY_`.  Whatever comes after `PROXY_` becomes the _context_, while the value of the key is the _target_.

Admins can specify any number of context/target pairs in `.env`. 

# Example
We want to make a request to `http://internal.server.local:8080/ogc/osm?service=WMS&request=GetCapabilities`.

We add this proxy definition in `.env`: `PROXY_QGISSERVER=http://internal.server.local:8080`

With a Hajk backend running on localhost, port 3002, we can now request: `http://localhost:3002/api/v1/proxy/qgisserver/ogc/osm?service=WMS&request=GetCapabilities`. This will be rewritten by the proxy and invoke `http://internal.server.local:8080/ogc/osm?service=WMS&request=GetCapabilities` instead. 

## Illustration
```
http://localhost:3002/api/v1/proxy/qgisserver/ogc/osm?service=WMS&request=GetCapabilities
\                                /\          /\                                          /
               |                        |                          |
          Hajk backend URL           Context             Request to be proxied
```

**Comment by Hallbergs** [comment]
Awesome!
