### ISSUE TITLE
Print: Show the chosen paper format next to selected scale

### ISSUE THREAD

**Issue by jacobwod** [hajkmap/Hajk#858]
Currently a PDF printout from the Print plugin will include a scale. This is unfortunately not enough to recreate a physical print that holds up to the scale. One piece of information is missing: the chosen page format. 

Adding the information next to scale line should be enough to inform the user about how to print in order to keep preserve the scale.
![Skärmavbild 2021-09-06 kl  10 44 39](https://user-images.githubusercontent.com/110222/132187905-547500b8-1dd2-465d-b0e6-f84ba3b10b1d.png)

**Comment by jacobwod** [comment]
Here's the upcoming solution:
![Skärmavbild 2021-09-07 kl  10 35 45](https://user-images.githubusercontent.com/110222/132312875-fe7d7342-869f-4e9c-968c-d48a1fbd9cba.png)

**Comment by Hallbergs** [comment]
I like it!
