### ISSUE TITLE
Symbols for vector layers not working

### ISSUE THREAD

**Issue by perosoderstrom** [hajkmap/Hajk#878]
**Describe the bug**
Vector symbols with offset can be used when you want a pointer symbol 
to point exactly at the spot.

In Hajk 3.2 it was possible to set a symbol for points in vector layers. 
You could also set an X/Y Offset for the symbol. 

When uppgrading to Hajk 3.7 the symbols does not show on the map.

**To Reproduce**

1. In admin add a vector layer "Vektorlager" with points and data format WFS.
2. Set an "Ikon": i.e. https://karta.kungsbacka.se/publik/assets/map_icons/forskolor.svg
3. Notice that there are no fields in admin for X/Y Offset of the symbol.
4. Add the vector layer to a map.
5. When you open the map and turn the layer visible, no symbols are shown.

**Expected behavior**
Symbols whith a given offset should appear on the map.

**Screenshots**
1. Hajk 3.2 map with vector symbols
![Hajk 3 2 karta med vektorsymboler](https://user-images.githubusercontent.com/51197693/137288015-e3127b23-6e91-44ca-bf01-0ba52fa672e8.png)

2. Hajk 3.2 Admin 
![Hajk 3 2 admin](https://user-images.githubusercontent.com/51197693/137288098-275f1f32-d8d1-4f90-abc9-a31c30ec2e0f.png)

3. Hajk 3.7 Admin
![Hajk 3 7 admin](https://user-images.githubusercontent.com/51197693/137288140-d5e60e92-cb53-4c25-8687-e9f3dc833c2b.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: any

**Additional comments**
This might have been changed in "Feature/592 snap interaction #598" commit.

**Comment by jacobwod** [comment]
Hi @perosoderstrom, thank you for such a detailed description! It surely helps me to track down this bug, I'll take a look as soon as I have a chance. Great find! 👍 😄

**Comment by jacobwod** [comment]
> Yes, a default marker.
> ![Hajk 3 7 vektorlager med default symboler](https://user-images.githubusercontent.com/51197693/139062210-1d0c9383-bc50-4832-a162-ec37f97d6d5c.png)

OK, so you do get the default marker. Have you tried specifying the marker in the URL too? Try with absolute URL, make sure that you don't get 404 in the Network tab too. I'm pretty sure you will see your marker, it's possible to set that in Admin UI. 

The offsets however are missing. It that what you want to add?

**Comment by perosoderstrom** [comment]
@jacobwod Yes. The reason for using vector layers with symbols is the (previous) possibility to offset the symbol.

**Comment by jacobwod** [comment]
It's a minor tweak in Admin UI, and then you'd need to read those options and pass on by to the ol.Style. Feel free to fix!

**Comment by perosoderstrom** [comment]
Thanx, @jacobwod! I will look into this.
