### ISSUE TITLE
Add QGIS Server tolerance parameters for GetFeatureInfo in Admin

### ISSUE THREAD

**Issue by eri-blan** [hajkmap/Hajk#885]
**Is your feature request related to a problem? Please describe.**
This is related to #852. In our setup, the hardcoded values result in a lot of extra hits. Removing these parameters seem to give reasonable results. 

**Describe the solution you'd like**
To put these as settings in admin somewhere, as is mentioned in the code.  

**Describe alternatives you've considered**
Lower or comment the settings out and build without them.

**Additional context**
The yellow highlighted building is the one that is clicked on. I believe it is reasonably zoomed in.
![image](https://user-images.githubusercontent.com/92728323/138449314-0ca1981a-ba96-4c81-8355-8ba0f24cdfe2.png)

**Comment by Hallbergs** [comment]
It seems like the @eri-blan QGIS-server setup differs from @jacobwod QGIS-server setup? If i understand it correctly, everything seems to work as expected if you don't include the tolerance values, @eri-blan, and in @jacobwod setup he must include the tolerance? Maybe we should investigate if this is a setting in QGIS-server, to avoid bloating the Admin UI with more settings?

**Comment by jacobwod** [comment]
Exactly, although I wouldn't have a problem with a layer like the one in @eri-blan's example, as we have Polygon features there. The tolerance is needed for Line or Point features: managing to click _exacly_ right on those ones is quite difficult. 😅 

But you don't have any problems clicking on Point features either, even without tolerance, @eri-blan?

**Comment by eri-blan** [comment]
It seems to work OK even with points or lines here without setting the tolerance parameters, atleast in my experience. I agree it would be good to investigate why there seems to be a discrepancy.

**Comment by jacobwod** [comment]
@eri-blan Anything in the project file settings dialog that you can think of that would control this? (It should be part of GetFeatureInfo somewhere in the WMS settings I guess.)

**Comment by jacobwod** [comment]
I will have a look at this perhaps in 3.13. We also get far more hits than expected, now on QGIS Server 3.24. I'll either remove or make this a setting. How about your experience @eri-blan, did you just remove those or are you sending in any other hard-coded values?

**Comment by eri-blan** [comment]
@jacobwod I hard code the values to 5 instead for points and lines, and remove the value for polygons. Setting the point/line tolerance parameters to 0 still makes objects hard to get a hit for, if I remember correctly.

**Comment by jacobwod** [comment]
Same as my experience now. How about making it a setting with the following syntax? 

![Skärmavbild 2023-07-04 kl  15 32 26](https://github.com/hajkmap/Hajk/assets/110222/1db744b0-be83-4f3e-b281-b198b319a9ce)

**Comment by eri-blan** [comment]
Sounds good to me 👍
