### ISSUE TITLE
Internal layer names in admin interface

### ISSUE THREAD

**Issue by hitomin21** [hajkmap/Hajk#887]
We would like to be able to specify custom layernames (called internalName) to be used when displaying the name of the layer in the admin interface. As it is now, we have several layers with the same caption (and want the same caption for client side) and is therefore indistinguishable from each other in parts of the admin interface (kartinställningar, etc.).

The attribute would be set in the layers menu and ff no internal layername is specified, the caption will be used for displaying the layer name as in the current behavior. No changes are intended for the client side.

@jacobwod @Hallbergs: Can I start developing this?

**Comment by jacobwod** [comment]
Hi @hitomin21, what's the status here?

**Comment by jesade-vbg** [comment]
We are currently testing. And initial tests looks promising. 👍

**Comment by jacobwod** [comment]
Where? 😄 I'd like to try it out too.

**Comment by jesade-vbg** [comment]
Maybe @Hitomin hasnt pushed it to branch yet. Hitomi and me are not working today so I think you'll need to wait for next week.

**Comment by hitomin21** [comment]
I have pushed the changes to this branch
https://github.com/hajkmap/Hajk/tree/feature/887-internallayernames

**Comment by hitomin21** [comment]
I am currently merging with the latest from develop

**Comment by hitomin21** [comment]
Hopefully completed now, we will do a final internal testing before I submit a pull request. Would be nice if someone could test with an arcgislayer.

**Comment by hitomin21** [comment]
@jacobwod if you want to try, just modify "visningsnamn admin" in admin in this branch.

![bild](https://user-images.githubusercontent.com/22234673/145590455-e9d104e1-b7fb-4987-b02b-a81cdf6f66c5.png)

**Comment by jacobwod** [comment]
It's merged to `develop`, but we've found the following issue.

**Steps to reproduce**
1. Add an internal name to a layer and save
2. The name gets saved and is now shown in Admin list
3. Select another layer that _doesn't_ have a custom internal name yet (the key is missing in JSON file)
4. The previously added internal name, from step 1, is shown as internal name here too.

**Expected results**
The internal name field should be empty.

We've reproduced this across different users. Can you take a look @hitomin21?

---

Internal name added, show up correctly:
![Skärmavbild 2022-01-11 kl  13 18 39](https://user-images.githubusercontent.com/110222/148941393-3e482cb6-bb53-4269-ab71-df6ca34959b2.png)

---

No internal name yet, show the previous layer's internal name:
![Skärmavbild 2022-01-11 kl  13 18 49](https://user-images.githubusercontent.com/110222/148941388-68e0d5b0-fca7-4f92-a4bf-4729c52c622a.png)

**Comment by FredrikEkstrom79** [comment]
A suggestion for future improvements would be nice to see the schema and table name
Even with unique names in admin (which is good) this will add much more clarity to what the name points to without clicking on it to see the schedule and table name.
![preview](https://user-images.githubusercontent.com/50202826/148945873-62365a5f-9071-42d8-8bbd-7f3bf343bd68.png)

**Comment by jesade-vbg** [comment]
@jacobwod  & @hitomin21. 
I've fixed the "tripp trapp" issue above. Pushed to dev.

**Comment by jacobwod** [comment]
Well done @jesade-vbg, seems to work good here now. 👍 

I think we can consider this closed. I moved @FredrikEkstrom79's comment to a separate issue as it really is a further improvement of the original and would be nice to see some time in the future.
