### ISSUE TITLE
TLS support for LDAP (Active Directory) in Backend

### ISSUE THREAD

**Issue by jacobwod** [hajkmap/Hajk#893]
The current AD functionality is limited as it only works with the ldap:// protocol. The underlying libraries, however, do support secure connections. 

**Hajk's backend should be extended to make it possible to provide necessary TLS certificate files, read them, and establish a secure connection to LDAP via TLS.**

**Comment by larsam0524** [comment]
What TLS-version are supported from Node-backend? (maby OT)

**Comment by jacobwod** [comment]
I think it depends on which version of NodeJS you're running, @larsam0524 . Please see the [official documentation](https://nodejs.org/api/tls.html). Perhaps there is some more specific information there.
