### ISSUE TITLE
MF Integration: Set up a KUBB connection

### ISSUE THREAD

**Issue by sweco-semtto** [hajkmap/Hajk#903]
Configure a KUBB connection to EDP Vision with a SignalR connection. This connection must use a HubProxy "GisAndRealEstate". 

Implement support for: 
* Receive real estates (HandleRealEstateIdentifiers)
* Send real estates (SendRealEstateIdentifiers)
* Receive coordinates (HandleCoordinates)
* Send coordiantes (SendCoordinates)

**Comment by Hallbergs** [comment]
Could you please elaborate? It would be nice with some clarifications on what you're planning to implement.

**Comment by sweco-semtto** [comment]
Sure. I'm home and I'm sick today. That is the reason for the really short description. Can I update it on Monday with our requirements?

**Comment by Hallbergs** [comment]
Alright, great. Yes of course. While you're at it, please update #904, #865, and #862 as well.

**Comment by jacobwod** [comment]
Can we close this one @Hallbergs @sweco-semtto?
