### ISSUE TITLE
MF Integration: Coordinates with KUBB

### ISSUE THREAD

**Issue by sweco-semtto** [hajkmap/Hajk#904]
Implement the coordinate functions supported by EDP Vision in Hajk. 

* Coordinates that are linked to an entry in EDP Vision are highlighted and zoomed in to the map. 
* Coordinates that are linked to objects and filtered out by EDP Vision are highlighted and zoomed in on the map.
* Placed coordinates, e.g. from clicking on the map, is collected and loaded into EDP Vision.

**Comment by Hallbergs** [comment]
Could you please elaborate? It would be nice with some clarifications on what you're planning to implement.

**Comment by jacobwod** [comment]
Can we close this one @Hallbergs @sweco-semtto?
