### ISSUE TITLE
Print plugin - print all map scales in highest dpi

### ISSUE THREAD

**Issue by jesade-vbg** [hajkmap/Hajk#908]
If your map have scales (psuedo, its called resolutions in config)
500, 1000, 2000, 5000, 10000, 20000, 50000, 100000, 200000, 300000

And print plugin has scales 500, 1000, 2000, 5000, 10000, 20000, 50000, 100000, 200000, 300000.
And dpi 90 and 150 availiable.

You can only print scale 500 in 90 dpi.

Goal with issue: Be able to print scale 500 in 150 dpi or more accurate,
be able to print all map scales in highest dpi.

This is possible if you add scale 200 to the allowed scales for the map.
But, now you cant print 200 in 150dpi only in 90dpi.
And also, we dont want it to be possible to zoom to 200.

------------------------------------------------------

How would we achieve this? (Discussion):

Thoughts:
Map could have secondary resolution array with the additional scale 200.
All layers use the secondary resolutions if availiable. (today all layers gets resolution from map config)
The map has primary resolution array to prevent zooming to 200 (max 500).
When printing, the maps view is changed to a view that uses the secondary resolution array.
This makes it possible for print plugin to zoom to 200 to get a 500 scale print with 150dpi.

Maybe this could work and we should never see the red text "lower your dpi settings" again.

**Comment by jesade-vbg** [comment]
I hope the above makes sense :sweat_smile:

**Comment by Hallbergs** [comment]
I like your idea! It should get the job done!
