### ISSUE TITLE
hfetch should be able to handle both Strings and Objects.

### ISSUE THREAD

**Issue by jesade-vbg** [hajkmap/Hajk#909]
hfetch fails when recieving new URL("https://etcetc.com")
Make it work like the original fetch or at least similar.

Kind of in between bug and feature. But more towards bug.

**Comment by jacobwod** [comment]
FYI: it does work if you don't set any special properties to your HFetch options (i.e. proxy and such). In those situations, where you only pass on the `url` variable to the real `fetch`, there are no problems. So the only part that needs to be fixed is  inside `overrideOptions()`, where you do `indexOf` on `this.url` (which assumes it's a String). Just throw in a quick check there:
```javascript
let urlString = null;
if (this.url instanceof URL) {
  // We've got an URL object, let's grab the String
  urlString = this.url.toString();
}
else if (typeof this.url === "string")
  urlString = this.url;
else 
   throw new Error("Ehh, this.url is neither a String nor a URL Object. Abort all operations!")
   
// …and now do whatever mods you'd like on urlString and returned the modify String.
```

**Comment by jesade-vbg** [comment]
Yes, thanx.
