### ISSUE TITLE
Activating the Edit plugin may affect the look of FeatureInfo

### ISSUE THREAD

**Issue by jacobwod** [hajkmap/Hajk#917]
This needs more investigation, but here's a quick demo of the bug. **Note how the content of our FeatureInfo window gets different styling, depending on whether the `DrawModel`'s layer is active or not.**

https://user-images.githubusercontent.com/110222/142633227-ecdb2fab-2322-4b84-9954-612145cfde6f.mov

----
The affected layer doesn't have to be the same as the one selected in Edit. See the following screenshot where I edit the "outdoor art" layer, while map is showing the "indoor art" layer:

![Skärmavbild 2021-11-19 kl  14 57 57](https://user-images.githubusercontent.com/110222/142634630-4ae88466-7b18-4b9e-8586-9d57ed5d36fe.png)

----

The infoclick definition is the following MD:
<details>
  <summary>Click to expand!</summary>

```markdown
{{if {titel}}}
#### Titel
{titel}{{/if}}

{{if {konstnar}}}
#### Konstnär
{konstnar}{{/if}}

{{if {fotograf}}}
#### Foto
{fotograf}{{/if}}

{{if {bildlank1}}}
#### Bilder
[Större bild](./files/kf/konstkarta/bilder/{bildlank1}.jpg)
![](./files/kf/konstkarta/bilder/{bildlank1}_thumbnail.jpg)
{{/if}}

{{if {bildlank2}}}
[Större bild](./files/kf/konstkarta/bilder/{bildlank2}.jpg)
![](./files/kf/konstkarta/bilder/{bildlank2}_thumbnail.jpg)
[Länk]({bildlank2}){{/if}}

{{if {bildlank3}}}
[Större bild](./files/kf/konstkarta/bilder/{bildlank3}.jpg)
![](./files/kf/konstkarta/bilder/{bildlank3}_thumbnail.jpg)
[Länk]({bildlank3}){{/if}}

{{if {modell}}}
#### 3D-modell
{modell}{{/if}}

{{if {artal}}}
#### Årtal
{artal}{{/if}}

{{if {material}}}
#### Material
{material}{{/if}}

{{if {placering}}}
#### Placering
{placering}{{/if}}

{{if {information}}}
#### Information
{information}{{/if}}
```
</details>

**Comment by jesade-vbg** [comment]
This was a weird one :)

**Comment by jacobwod** [comment]
I can confirm that this happens both with services from GeoServer and QGIS Server. And all possible layers, as long as they're styled with MarkDown. Can anyone confirm or deny? 

https://user-images.githubusercontent.com/110222/142838772-c1c31e3d-70ca-40b0-a8af-8d3205ae1928.mov

**Comment by jacobwod** [comment]
I've investigated further and the element doesn't re-render: in my case the heading is a H4 all the time. So it seems that the styling (JSS) from the Edit plugin "leaks" in some way to other plugins and re-styles them in view. See below.
![Skärmavbild 2021-11-22 kl  10 50 42](https://user-images.githubusercontent.com/110222/142839884-0e542510-97ec-4d72-b60e-44a6bf5d1f14.png)
![Skärmavbild 2021-11-22 kl  10 50 32](https://user-images.githubusercontent.com/110222/142839891-04e9c68d-abe0-4c2a-b8ec-9b6977e0fd30.png)

**Comment by Hallbergs** [comment]
Yes i can also see the issue. Seems as the overriding-styles in <FeatureInfo /> is replaced with the "standard-styles". I can only see one thing that might lead to this; we're accessing the theme-object in a function in /Edit/components/Toolbar.js (`getSelectedStyle`).

**Comment by jacobwod** [comment]
I've tried returning an empty object from `getSelectedStyle` but it did not change anything. You got me thinking, however, and I've nailed it down to this row:
https://github.com/hajkmap/Hajk/blob/ddfb56c662a3ed18c1dde4706b933919720ab162/new-client/src/plugins/Edit/EditModel.js#L465

Commenting this out fixes the problem, so it's something inside the event handler. I'll take a look.

**Comment by Hallbergs** [comment]
Hmmmm. I don't get how the edit source would affect the styling. I guess it's the re-render happening when setting the state there that shows some change. Maybe we can look at it after lunch?

**Comment by Hallbergs** [comment]
It seems as the css-overrides that we are applying in the feature-info are overridden when we are rendering a <Typography /> in the Edit-plugin. I don't think this is a new bug, and with that in mind, maybe we can implement the fix in the MUI5-migration?

**Comment by jacobwod** [comment]
Sure, this will wait until after the migration!

**Comment by jacobwod** [comment]
So the initial problem, where FeatureInfo was affected, is **solved in the MUI 5 version**. I'm closing this right now.

Another issue has emerged however, see the following video. I think I'll move it to an issue of its own.

https://user-images.githubusercontent.com/110222/149768305-430014b4-7679-4514-873a-5954015631f1.mov
