### ISSUE TITLE
Help button/functionality

### ISSUE THREAD

**Issue by WCarlsson** [hajkmap/Hajk#922]
**Is your feature request related to a problem? Please describe.**
For new users it can be difficult to know exactly how to use the map or know all the possibilities present in the map.

**Describe the solution you'd like**
A button or similiar to show helpful information with text and pictures and/or links to sites or documents that describe the functionality in the map.

**Describe alternatives you've considered**
Use About map but then links doesnt seem to work at present time and the "help message" and potential "welcome message" (about maps present functionality) would have to be merged into one.

**Comment by Hallbergs** [comment]
Hmm, links in the "About map" seems to work fine for me in 3.8rc1, see image: 
![image](https://user-images.githubusercontent.com/43059093/142977263-a7dfee53-6cf5-45bb-9fef-95c1171cdc9c.png)

I've added links as <a />-tags.

A "Help"-plugin could still be a nice addition though, allowing us to separate the help and map-information.

**Comment by WCarlsson** [comment]
Yes you are quite right! 
The "Help" plugin could essentially be a duplicate of "About map" but with a questionmark icon.
The option to use a link directly when the button is clicked could also be nice.

**Comment by WCarlsson** [comment]
The InfoDialog Plugin that was introduced in an earlier release solves this issue
