### ISSUE TITLE
Change symbol for bookmark or quick link

### ISSUE THREAD

**Issue by WCarlsson** [hajkmap/Hajk#923]
**Is your feature request related to a problem? Please describe.**
Bookmark (Bokmärke) and  quick link (snabbval) uses the same symbol. This makes it confusing if both of the plugins are set as control buttons since you can´t see a difference until you hover or click on them.

**Describe the solution you'd like**
Change the symbol for one of the plugins in order to tell them apart when both are control buttons.

**Describe alternatives you've considered**
If one or both of them are used as a widget or put in the drawer the names show and the fact that they share the same symbol doesn´t impact as much.

**Comment by Hallbergs** [comment]
I agree, one of them must change! Do you have any icon-suggestions? :) (https://mui.com/components/material-icons/)

**Comment by Hallbergs** [comment]
Suggestions: 
- FavoriteIcon
- StarsIcon

**Comment by jacobwod** [comment]
Both would work, I suggest we discuss it on tomorrow's meeting.

**Comment by jacobwod** [comment]
Do you have any preference on this, @WCarlsson, @Hallbergs. Another option could be the "Label" or "LabelImportant" icon.

![Skärmavbild 2021-11-25 kl  11 54 07](https://user-images.githubusercontent.com/110222/143428616-fa894a7c-32c6-43e6-8f14-48e4d749269a.png)

**Comment by jacobwod** [comment]
Or the "FolderSpecial" perhaps?

Now we've got some options… 😄 
![Skärmavbild 2021-11-25 kl  11 55 12](https://user-images.githubusercontent.com/110222/143428777-83e46444-d73f-458a-ac4f-3a718205c417.png)

**Comment by WCarlsson** [comment]
All good options @jacobwod @Hallbergs !
I feel that Bookmarks can keep the current symbol and that we change Quick link to **FolderSpecial** or **BookmarkBorder**

**Comment by Hallbergs** [comment]
A fix coming up!
