### ISSUE TITLE
Create a model in core to handle common Draw functionality

### ISSUE THREAD

**Issue by Hallbergs** [hajkmap/Hajk#931]
To avoid code duplication i suggest that we create a core model that handles common draw functionality. The model can be used trough out the application, and should expose methods for common draw interactions.

Proposed list of exposed methods: 

- `toggleDraw(drawType, settings)`: 
    - Accepts a string and enables/disables a draw interaction with the type supplied. The settings object will allow for changing drawEnd behaviour etc. 
- `setLayer(string)`:
    - Sets (to a existing) or creates a vector source in which the drawn objects will be placed.
- `getExtent()`
    - Returns the extent of the current draw-layer
- And so on... 

Any thoughts on more functionality?

**Comment by Hallbergs** [comment]
The draw-model should handle #933

**Comment by Hallbergs** [comment]
The draw-model is now exposing the following methods: 
<pre><code> - getCurrentExtent(): Returns the current extent of the current draw-layer.
 - getCurrentLayerName(): Returns the name of the layer currently connected to the draw-model.
 - removeDrawnFeatures():  Removes all drawn features from the current draw-source.
 - setLayer(layerName <string>): Sets (or creates) the layer that should be connected to the draw-model.
 - toggleDrawInteraction(drawType, settings): Accepts a string with the drawType and an object containing settings.
 - zoomToCurrentExtent(): Fits the map-view to the current extent of the current draw-source.
 - get/set showDrawTooltip(): Get or set wether a tooltip should be shown when drawing.
 - get/set drawStyleSettings(): Get or set the style settings used by the draw-model.
 - get/set showFeatureMeasurements(): Get or set wether drawn feature measurements should be shown or not.</code></pre>

More interactions will probably be added when i start using the model in the new draw ("Sketch"?) plugin.

**Comment by perosoderstrom** [comment]
I'm not sure this is affecting the core draw model, but we note it here.
In Kungsbacka we have user requests for some more draw features:
- draw arrows
- copy geometries
- edit features symbology and text (issue #412)

**Comment by Hallbergs** [comment]
Arrows, edit-, and copy-functionality will absolutely be a thing in the new draw-plugin!

**Comment by jesade-vbg** [comment]
This looks really promising @Hallbergs !

**Comment by Hallbergs** [comment]
This is (partially) closed as of 62c9fbdaf69176f098cb007ab00aa4dc04c37aa9 (The model is merged to develop). Remember that the model has only been trough minor tests, and will be properly tested when the new draw-plugin ("Sketch") is developed. Closing this for now.
