### ISSUE TITLE
Show coordinate: "Inverted" functionality

### ISSUE THREAD

**Issue by WCarlsson** [hajkmap/Hajk#935]
**Describe the bug**
When adding a coordinate setup in the plugin "Show coordinate"/"Capture coordinate" with inverted coordinates the ability to write your own coordinates or adjust the given coordinates in the number fields does not work.

**To Reproduce**

1. Add a new setup to capture coordinates with inverted coordinates
2. In the client show/capture a coordinate in the map and try to modify one of the coordinates
3. The number you are inputing is incorretly added to the other coordinate field

**Expected behavior**
The same behaviour as when inverted is not checked. The coordinate value should change and the marker move to the appropriate place in the map.

**Desktop (please complete the following information):**
- Browser: chrome, firefox

**Additional context**
X and Y are labeled in a way that is not consistent with X/N and Y/E. Don´t know if this is a labeling miss or if its intented.
It could make it easier to confuse the coordinates.  @jacobwod I checked karta.halmstad.se where the N and E coordinates seem to be switched unless I´m mistaken.

**Comment by jacobwod** [comment]
You're right, this is not working the intended way. 

I checked the code and related issues (#482, #807) and it seems @hitomin21 has been working on this. If I recall correctly @linus-gbg @linusfj @sbk-linus has also been fixing this plugin. Can one of you take a look, please?

**Comment by hitomin21** [comment]
Pushed a fix for this in pull request https://github.com/hajkmap/Hajk/pull/1009

**Comment by jacobwod** [comment]
Well done @hitomin21! 👍
