### ISSUE TITLE
Create a new Draw-plugin (Sketch)

### ISSUE THREAD

**Issue by Hallbergs** [hajkmap/Hajk#945]
The current Draw-plugin lacks several nice-to-have features, and the code is pretty messy. 

Instead of trying to patch the old plugin, i have decided to create a new plugin. The old Draw-plugin will be kept in the code-base (at least until we know that everyone has decided to switch to the new one, given that the new one is be better than the old one ;) ).

The new Draw-plugin (called Sketch) will contain all the old Draw-functionality, as well as:

- [X] Possibility to restore removed features
- [x] Possibility to Edit already drawn features (change style etc.).
- [x] Possibility  to copy drawn features
- [x] Possibility to save sketches (so that users can sketch for a while, save the progress, and then continue on at a later stage).
- [x] Possibility  to draw arrows (and perhaps other "icons", please let me know if you have ideas).
- [x] And more! Let me know if you have ideas!

The new Sketch-plugin will rely on the recently added core model (DrawModel.js), see: #931.

If anyone wants to contribute, just let me know! The progress can be found in [this branch](https://github.com/hajkmap/Hajk/tree/feature/945-new-draw-plugin).

**Comment by WCarlsson** [comment]
Awesome work @Hallbergs , it feels like a big improvement!
I noticed some bugs when moving existing objects . Coordinates does not update properly for points and arrowheads does not follow as expected.
![image](https://user-images.githubusercontent.com/38069156/156347863-66906464-84b5-45d4-b459-9e26e26475d1.png)

**Comment by Hallbergs** [comment]
Thanks for testing it out! Im very surprised to see an error like that. The arrow-heads and coordinates have been updating fine for me. Could you elaborate on what you did before moving the objetcs and how you moved them? Im having troubles replicating.

**Comment by Hallbergs** [comment]
Ahh thanks! Totally missed that case. This will obvoiusly get fixed asap! :D
