### ISSUE TITLE
Different layers IDs in NodeJS and .NET backends

### ISSUE THREAD

**Issue by perosoderstrom** [hajkmap/Hajk#952]
**Describe the bug**
In dotnet backend layer id:s are generated as **int**, and in nodejs backend they are generated as a **random string.** 

The problem with this is when you create layers in admin using nodejs backend, you can't use this layer file (layers.json) in admin with dotnet backend. The layers.json works ok in the client.

I do not consider this a major bug, but it can be a problem if you have to administrate (or test) both backend environments.

**To Reproduce**

1. In a nodejs backend environment, add a layer.
2. Copy layers.json to a dotnet environment
3. Try to add a new layer in the dotnet environment
4. In the browser console you get an error like _". . ./hajk3.8/mapservice/settings/wmslayer 500 (Internal Server Error)"_, and the stack trace points to _SettingsStore.cs._ (Se Additional context below)

**Expected behavior**
Both backend environments should be compatible, at least when handling core functions like layers and maps.

**Desktop (please complete the following information):**

- OS: Win 10
- Browser any
- Version Hajk 3.8

**Additional context**
I haven't dived deep into this but I guess this could be fixed by changing `GenerateLayerId(LayerConfig layerConfig)` in `backend\mapservice\DataAccess\SettingsStore.cs`

**Comment by jacobwod** [comment]
That's right, but I don't think that it was ever intended that one would work with both backends simultaneously. 

However, it's an easy fix. The possible valid layer IDs, from both the old and current solutions are as follow:
```javascript
export const isValidLayerId = (id) => {
  return (
    !Number.isNaN(Number(id)) || // A Hajk layer is considered valid if it's ID is either a Number…
    /^[a-f0-9]{32}$/i.test(id) || // … or a MD5 string (default in the first versions of NodeJS backend)…
    /^[a-z0-9]{6}$/i.test(id) // … or a 6 characters long alphanumeric string (default in current version of NodeJS backend)
  );
};
```

Just make sure that the .NET backend accepts those values too and you're good to go!

**Comment by perosoderstrom** [comment]
You also have to change the handling/comparing of int's to strings in ` internal int GenerateLayerId(LayerConfig layerConfig)`.
But its low priority as most users are using one or the other, not both backends.

**Comment by jacobwod** [comment]
I agree. Still, I'd like to know if anyone using .NET backend intends to fix this in the near future. Otherwise I propose we close it as a `wontfix`for now.

**Comment by perosoderstrom** [comment]
For Kungsbacka it is ok to close it.
