### ISSUE TITLE
GeoSuite Export: Regression in layer config, WFS URLs not configurable

### ISSUE THREAD

**Issue by sweco-semara** [hajkmap/Hajk#957]
**Describe the bug**
When configuring the GeoSuite Export plug-in, WFS vector data sources options from layers.json have lower prio than the tool config which in turn renders the default URL a permanent non-overridable setting.

**To Reproduce**
Try to change the URL of a referenced WFS vector layer. The default will still be used in the plug-in for WFS integration.

1. Go to admin
1. Click on layers
1. Select a WFS layer referenced by the plug-in
1. Edit WFS URL
1. Save updated config
1. Reload the map
1. Use the tool and advance the stepper as far as first WFS query
1. Note by service results in GUI or network tab URL that WFS URL change is not effective

**Expected behavior**
In the last step of reproduce routine, the new URL saved in admin layer config should be used as WFS source.

**Devices and context**
All devices, all contexts.

**Comment by sweco-semara** [comment]
@jacobwod @Hallbergs We have a fix for this regression that will reach you in a PR shortly, could you check that this bug report's selection is OK? E.g. if it's considered offensive to set the HAJK version milestone when reporting, then by all means please revert and sorry in advance if so - still learning in this neighbourhood... :-)

**Comment by jacobwod** [comment]
> E.g. if it's considered offensive to set the HAJK version milestone when reporting, then by all means please revert and sorry in advance if so - still learning in this neighbourhood... :-)

Hi @sweco-semara! By all means, this is a perfectly created issue (and subsequent PR). The description, labeling and milestone are all by-the-book. 

Couldn't be more happy! 😃
