### ISSUE TITLE
Point feature clustering - to use with for ex. georefferenced photo layers

### ISSUE THREAD

**Issue by JakubPelka** [hajkmap/Hajk#963]
**Is your feature request related to a problem? Please describe.**
Municipalities sometimes have big libraries of georefferenced images (for example from drone flights). Right now it is difficult to search for images for some specific region. It is easy to create a point layer, where every point will link to a single image. But if we have 50 000 points it will not look well on the map, and can create some rendering issues. That is why it might be good to cluster point features and present density of images in a clear form as a cluster and/or heatmap.

**Describe the solution you'd like**
Proposed solution is to have a cluster feature in HAJK with possibility to change the view to the heatmap view (optionally)
Cluster OL: https://openlayers.org/en/latest/examples/cluster.html
Heatmap OL: https://openlayers.org/en/latest/examples/heatmap-earthquakes.html
Same solution is available for example in KoboToolbox - that with a click you could change view from point/clusters to heatmap
![image](https://user-images.githubusercontent.com/32998823/146167946-b85c8ba6-29db-4bf8-a39d-e085a222f383.png)

**Describe alternatives you've considered**
Alternatively - just one cluster form without heatmap. Eventually - but it is more complicated it is possible with other solution - like grid that presents all the point features that intersects with a grid. Infoclick on a grid making all data in that range available. But it will not be as precise as needed - big accuracy loss.

**Additional context**
I guess that something similar is already available on https://karta.varberg.se/
![image](https://user-images.githubusercontent.com/32998823/146168610-6276e108-23d9-4c6a-92d9-3eac2fa4782b.png)
but it is not looking good - lacks regularity of a clusterd data so it is not so clear to read - bigger gaps could be useful. No heatmap function.

**Comment by jacobwod** [comment]
How did you implement this in the WMS, @jesade-vbg, @hitomin21?

**Comment by jesade-vbg** [comment]
The clusters are created using SLD in geoserver. I have not created it but I can send you the SDL.

**Comment by jacobwod** [comment]
Great, thank, I'll take a look! 👍

**Comment by jacobwod** [comment]
Btw, I think the _PointStacker_ transformation is very useful as-is and we won't implement the vector-based solution anytime soon (if the WMS solution works out well). 

This will probably get closed soon, to avoid stale issues.

**Comment by jacobwod** [comment]
@JakubPelka and anyone else interested in stacking features in WMS layers: please refer to the SLD's [PointStacker transformation](https://docs.geoserver.org/latest/en/user/styling/ysld/reference/transforms.html#point-stacker). 

Closing, feel free to refer or reopen if this will be implemented for vector features anytime.

**Comment by ingvar-uddevalla** [comment]
@jacobwod @FredrikEkstrom79 @emmafrygne-vbg @JacubPelka. I have just created a draft in Github wiki called 'Geoserver - Tips och Trix'. The purpose is to have a document with short descriptions of how to use Geoserver as an alternative to plattform for HAJK. I've also added a few links of "good examples" of styling, for example Point Stacker transformation (mentioned above). Please continue to fill the wiki-document with more text and examples :-)

**Comment by jacobwod** [comment]
Well done @ingvar-uddevalla, here's the link just for reference: https://github.com/hajkmap/Hajk/wiki/Geoserver-Tips-och-Trix.
