### ISSUE TITLE
PresetLinks, remove param validation.

### ISSUE THREAD

**Issue by jesade-vbg** [hajkmap/Hajk#964]
**I want to be able to target layers only, without XYZ.**

As the presets isn't user specified, only via admin/config, maybe we should remove this check making the tool more useful.

Extract:
```
isValidMapLink = (mapLink) => {
    return (
      mapLink.includes("x=") && mapLink.includes("y=") && mapLink.includes("z=")
    );
};
```

https://github.com/hajkmap/Hajk/blob/ec637adb5d5e48b83d957700d4d875f9cf92847d/new-client/src/controls/PresetLinks.js#L67

**Comment by Hallbergs** [comment]
Sounds good!

**Comment by jacobwod** [comment]
Isn't this what [Bookmarks](https://github.com/hajkmap/Hajk/blob/7378aa1b9c2b8c26846d9ff4ef4de1a6a098dfb2/new-client/src/plugins/Bookmarks/Bookmarks.js#L16) is for?

**Comment by jesade-vbg** [comment]
Well, you can't have any preset bookmarks, the user needs to add these.
It would be nice to be able to have "layers only" links in presets.

**Comment by jacobwod** [comment]
I see. But you're not thinking about removing the _possibility_ to specify `x`, `y` and `z`, only make them optional, right?

**Comment by jesade-vbg** [comment]
Yes, exactly, optional. Maybe validate (xy || z || layers). instead of (xyz). I'll see when the time comes
