### ISSUE TITLE
Add react-markdown to Dialog-based components

### ISSUE THREAD

**Issue by jacobwod** [hajkmap/Hajk#966]
# Summary of changes related to this issue
- The development takes place in [feature/966-markdown-in-dialog.](https://github.com/hajkmap/Hajk/tree/feature/966-markdown-in-dialog)
- **Dialog.js** is now a functional component with the following additions:
  - Dialog will now by default render its contents using react-markdown. It is possible to enable the HTML support too.
  - The old renderer (which relies on `dangeresoulySetInnerHTML`) is now a legacy optional renderer. It's placed in LegacyNonMarkdownRenderer. Admin can decide which renderer will be used.
  - The legacy renderer is still **the default renderer** for the **old Information** plugin. We preserve the current functionality by hard coding this option. If you want to use ReactMarkdown, you should switch to the new plugin: InfoDialog.
- AppModel now supports **plugins with multiple instances**. This is achieved by making the `options` property an array of objects, rather than the usual plain object. AppModel retains backwards compatibility as we still expect most plugins to be one-instance-only. 
- The first multi-instance plugin is added: **InfoDialog**
- InfoDialog is a plugin that build on a new type of plugin windows, called **DialogPluginWindow**. This is quite similar to the BaseWindowPlugin methodology we've been using for some time now: a plugin extends the DialogPluginWindow, it needs only to take care of providing a name, title, icon as well as its' internal contents (the View) - DialogPluginWindow will take care of the rest (rendering Buttons/Control buttons/Widget buttons at appropriate places, etc).
- With the addition of react-markdown rendering in Dialog, we now had two places in Hajk that used react-markdown. The need of consolidating the mappings between Markdown's elements and MUI's components grew bigger, so I created the `customComponentsForReactMarkdown` utility. 
  - Both Dialog and FeaturePropsParsing are using this new, consolidated utility 

# Original issue
## Information: add Markdown to the plugin
Currently the Information plugin is plain-text only. Over the years we've seen a lot of needs for extending this: we want to add basic text formatting, as well as images and videos to the Introduction.

One way to solve it, without introducing new dependencies and/or having to care about Admin UI, is to add a Markdown parser, similar to how it's done in `FeatureInfo.js`.

**Comment by Hallbergs** [comment]
Very nice!

**Comment by jacobwod** [comment]
Here's what I've come up with so far. As a bonus, I've **rewritten Information as a functional component** too. 
https://user-images.githubusercontent.com/110222/146772460-e8f13e36-a071-4fb7-954b-e5d7891f6f58.mov

Some minor stuff to figure out though, but testers are welcome to try out, it's in `develop`.

**Comment by jacobwod** [comment]
Can you clarify why? Plain text and HTML do still work (as in the previous version). The only difference is the addition of MD syntax which you _can_ (but aren't forced to) use.

**Comment by jesade-vbg** [comment]
Actually rehypeRaw is far from the same as dangerouslySetInnerHTML.

rehypeRaw is very destructive to HTML, adding <p>-tags, removing disallowed tags etc.

Passing html thru rehypeRaw causes alot of limitations, and it's the same problem with FeatureInfo.

Usually I only use markdown for end user supplied data, for security reasons. In the FeatureInfo and info dialog cases I'm not so worried as the data only comes from a server config.

I was actually planning to re-add the possibility to use "real" html ni FeatureInfo, as rehypeRaw has caused us lots of problems and limitations.

**Comment by jacobwod** [comment]
OK, no worries, I've reverted it in `develop` as of 6250e70e71886ed2c3ef496488839f80f39769a5 and will continue the work in https://github.com/hajkmap/Hajk/tree/feature/966-markdown-in-dialog.

However, I disagree about the usage of pure HTML, even when it comes from Admin UI. The main issue is that we have no control on how it's rendered, e.g. a `<p>` will always be a pure HTML Paragraph, as opposed to the MUI `Typography` Component (which would give us correct sizing, spacing, colors etc). This becomes even more complex with more styled tags then a pure Paragraph. Try `<blockquote>` in dark mode for example… 

Using this solution gives us the possibility to map e.g.
- `<blockquote>` --> `<Typography variant="quote">

and it all works out fine. This simply can't be done with HTML.

(Of course, when this is implemented, I wouldn't even bother using HTML's `<blockquote>` when Markdown's ` > ` can be used to create the same effect.)

**Comment by jesade-vbg** [comment]
I see your point and I will investigate further.
The biggest problem right now is that if you allow HTML, markup is still rendered. There is no way to skip markup. And all newlines becomes `<p>`. So you have to strip all newlines from html before saving. Otherwise you will get junk like 
```
<p>
<table>
<p>
   <tr>
<p><td></p>
<p>content</p>
<p></td></p>
</p>
</p>
```

Here is an example (not a perfect one) of possible content that markup does not support. Custom rotated table, backgrounds in cells etc
![image](https://user-images.githubusercontent.com/73874338/147090828-b3d742fd-4a62-47bd-8c6d-66bf715f53ac.png)

**Comment by maan002** [comment]
Also attribute colspan in HTML table

**Comment by jacobwod** [comment]
Okay @jesade-vbg, @maan002, I've come up with a solution. `Dialog.js` will still be rewritten as a functional component and have the React Markdown functionality added. But I will provide a switch that will disable this new renderer and use the legaly method (`setDangerousInnerHtml`). This way you can provide a JSON configuration with pure HTML:
```html
<h1>The td colspan attribute</h1>
<table>
  <tr>
    <th>Month</th>
    <th>Savings</th>
  </tr>
  <tr>
    <td>January</td>
    <td>$100</td>
  </tr>
  <tr>
    <td>February</td>
    <td>$80</td>
  </tr>
  <tr>
    <td colspan="2">Sum: $180</td>
  </tr>
</table>
```
And render this (I've marked the table just to show you that it is a table with correct `colspan` on the last row - I didn't bother with styling it the way you do, but you get the idea).
![Skärmavbild 2022-01-03 kl  09 03 55](https://user-images.githubusercontent.com/110222/147909865-a2d08857-ccc3-4546-a40e-2be773d83623.png)

**Comment by Hallbergs** [comment]
Love it!!
