### ISSUE TITLE
`null` gets added to print resolutions if left empty in Admin UI

### ISSUE THREAD

**Issue by jacobwod** [hajkmap/Hajk#971]
Saving this in Admin UI (with no value in `extraPrintResolutions`):
![Skärmavbild 2022-01-11 kl  10 50 09](https://user-images.githubusercontent.com/110222/148920069-562f4e18-f148-4fa1-8022-9357aacbebea.png)

…gives the following in the JSON config file:
```json
"extraPrintResolutions": [
      null
    ],
```

…which, in turn ends up in Client UI:
![image](https://user-images.githubusercontent.com/110222/148920460-36ec0e17-0673-475a-84ff-a0ea8b4c1020.png)

---

This was added in https://github.com/hajkmap/Hajk/commit/9a7de578f13251a14968e51cc9c4b63ea2b244e3, just recently, as a fix of #908. Haven't you noticed the problem in your environment, @jesade-vbg?

**Comment by jesade-vbg** [comment]
OK. No, I get an empty array as expected.
![image](https://user-images.githubusercontent.com/73874338/148929567-f2119e1b-117e-4857-b0f5-67117ff61ed6.png)

In .Net backend: `public double[] extraPrintResolutions { get; set; } `     

But now I just noticed that admin sends [null], so I need to fix the issue in the admin UI.
I guess .Net ignores the null as it's supposed to be a double as input.

**Comment by jacobwod** [comment]
I tried to reach out to you - I've prepared a small fix that sends an empty Array from Admin UI. Please see if it works for you too, hopefully it was that easy.
