### ISSUE TITLE
Search: Links in result preview

### ISSUE THREAD

**Issue by WCarlsson** [hajkmap/Hajk#973]
**Is your feature request related to a problem? Please describe.**
When a search has multiple hits there is the possibility to view a preview of a result. If the result contains links it is easy to believe that it is possible to click these links.

**Describe the solution you'd like**
It should be possible to hoover over the preview and click links if there are any.
![image](https://user-images.githubusercontent.com/38069156/148971615-86e9f598-3c64-4699-b746-f3a5e71d1ae8.png)

**Comment by Hallbergs** [comment]
I don't really agree. 

The idea behind the preview-window was to provide a way for the user to quickly scan the results and see if they are interested to open the actual results. If we would allow the user to interact with the information in the preview-window we would present two ways to interact with the actual information, which might be confusing for the users.

I might be wrong of course! If you decide to implement, a setting in admin (enabling or disabling interaction with the preview-window) would be greatly appreciated!

**Comment by jacobwod** [comment]
I suppose this is stale and propose closing. @WCarlsson, @Hallbergs ok?

**Comment by Hallbergs** [comment]
> I suppose this is stale and propose closing. @WCarlsson, @Hallbergs ok?

Fine by me

**Comment by WCarlsson** [comment]
Fine by me aswell
