### ISSUE TITLE
Bookmark: Some layers does not work

### ISSUE THREAD

**Issue by WCarlsson** [hajkmap/Hajk#990]
**Describe the bug**
When using a saved bookmark some layers aren´t activated at all. The map is moved to the correct location and some layers may activate but not always all. 
This seems to be connected to if the layer id is numerical e.g. id = "1" or a string e.g. id = "k2jhzp". Layers with numerical ids seems to work and layers with string ids doesn´t.

**To Reproduce**

1. Create a bookmark with atleast one layer that has a string id.
2. Reload the map.
3. Click on the newly created bookmark.
4. Notice that the map is moved but the layer is not activated in any way.

**Expected behavior**
The layer(s) in the bookmark should be activated when the bookmark is clicked.
If the id is manually changed in the layers file from a string to a numerical value, the map is fixed in admin and the bookmark is recreated then it works as expected.

**Comment by jacobwod** [comment]
@jesade-vbg Can you please fix how you filter out valid layers? Your code:
https://github.com/hajkmap/Hajk/blob/7378aa1b9c2b8c26846d9ff4ef4de1a6a098dfb2/new-client/src/plugins/Bookmarks/BookmarksModel.js#L29-L33

https://github.com/hajkmap/Hajk/blob/7378aa1b9c2b8c26846d9ff4ef4de1a6a098dfb2/new-client/src/plugins/Bookmarks/BookmarksModel.js#L43-L47

Line 32 and 46 is what leads to this problem: layer IDs are not always numeric anymore.

We have a couple of places in the codebase where we do it to capture all possible layer IDs.

Please use `utils/Validator` instead, the way it's used in AnchorModel for example, line 68:
https://github.com/hajkmap/Hajk/blob/7c0bd94ab23d6f118ba2b2f92bc1d65592f506d3/new-client/src/plugins/Anchor/AnchorModel.js#L63-L70

**Comment by jesade-vbg** [comment]
Sure! I guess it's been like this since the new node backend. I have not noticed.

**Comment by jesade-vbg** [comment]
Could someone with the problem verify that the fix works?

Branch
fix/990-bookmarks

**Comment by jacobwod** [comment]
Thanks @jesade-vbg, should be fine with this solution. Perhaps @WCarlsson can switch to this branch (https://github.com/hajkmap/Hajk/compare/fix/990-bookmarks), build locally and verify? Otherwise we'll just merge it as I'm in the middle of other work right now.

**Comment by WCarlsson** [comment]
Works fine for me, nice work!

**Comment by jesade-vbg** [comment]
Thanx for testing, it's now merged into develop.
