### ISSUE TITLE
Ersätt google font för att följa GDPR

### ISSUE THREAD

**Issue by larsam0524** [hajkmap/Hajk#996]
Genom att använda google font i hajk, finns det risk att man bryter mot GDPR/dataskyddsförordningen genom att vi utlämnar IP-nummer till tredje land utan möjlighet för användaren att samtycka. 

Jag föreslår att man försöker att hitta en ersättning av google font, och lägger med det direkt i installationspaketen så fonterna ligger på servern och vi undviker tredjelandsöverföring av personuppgifter vid användning av hajk.  

Credit: Urspungligen ett påpekande från SBK Göteborg, som har implementerat en ersättning på sina externa kartor.

**Comment by Hallbergs** [comment]
The roboto font is installed locally since https://github.com/hajkmap/Hajk/issues/809, (if i recall correctly, it was shipped in release 3.7).

Please avoid Swedish and use English for future issues.
