### ISSUE TITLE
OL interactions options are not saved when using .Net backend

### ISSUE THREAD

**Issue by perosoderstrom** [hajkmap/Hajk#998]
**Describe the bug**
OpenLayers map interactions options ("Kartinteraktioner") are not saved to map file when using .Net backend.

**To Reproduce**

Running in .Net backend:
1. Open /admin
2. Choose Kartor - Inställningar
3. Change some Kartinteraktioner
4. Spara
5. Check the map file in mapservice/App_Data/(map file).json
No options are saved.

**Additional context**
The options {get;set;} are missing in MapSettings.cs

**Comment by Hallbergs** [comment]
Closed via #1000
