### ISSUE TITLE
documenthandler 2.0 - print font bug

### ISSUE THREAD

**Issue by emmafrygne-vbg** [hajkmap/Hajk#999]
**Describe the bug**
When printing from documenthandler second time (and after that) the font in the document is behaving strange. See screenshots below for example. 

First print
![image](https://user-images.githubusercontent.com/59825341/152511147-44abc148-6462-46fd-9747-2c96d7e2ce89.png)

Second print
![image](https://user-images.githubusercontent.com/59825341/152511203-3fe76636-b693-4812-9764-7a3250d1f351.png)

**To Reproduce**
In client print from documenthandler a first time (or with clean cache if you have printed before) and see that the print looks good. Print a second time and see that the font is behaving strange. Some headings are huge and line spacing is not the same as before. If you clean the cache in your browser and print again it looks good the first time again, but not the second time and the problem with fonts appears again. 

It also seems to be a problem with huge headings that are connected with if a heading have a connection with a document in the meny in admin or not. If the document doesn't have a connection the heading will be huge (in the first print too)
![image](https://user-images.githubusercontent.com/59825341/152512971-5b324da1-fb82-4860-baec-6f90034448cb.png)
![image](https://user-images.githubusercontent.com/59825341/152521731-37b4f7a7-878b-4029-b9b8-e3a5177c34b4.png)

**Expected behavior**
Have the same print as the first time.

**Comment by Hallbergs** [comment]
This should be solved via https://github.com/hajkmap/Hajk/pull/937/commits/c04d4a23144417f292c930051cc54a4e5e51c6e8 (in develop atm, will be shipped in 3.9).
